### PR TITLE
Expand DocTest's RegExp to allow Unicode and Multi-line inside opaque inspect types

### LINKED ISSUE #5100: Doctests cannot handle Unicode
### Environment

* Elixir version (elixir -v): 1.3.2 (and probably older versions as well)
* Operating system: Linux Mint.

### Current behavior

I am creating a library called [Tensor](https://github.com/Qqwy/tensor/), which allows people to work with Vectors, Matrices and higher-dimension Tensors. 

These data structures are implemented as Structs, with an overridden Inspect protocol. A matrix, for instance, looks like this:

```
iex(1)> mat = Matrix.new([[1,2],[3,4]], 2,2)
#Matrix-(2×2)
┌                 ┐
│       1,       2│
│       3,       4│
└                 ┘

```

This looks great, and works fine. However, I started writing more documentation today, including some doctests. That is where it goes wrong.

[My example doctest](https://github.com/Qqwy/tensor/blob/non_compiling_doctest/lib/tensor.ex#L154) for `Tensor.pop` (an implementation `pop` function of the Access protocol), is as follows:

```
iex> mat = Matrix.new([[1,2],[3,4]], 2,2)   
      iex> Tensor.pop(mat, 0)   
      {#Vector-(2)[1, 2],
       #Matrix-(2×2)
      ┌                 ┐
      │       0,       0│
      │       3,       4│
      └                 ┘
      }
```
When now running `mix test`, I get the following result:

```
 1) test doc at Tensor.pop/3 (1) (TensorTest)
     test/tensor_test.exs:3
     Doctest did not compile, got: (SyntaxError) lib/tensor.ex:158: unexpected token: "┌" (column 1, codepoint U+250C)
     code: {#Vector-(2)[1, 2],
            #Matrix-(2×2)
           ┌                 ┐
           │       0,       0│
           │       3,       4│
           └                 ┘
           }
     stacktrace:
       lib/tensor.ex:156: Tensor (module)

```

As can be seen, the doctest functionality cannot properly handle the Unicode.

### Expected behavior

I would expect the doctests to be able to handle Unicode characters in the inspect output.

### LINKED ISSUE #5103: Doctest 'opaque type' regular expression is too restrictive
### Environment

* Elixir version (elixir -v): 1.3.2
* Operating system: Linux Mint

### Current behavior

This is sort of a follow-up on #5100.

I followed the documentation on DocTests outlined [here](http://elixir-lang.org/docs/stable/ex_unit/ExUnit.DocTest.html#module-opaque-types), which states that opaque types are matched specially, because they start with a `#` (and these are also used inside doctests to create explanatory comments).

However, even with the inspect-format of the vectors and matrices changed slightly so they follow the  `#Name<...>`-format and editing the example code changed so opaque types and non-opaque types are no longer used interchangeably, it still does not work:

```
      iex> mat = Matrix.new([[1,2],[3,4]], 2,2)   
      iex> {vector, mat2} = Tensor.pop(mat, 0)   
      iex> vector
      #Vector<(2)[1, 2]>
      iex> mat2
      #Matrix<(2×2)
      ┌                 ┐
      │       0,       0│
      │       3,       4│
      └                 ┘
      >
``` 

This has as output:
```
  1) test doc at Tensor.pop/3 (1) (TensorTest)
     test/tensor_test.exs:3
     Doctest failed
     code: mat = Matrix.new([[1,2],[3,4]], 2,2)   
            {vector, mat2} = Tensor.pop(mat, 0)   
            vector === #Vector-(2)[1, 2]
     lhs:  #Vector-(2)[1, 2]
     stacktrace:
       lib/tensor.ex:156: Tensor (module)
```

Therefore, I started digging in the source code of ExUnit.

It turns out that [on line 592 in the DocTest module](https://github.com/elixir-lang/elixir/blob/v1.3.2/lib/ex_unit/lib/ex_unit/doc_test.ex#L592) there exists a Regular Expression that checks for the special case of coming across an opaque type:

```
~r/^#[A-Z][\w\.]*<.*>$/
```

This regular expression:

- does not match unicode characters.
- does not match multi-line inspect results.

### Expected behavior

An altered regular expression is used ,which _does_ allow for the two cases mentioned above. An example would be:

```
~r/\A#[A-Z][\w\.]*<(.|\n)*>\n?\z/um
```
_(This also allows for the case where a multi-line inspect is constructed using heredocs (`"""`), which add a final `\n` at the end)_

### PR DESCRIPTION
**Pull request by Qqwy**
- DocTest Regex changed to:
  - Allow Unicode
  - Allow multiline statements.
    - Doctest will still match if Inspect output ends with a `\n`.
  - Instead of enforcing `#Name<...>` now enforces `#Name<...` (Trailing `>` no longer required) for opaque inspect types.

Fixes #5103. Fixes #5100.

Also contains some very poetic specs. :innocent:

### CODE REVIEW

File: lib/ex_unit/lib/ex_unit/doc_test.ex [hunk 1]
```diff
@@ -599,7 +599,7 @@ defmodule ExUnit.DocTest do
         [mod, message] = :binary.split(error, ")")
         {:error, Module.concat([mod]), String.trim_leading(message)}
       _ ->
-        if string =~ ~r/^#[A-Z][\w\.]*<.*>$/ do
+        if string =~ ~r/\A#[A-Z][\w\.]*<(.|\n)*?\z/mu do
```
Comment (josevalim) [inline lib/ex_unit/lib/ex_unit/doc_test.ex]: Couldn't it be `~r/\A#[A-Z][\w\.]*</mu`?

**Comment by josevalim** [comment]
Just one comment and it looks good to go!

**Comment by Qqwy** [comment]
All right, all don!

**Comment by josevalim** [comment]
:shipit:

File: lib/ex_unit/test/ex_unit/doc_test_test.exs [hunk 2]
```diff
@@ -217,6 +217,71 @@ defmodule ExUnit.DocTestTest.Numbered do
...
+        #{haiku.first_phrase}
+        #{haiku.second_phrase}
+        #{haiku.third_phrase}#{author_str}
+      >
+      """
+    end
+  end
+end |> write_beam
+
+
```
Comment (lexmag) [inline lib/ex_unit/test/ex_unit/doc_test_test.exs]: Unnecessary line. ✂️

File: lib/ex_unit/test/ex_unit/doc_test_test.exs [hunk 3]
```diff
@@ -217,6 +217,71 @@ defmodule ExUnit.DocTestTest.Numbered do
...
+      # Haiku with Unicode characters (Japanese Kanji, em-dash).
+      iex> ExUnit.DocTestTest.Haiku.new("古池や","蛙飛びこむ","水の音", "Matsuo Basho")
+      #Haiku<
+        古池や
+        蛙飛びこむ
+        水の音
+        ― Matsuo Basho
+      >
+
+
```
Comment (lexmag) [inline lib/ex_unit/test/ex_unit/doc_test_test.exs]: Unnecessary line. ✂️

File: lib/ex_unit/test/ex_unit/doc_test_test.exs [hunk 4]
```diff
@@ -217,6 +217,71 @@ defmodule ExUnit.DocTestTest.Numbered do
...
+  ## Examples:
+  
+      # Simple Haiku, inspect output consists of multiple lines.
+      iex> ExUnit.DocTestTest.Haiku.new( "Haikus are easy","But sometimes they don't make sense","Refrigerator")
+      #Haiku<
+        Haikus are easy
+        But sometimes they don't make sense
+        Refrigerator
+      >
+
```
Comment (lexmag) [inline lib/ex_unit/test/ex_unit/doc_test_test.exs]: Unnecessary line. ✂️

File: lib/ex_unit/test/ex_unit/doc_test_test.exs [hunk 5]
```diff
@@ -217,6 +217,71 @@ defmodule ExUnit.DocTestTest.Numbered do
...
+      first_phrase: first,
+      second_phrase: second,
+      third_phrase: third,
+      author: author
+    }
+  end
+
+  defimpl Inspect do
+    def inspect(haiku, _opts) do
+      author_str = if haiku.author == "", do: "", else: "\n  ― #{haiku.author}"
```
Comment (lexmag) [inline lib/ex_unit/test/ex_unit/doc_test_test.exs]: This seems unnecessary check.

Comment (lexmag) [inline lib/ex_unit/test/ex_unit/doc_test_test.exs]: Nope, it's actually used.

**Comment by lexmag** [comment]
Thank you @Qqwy. I'll clean these lines in the following commit. 💛

**Comment by Qqwy** [comment]
Thanks a lot, @lexmag! :-)

:tada:
