### PR TITLE
Do not emit warning when "with" clause always matches

### LINKED ISSUE #4556: Misleading warning when "with" clause always matches
### Environment

* Elixir version (elixir -v): 1.2.3
* Operating system: Windows 10

### Current behavior

When the following code is compiled:

```
defmodule Test do
    def something do
        with something <- get_value,
                do: something
    end
    
    defp get_value do
        :ok
    end
end 
```

The following warning is emitted by the compiler:

> PS D:\temp> elixirc .\warning.exs
> warning.exs:3: warning: this clause cannot match because a previous clause at line 3 always matches

### Expected behavior

This warning is misleading to me as an elixir newbie because it's claiming an always matching assignment will fail because the same pattern always matches.  It also makes it sound like like the `with` functionality will bail out early since it's claiming it won't match, even though the `with` statement will continue on.

### PR DESCRIPTION
**Pull request by lexmag**
Closes #4556.

### CODE REVIEW

File: lib/elixir/src/elixir_with.erl [hunk 1]
```diff
@@ -68,27 +68,34 @@ translate(Meta, Args, S) ->
...
     end,
   {TC, TS} = elixir_translator:translate(CaseExpr, S#elixir_scope{extra=nil}),
   {TC, elixir_scope:mergec(S, TS)}.
 
-build_cases([{'<-', Meta, [Left, Right]} | Rest], DoExpr, Wrapper) ->
-  Other = {'other', Meta, ?MODULE},
+build_case([{'<-', Meta, [Left, Right]} | Rest], DoExpr, Wrapper, S) ->
+  case Left of
+    {Name, _Meta, nil} when is_atom(Name) ->
+      Message = "this matching clause will always yield the same result",
```
Comment (whatyouhide) [inline lib/elixir/src/elixir_with.erl]: Maybe we can do something like:

```erlang
build_case([{'<-', Meta, [Left, Right]} = Clause, ...) ->
  ...
  Message = io_lib:format("this matching clause will always yield the same result: ~s~n",
                          ['Elixir.Macro':to_string(Clause)]),
  ...
```

so that the culrpit is more easily identifiable? I'm saying this because in the test you added (`with 1 <- 1, result <- self(), do: result`) it's not very clear which expression we're referring to (since `1 <- 1` always matches as well) and we only have line information. Wdyt?

Comment (lexmag) [inline lib/elixir/src/elixir_with.erl]: I thought about that but it won't gonna work perfectly since at this point we get this clause in the rewritten shape, e.g. `1 in qwe` will be printed as `Enum.member?(qwe, 1)`.

Comment (whatyouhide) [inline lib/elixir/src/elixir_with.erl]: Ah, I see, good call then.

**Comment by ericmj** [comment]
I think we should also say how the user should fix the error. In my experience people that get this warning often do not know they should use `=` instead of `<-` so I think we should point them to `=`.

File: lib/elixir/src/elixir_with.erl (hunk 1 above)
Comment (josevalim) [inline lib/elixir/src/elixir_with.erl]: The error message should be something alongside:

    the variable "~ts" on the left side of <- inside "with" will always match. If you want to assign to a variable, use = instead of <-. The latter is reserved to match on patterns

**Comment by josevalim** [comment]
@lexmag @ericmj After I wrote the new error message... I am wondering... what if we just make it work? I don't see why we need to differentiate between `<-` and `=`. Both will work and get the same result.

**Comment by whatyouhide** [comment]
I was bit 👎 on not emitting a warning, even if we don't *need* to emit it and we can make it work, just for consistency. But now that I think about it, a variable *is* a valid pattern, so yeah we can make both `<-` and `=` work, but then what's the point of `=`?

**Comment by josevalim** [comment]
@whatyouhide you can still use `{:ok, foo} = bar`. Variables is the only exception were both have the same meaning.

**Comment by whatyouhide** [comment]
@josevalim ah, if you want it to fail, I see. But anyways, the point about a variable being a valid pattern still holds I think, even if it's useless to do so in `with`.

**Comment by josevalim** [comment]
@whatyouhide exactly. it is probably best to not emit a warning in this case. it is a valid pattern, we know exactly what it means. I don't think we are gaining much by asking the user to change it to use a `=`.

**Comment by lexmag** [comment]
Can you think about any counterexample? Maybe bad resolving of merge conflicts?

**Comment by josevalim** [comment]
@lexmag ?

**Comment by lexmag** [comment]
Alright, we're not doing warning but making a rewriting. :bowtie:
