### PR TITLE
Remove invalid UTF-8 code from assertion failures

### LINKED ISSUE #7434: ex_unit crash with invalid utf8 in doctests
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.7.0-dev (24790a80b) (compiled with OTP 20)
```
* Operating system: macOS

### Current behavior

Given a following doctest:

```elixir
      iex> Jason.encode("invalid utf8 \xFF")
      {:error, ""}
```

`mix test` crashes with:

```
=ERROR REPORT==== 9-Mar-2018::08:55:29 ===
** Generic server <0.164.0> terminating
** Last message in was {'$gen_cast',
                        {test_finished,
                         #{'__struct__' => 'Elixir.ExUnit.Test',
                           'case' => 'Elixir.JasonTest',logs => <<>>,
                           module => 'Elixir.JasonTest',
                           name => 'doctest Jason.encode/2 (6)',
                           state =>
                            {failed,
                             [{error,
                               #{'__exception__' => true,
                                 '__struct__' =>
                                  'Elixir.ExUnit.AssertionError',
                                 args => ex_unit_no_meaningful_value,
                                 expr =>
                                  <<"Jason.encode(\"invalid utf8 ÿ\")">>,
                                 left => ex_unit_no_meaningful_value,
                                 message =>
                                  <<"Doctest did not compile, got: (UnicodeConversionError) invalid encoding starting at <<255, 34, 41>>">>,
                                 right => ex_unit_no_meaningful_value},
                               [{'Elixir.Jason','__MODULE__',0,
                                 [{line,113},{file,<<"lib/jason.ex">>}]}]}]},
                           tags =>
                            #{async => true,'case' => 'Elixir.JasonTest',
                              describe => nil,describe_line => nil,
                              file =>
                               <<"/Users/michalmuskala/src/oss/jason/test/jason_test.exs">>,
                              line => 4,module => 'Elixir.JasonTest',
                              registered => #{},
                              test => 'doctest Jason.encode/2 (6)',
                              type => doctest},
                           time => 8}}}
** When Server state == #{colors => [{enabled,true}],
                          excluded_counter => 0,failure_counter => 1,
                          invalid_counter => 0,seed => 757800,
                          skipped_counter => 0,slowest => 0,
                          test_counter => #{doctest => 1},
                          test_timings =>
                           [#{'__struct__' => 'Elixir.ExUnit.Test',
                              'case' => 'Elixir.JasonTest',logs => <<>>,
                              module => 'Elixir.JasonTest',
                              name => 'doctest Jason.encode/2 (5)',
                              state =>
                               {failed,
                                [{error,
                                  #{'__exception__' => true,
                                    '__struct__' =>
                                     'Elixir.ExUnit.AssertionError',
                                    args => ex_unit_no_meaningful_value,
                                    expr =>
                                     <<"Jason.encode(%{}) === \"%{}\"">>,
                                    left => {ok,<<"{}">>},
                                    message => <<"Doctest failed">>,
                                    right => ex_unit_no_meaningful_value},
                                  [{'Elixir.Jason','__MODULE__',0,
                                    [{line,110},
                                     {file,<<"lib/jason.ex">>}]}]}]},
                              tags =>
                               #{async => true,'case' => 'Elixir.JasonTest',
                                 describe => nil,describe_line => nil,
                                 file =>
                                  <<"/Users/michalmuskala/src/oss/jason/test/jason_test.exs">>,
                                 line => 4,module => 'Elixir.JasonTest',
                                 registered => #{},
                                 test => 'doctest Jason.encode/2 (5)',
                                 type => doctest},
                              time => 1518}],
                          trace => false,width => 80}
** Reason for termination ==
** {badarg,
       [{io,put_chars,
            [standard_io,unicode,
             [<<"  2) doctest Jason.encode/2 (6) (JasonTest)\n     \e[1m\e[30mtest/jason_test.exs:4\e[0m\n     \e[31mDoctest did not compile, got: (UnicodeConversionError) invalid encoding starting at <<255, 34, 41>>\e[0m\n     \e[36mcode: \e[0mJason.encode(\"invalid utf8 ÿ\")\n     \e[36mstacktrace:\e[0m\n       lib/jason.ex:113: Jason (module)\n">>,
              10]],
            []},
        {'Elixir.ExUnit.CLIFormatter',handle_cast,2,
            [{file,"lib/ex_unit/cli_formatter.ex"},{line,107}]},
        {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},
        {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},
        {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}

```

### Expected behavior

The test should not crash.

### PR DESCRIPTION
**Pull request by devonestes**
We were having issues with trying to write invalid UTF-8 sequences to
the console in the CLI formatter because if it was possible, we would
try and print the code that was failing in the failure message. This is
totally helpful, but we unfortunately can't print invalid UTF-8, so if
the code failed because it was invalid UTF-8, we can't show the user
that code.

We do still get the sequence that failed, and the line number that it
was on, so I'm hoping that this is still going to be enough for folks
to fix whatever issues they have.

Resolves #7434

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks @devonestes!

I am wondering if this is the best fix. Generally speaking, the `:code` that comes from regular tests cannot be invalid because otherwise the test would not run in the first place.

So to seems to be an issue exclusive to doctests and I wonder if we should tackle it there. Probably around [here](https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/doc_test.ex#L412-L416) by skipping the `expr: ...` key if the underlying String is not valid?

**Comment by devonestes** [comment]
Ok, that works for me.

My thinking was that since that `expr` binary isn't technically "invalid", it's just not valid UTF-8, and so we can't print it to the console. That's why I thought we should only remove those code examples that we are unable to print to the console while we're formatting these errors for printing to the console.

I'll tack on another commit and we can see how this other solution looks.

**Comment by devonestes** [comment]
Yeah, this is a nice and simple solution. I like it 😄

File: lib/ex_unit/lib/ex_unit/doc_test.ex [hunk 1]
```diff
@@ -411,9 +412,13 @@ defmodule ExUnit.DocTest do
         quote do
           message = "Doctest did not compile, got: #{unquote(ex_message)}"
 
-          reraise ExUnit.AssertionError,
-                  [message: message, expr: unquote(String.trim(expr))],
-                  unquote(stack)
+          if unquote(String.valid?(expr)) do
```
Comment (josevalim) [inline lib/ex_unit/lib/ex_unit/doc_test.ex]: You can do this check at compilation time. So move the conditional out of the quote and then do something like:

    reraise ExUnit.AssertionError, unquote(opts), unquote(stack)

Please let me know if you have any questions. :)

Comment (devonestes) [reply lib/ex_unit/lib/ex_unit/doc_test.ex]: Got it 😉

**Comment by michalmuskala** [comment]
Thank you! :heart:
