### PR TITLE
Fix logger crash when :gen_statem format_status/2 returns non-tuple

### LINKED ISSUE #13682: Failure while translating Erlang's logger event (gen_statem)
👋 

### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.17.1 (compiled with Erlang/OTP 27)

### Operating system

mac

### Current behavior

```elixir
iex(1)> Mix.install [:postgrex]
:ok
iex(2)> Postgrex.start_link(backoff_type: :stop, max_restarts: 0, database: "plausible_dev")
{:ok, #PID<0.198.0>}
```
results in "Failure while translating Erlang's logger event"
```
01:40:10.853 [error] Postgrex.Protocol (#PID<0.200.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused

01:40:10.855 [error] Failure while translating Erlang's logger event
** (MatchError) no match of right hand side value: %{label: {:gen_statem, :terminate}, name: #PID<0.200.0>, reason: {:error, %DBConnection.ConnectionError{message: "tcp connect (localhost:5432): connection refused - :econnrefused", severity: :error, reason: :error}, [{DBConnection.Connection, :handle_event, 4, [file: ~c"lib/db_connection/connection.ex", line: 122, error_info: %{module: Exception}]}, {:gen_statem, :loop_state_callback, 11, [file: ~c"gen_statem.erl", line: 3115]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 329]}]}, log: [], state: Postgrex.Protocol, queue: [internal: {:connect, :init}], modules: [DBConnection.Connection], client_info: :undefined, process_label: :undefined, callback_mode: &DBConnection.Connection.handle_event/4, postponed: [], timeouts: {0, []}, state_enter: false}
    (logger 1.17.1) lib/logger/translator.ex:306: Logger.Translator.report_gen_statem_terminate/2
    (logger 1.17.1) lib/logger/utils.ex:47: Logger.Utils.translate/5
    (logger 1.17.1) lib/logger/utils.ex:25: Logger.Utils.translator/2
    (kernel 10.0) logger_backend.erl:102: :logger_backend.do_apply_filters/4
    (kernel 10.0) logger_backend.erl:87: :logger_backend.apply_filters/4
    (kernel 10.0) logger_backend.erl:33: :logger_backend.log_allowed/3
    (stdlib 6.0) gen_statem.erl:4309: :gen_statem.terminate/7
    (stdlib 6.0) proc_lib.erl:329: :proc_lib.init_p_do_apply/3

** (EXIT from #PID<0.104.0>) shell process exited with reason: killed
```

### PR DESCRIPTION
**Pull request by sabiwara**
Closes #13682

Will backport after merge.

### CODE REVIEW

File: lib/logger/lib/logger/translator.ex [hunk 1]
```diff
@@ -324,12 +324,19 @@ defmodule Logger.Translator do
         ["\nPostponed: #{inspect(postponed, inspect_opts)}"]
 
     if min_level == :debug do
+      state_info =
+        case state do
+          {state, data} ->
```
Comment (josevalim) [inline lib/logger/lib/logger/translator.ex:329]: Couldn't this be a user defined tuple then? That we think is State+Data, but it is just something else? How does Erlang/OTP report those? Is there another key we could look at instead?

Comment (sabiwara) [reply lib/logger/lib/logger/translator.ex:329]: Good call, I should really always ask myself "what would Erlang do?" 😄

Indeed, it seems there is no such thing as State-Data unpacking, just `State`: https://github.com/erlang/otp/blob/OTP-27.0/lib/stdlib/src/gen_statem.erl#L4554-L4616. Will fix accordingly.

File: lib/logger/test/logger/translator_test.exs [hunk 2]
```diff
@@ -552,6 +570,34 @@ defmodule Logger.TranslatorTest do
     assert_receive {:event, {:string, ["Process " | _]}, _process_metadata}
   end
 
+  test "translates :gen_statem crashes when format_status/2 does not return a tuple" do
```
Comment (sabiwara) [inline lib/logger/test/logger/translator_test.exs:573]: Should we keep this test just in case to prevent similar regressions?
It feels like a bit artificial now that there is no code assuming a tuple in the first place.
No strong opinion.

File: lib/logger/lib/logger/translator.ex (hunk 1 above)
Comment (sabiwara) [reply lib/logger/lib/logger/translator.ex]: [dadb797](https://github.com/elixir-lang/elixir/pull/13684/commits/dadb7974bafa99cd28e781a71544c957edaf9893) ✅

File: lib/logger/test/logger/translator_test.exs (hunk 2 above)
Comment (josevalim) [reply lib/logger/test/logger/translator_test.exs:573]: I would nuke it, yeah. :)

Comment (josevalim) [reply lib/logger/test/logger/translator_test.exs:573]: Sorry, to be clear, we should have tests for both styles of `gen_statem`, but perhaps we should change its name.

Comment (sabiwara) [reply lib/logger/test/logger/translator_test.exs]: OK, like [578e043](https://github.com/elixir-lang/elixir/pull/13684/commits/578e0434c69f1107d20019b21a27ebc895b15787)?

File: lib/logger/test/logger/translator_test.exs [hunk 3]
```diff
@@ -552,6 +570,34 @@ defmodule Logger.TranslatorTest do
...
+    assert capture_log(:debug, fn ->
+             catch_exit(:gen_statem.call(pid, :error))
+           end) =~ ~r"""
+           \[error\] :gen_statem #PID<\d+\.\d+\.\d+> terminating
+           \*\* \(RuntimeError\) oops
+           .*
+           Queue: .*
+           Postponed: \[\]
+           State: :ok
+           Callback mode: .*, state_enter: false
```
Comment (sabiwara) [inline lib/logger/test/logger/translator_test.exs:585]: Note: I can't check for callback mode because of https://github.com/erlang/otp/issues/8605

**Review by josevalim — APPROVED** [review]
Ship it! Also please backport it!

**Comment by sabiwara** [comment]
[Backported](https://github.com/elixir-lang/elixir/commits/v1.17/) ✅
