### PR TITLE
Accordingly mark top level optional dependencies from child deps

### LINKED ISSUE #7990: mix test fails: could not find application file: decimal.app (with 1.7)
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
   - Erlang/OTP 21 [erts-10.0.3]
   - Elixir 1.7.0 (compiled with Erlang/OTP 21)

* Operating system:  
   - macOS

### Current behavior

I have a big umbrella project that fails with Elixir 1.7.0. When I cd into some of the umbrella apps and run the tests, I get the following error:

```
$ mix test
** (Mix) Could not start application decimal: could not find application file: decimal.app
```

### Expected behavior

I think tests should run. They worked with v1.6.6. 

Any thoughts?

### PR DESCRIPTION
**Pull request by josevalim**
Closes #7990

### CODE REVIEW

**Comment by josevalim** [comment]
This should be backported and we should release v1.7.2.

File: lib/mix/lib/mix/dep.ex [hunk 1]
```diff
@@ -117,18 +117,42 @@ defmodule Mix.Dep do
...
+
+    Enum.map(children, fn %{app: app} = dep ->
+      case top_level do
+        %{^app => child_opts} ->
+          # Only top level dependencies can be optional.
+          # Any non-top level dependency that is optional and
+          # is still available means it has been fulfilled.
+          opts =
+            dep.opts
+            |> Keyword.drop(@child_keep_opts)
```
Comment (ericmj) [inline lib/mix/lib/mix/dep.ex]: Is it correct to explicitly `drop`? I don't think we should remove the `:runtime` option unless it exist at a higher level for example.

File: lib/mix/lib/mix/dep.ex [hunk 2]
```diff
@@ -117,18 +117,42 @@ defmodule Mix.Dep do
...
+          child <- dep.deps,
+          do: {child.app, Keyword.take(child.opts, @child_keep_opts)},
+          into: %{}
+
+    Enum.map(children, fn %{app: app} = dep ->
+      case top_level do
+        %{^app => child_opts} ->
+          # Only top level dependencies can be optional.
+          # Any non-top level dependency that is optional and
+          # is still available means it has been fulfilled.
```
Comment (ericmj) [inline lib/mix/lib/mix/dep.ex]: The comment needs to be updated regarding `:runtime`.

File: lib/mix/test/mix/dep_test.exs [hunk 3]
```diff
@@ -509,6 +509,56 @@ defmodule Mix.DepTest do
...
+        # Check that the child dependency is top_level and optional
+        [%Mix.Dep{app: :git_repo, top_level: true, opts: opts}] = Mix.Dep.cached()
+        true = Keyword.fetch!(opts, :optional)
+        """)
+
+        Mix.Tasks.Deps.Get.run([])
+        Mix.Tasks.Deps.Compile.run([])
+      end)
+    end)
+  end
```
Comment (ericmj) [inline lib/mix/test/mix/dep_test.exs]: Great test 👏

File: lib/mix/lib/mix/dep.ex (hunk 1 above)
Comment (josevalim) [reply lib/mix/lib/mix/dep.ex]: Yes, whatever is given upstream should be ignored. That's because we assume an implicit default of true. So even if downstream specifies false, the dependency still wants it to be true (because it requires it!)

File: lib/mix/lib/mix/dep.ex (hunk 2 above)
Comment (josevalim) [reply lib/mix/lib/mix/dep.ex]: Done!

File: lib/mix/lib/mix/dep.ex (hunk 1 above)
Comment (josevalim) [reply lib/mix/lib/mix/dep.ex]: I have pushed a new test to emphasize why the drop matters!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
