### PR TITLE
Fix logger truncate for multi-byte characters

### LINKED ISSUE #9766: Logger truncate fails for multi-byte UTF-8 characters
Logger incorrectly handles multi-byte UTF-8 characters

### Environment
Elixir 1.11.0-dev (b62a23d) (compiled with Erlang/OTP 22)

### Current behavior
```elixir
require Logger
Logger.configure(truncate: 15)
Logger.info("𠜎𠜱𠝹𠱓")
```
produces 
```
22:20:35.456 [info]  𠎜𠜱𠝹 (truncated)
```

### Expected behavior
```
22:20:35.456 [info]  𠜎𠜱𠝹 (truncated)
```

### PR DESCRIPTION
**Pull request by akash-akya**
Fixes #9766

### CODE REVIEW

File: lib/logger/lib/logger/utils.ex [hunk 1]
```diff
@@ -81,7 +81,7 @@ defmodule Logger.Utils do
   end
 
   defp fix_binary(<<h, t::binary>>, acc) do
-    fix_binary(t, <<h, acc::binary>>)
+    fix_binary(t, <<acc::binary>> <> <<h>>)
```
Comment (josevalim) [inline lib/logger/lib/logger/utils.ex]:
```suggestion
    fix_binary(t, <<acc::binary, h>>)
```

Comment (akash-akya) [reply lib/logger/lib/logger/utils.ex]: addressed

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
