### PR TITLE
When all tests are excluded, colorize summary in yellow with message

### LINKED ISSUE #11825: Unexpected behaviour for `mix test` when line is before the first test declaration
### Environment

Elixir & Erlang/OTP versions (elixir --version): 1.13.4 / OTP 24
Operating system: Linux

### Current behavior

Take this repo https://github.com/eksperimental/missing_test/
and run

`mix test test/failing_test_test.exs:3`

image

It looks all good. I'm happy.  It all looks green!
Nope. No test was executed. All four tests fail in reality.

### Expected behavior

If no test is executed I expect a message in red or yellow to catch my attention.
Nobody runs `mix test` to run no tests.

Related issue: https://github.com/elixir-lang/elixir/issues/11824

### PR DESCRIPTION
**Pull request by solar05**
Fixes #11825 
Code example:
```elixir
ExUnit.start(seed: 0, exclude: :skip)

defmodule SkippedTest do
  use ExUnit.Case

  @tag :skip
  describe "skip test" do
    test "integers" do
      assert 1 == 1
    end
  end
end
```

Result:
image

### CODE REVIEW

File: lib/ex_unit/lib/ex_unit/cli_formatter.ex [hunk 1]
```diff
@@ -290,9 +291,17 @@ defmodule ExUnit.CLIFormatter do
...
     cond do
-      config.failure_counter > 0 or force_failures? -> IO.puts(failure(message, config))
-      config.invalid_counter > 0 -> IO.puts(invalid(message, config))
-      true -> IO.puts(success(message, config))
+      config.failure_counter > 0 or force_failures? ->
+        IO.puts(failure(message, config))
+
+      config.invalid_counter > 0 ->
+        IO.puts(invalid(message, config))
+
```
Comment (solar05) [inline lib/ex_unit/lib/ex_unit/cli_formatter.ex:299]: This changes provided by `mix lint` command

**Comment by eksperimental** [comment]
Thank you @solar05 for looking after this.
I am wondering if a color change would be enough to tall the attention.
How about adding a message bellow, saying "No tests have been run"

**Comment by solar05** [comment]
@eksperimental, thanks for suggestion! Update PR description screenshot with additional message 👌

**Comment by josevalim** [comment]
Thank you for the PR. Can you please do two changes?

1. I am wondering if we should change the error message and move it up. Maybe it should be:

```
All tests have been excluded.  [in yellow]

Finished in ...
1 test, 0 failures, 1 excluded
```

And then we only show if it there is tests > 0 and all of them are excluded? Thoughts?

2. Let's add a test to ex_unit_test.exs that verifies the message above appears once we exclude all tests.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
