### PR TITLE
Invalidate a module's tests if an on_exit hook errors in setup_all

### LINKED ISSUE #10974: Failure in linked process during ExUnit on_exit doesn't change process exit code
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.10.4 OTP 22
* Operating system: Ubuntu 

### Current behavior

The issue is very similar to https://github.com/elixir-lang/elixir/issues/5967 except here, it is about the [on_exit/2](https://hexdocs.pm/ex_unit/ExUnit.Callbacks.html#on_exit/2) callback: if an error occurs during the callback, that error does not influence the exit code. Also, the test is marked as succesful (despite the message "all tests have been invalidated")

```Elixir
defmodule SampleTest do
  use ExUnit.Case
  doctest Sample

  setup_all do
    on_exit(fn -> raise "boom" end)

    :ok
  end

  test "greets the world" do
    assert Sample.hello() == :world
  end
end
```

```
  1) SampleTest: failure on setup_all callback, all tests have been invalidated
     ** (RuntimeError) boom
     stacktrace:
       test/sample_test.exs:6: anonymous fn/0 in SampleTest.__ex_unit_setup_all_0/1
       (ex_unit 1.10.4) lib/ex_unit/on_exit_handler.ex:142: ExUnit.OnExitHandler.exec_callback/1
       (ex_unit 1.10.4) lib/ex_unit/on_exit_handler.ex:128: ExUnit.OnExitHandler.on_exit_runner_loop/0



Finished in 0.03 seconds
1 test, 0 failures
```

### Expected behavior

A non-zero exit code and the tests affected by the setup_all where the on_exit callback was initialized should be marked as failed.

### PR DESCRIPTION
**Pull request by QuinnWilton**
This resolves #10974

There's two separate changes here, and I've tried to summarize them in their respective commits.

The first commit fixes the count emitted by the `ExUnit.CLIFormatter`, in the event that a module's tests are invalidated. This seemed to be a simple case of properly updating the `failure_counter` when a module finishes with an error, taking care to not double-count the failed tests.

The second commit fixes the exit code emitted when a module's tests are invalidated, and also ensures that those invalidated tests are added to the `ExUnit.FailuresManifest`. This is a very similar change, and modifies `ExUnit.RunnerStats` to handle `:module_finished` messages, by invalidating any tests within a failed module.

I've never worked with the `ExUnit` codebase before, so it's entirely possible that these changes aren't in the right places, or that there's better fixes possible. If that's the case, I'm happy to adjust this PR as needed :)

### CODE REVIEW

File: lib/ex_unit/lib/ex_unit/cli_formatter.ex [hunk 1]
```diff
@@ -146,13 +146,23 @@ defmodule ExUnit.CLIFormatter do
         {:module_finished, %ExUnit.TestModule{state: {:failed, failures}} = test_module},
         config
       ) do
-    tests_length = length(test_module.tests)
+    # The failed tests have already contributed to the counter,
+    # so we should only add the successful tests to the count
+    successful_tests_length =
+      test_module.tests
+      |> Enum.filter(&is_nil(&1.state))
+      |> length()
```
Comment (josevalim) [inline lib/ex_unit/lib/ex_unit/cli_formatter.ex:154]:
```suggestion
    successful_tests_length = Enum.count(test_module.tests, &is_nil/1)
```

File: lib/ex_unit/lib/ex_unit/cli_formatter.ex [hunk 2]
```diff
@@ -146,13 +146,23 @@ defmodule ExUnit.CLIFormatter do
...
+
+    config = %{
+      config
+      | failure_counter: config.failure_counter + successful_tests_length
+    }
```
Comment (josevalim) [inline lib/ex_unit/lib/ex_unit/cli_formatter.ex:159]:
```suggestion
    config = update_in(config.failure_counter, & &1 + successful_tests_length)
```

You could also merge the two suggestions into one:

    config = update_in(config.failure_counter, fn counter ->
      counter + Enum.count(test_module.tests, &is_nil(&1.state))
    end)

But I am not sure it is an improvement.

**Comment by josevalim** [comment]
Looks great! :heart: Just two minor nitpicks!

File: lib/ex_unit/lib/ex_unit/cli_formatter.ex (hunk 2 above)
Comment (QuinnWilton) [reply lib/ex_unit/lib/ex_unit/cli_formatter.ex]: I prefer this version; fixed!

**Comment by QuinnWilton** [comment]
> Looks great! ❤️ Just two minor nitpicks!

Thank you! I pushed up your requested changes.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
