### PR TITLE
Fix incorrect guard type refinement with length/map_size and != operator

### LINKED ISSUE #15326: Invalid type guard type refinement with != operator
### Elixir and Erlang/OTP versions

Erlang/OTP 28 [erts-16.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.20.0-rc.4 (55a3899) (compiled with Erlang/OTP 28)

### Operating system

any

### Current behavior

Repro:

```
defmodule SizeInequalityRepro do
  def list_case(x) when is_list(x) and length(x) != 1 and x != [] do
    hd(x)
  end

  def map_case(x) when is_map(x) and map_size(x) != 1 and is_map_key(x, :a) and is_map_key(x, :b) do
    :ok
  end

  def tuple_case(x) when is_tuple(x) and tuple_size(x) != 1 and tuple_size(x) != 0 do
    :ok
  end
end

warning: incompatible types given to Kernel.hd/1:

    hd(x)

given types:

    empty_list()

but expected one of:

    non_empty_list(term(), term())

where "x" was given the types:

    # type: empty_list() or non_empty_list(term(), term())
    # from: iex:2
    is_list(x)

    # type: empty_list()
    # from: iex:2
    length(x) != 1

    # type: empty_list()
    # from: iex:2
    x

└─ iex:3: SizeInequalityRepro.list_case/1

warning: this guard will never succeed:

    is_map(x) and map_size(x) != 1 and is_map_key(x, :a) and is_map_key(x, :b)

because it returns type:

    false

where "x" was given the types:

    # type: map()
    # from: iex:6
    is_map(x)

    # type: empty_map()
    # from: iex:6
    map_size(x) != 1

└─ iex:6: SizeInequalityRepro.map_case/1
```

Note `length(x) != 1` is incorrectly refined to `empty_list()` and `map_size(x) != 1` to `empty_map()`. Tuples work correctly

This is a distinct problem from the one in https://github.com/elixir-lang/elixir/issues/15323 and unlike the cases from https://github.com/elixir-lang/elixir/pull/15325 this one results in false positive warnings on valid code

### Expected behavior

The type should be widened to `list` and `open_map` respectively

### PR DESCRIPTION
**Pull request by lukaszsamson**
Previously `empty_list()` and `empty_map` were returned for `length(x) != n` and `map_size(x) != n` when n > 0. Now the types are widened to `list()` and `open_map()`. List/map of size exactly n when n > 0 cannot be expressed in the type system. The problem does not affect tuples as their sizes are encoded in types

Fixes https://github.com/elixir-lang/elixir/issues/15326

### CODE REVIEW

File: lib/elixir/test/elixir/module/types/pattern_test.exs [hunk 1]
```diff
@@ -1159,6 +1159,17 @@ defmodule Module.Types.PatternTest do
 
       assert typecheck!([x], 0 != length(x), x) == dynamic(non_empty_list(term()))
       assert typecheck!([x], not (0 != length(x)), x) == dynamic(empty_list())
+
+      assert typecheck!([x], length(x) != 1, x) == dynamic(list(term()))
+      assert typecheck!([x], length(x) == 1, x) == dynamic(list(term()))
```
Comment (josevalim) [inline lib/elixir/test/elixir/module/types/pattern_test.exs]: This cannot be an empty list, right?

**Comment by gldubc** [comment]
This is a regression: they weren't tested explicitly previously, but things like `length(x) == 1` should rightfully deduce for `x` the type of a non empty list.

These tests should succeed:
```
assert typecheck!([x], length(x) == 1, x) == dynamic(non_empty_list(term()))
assert typecheck!([x], not (length(x) != 1), x) == dynamic(non_empty_list(term()))

assert typecheck!([x], 1 == length(x), x) == dynamic(non_empty_list(term()))

assert typecheck!([x], map_size(x) == 1, x) ==
               dynamic(open_map() |> difference(empty_map()))
assert typecheck!([x], not (map_size(x) != 1), x) ==  dynamic(open_map() |> difference(empty_map()))

assert typecheck!([x], 1 == map_size(x), x) ==  dynamic(open_map() |> difference(empty_map()))
```

**Comment by josevalim** [comment]
Yes, we need a few additional tests and cases!

**Comment by lukaszsamson** [comment]
Tightened refinement to `non_empty_list`/`non_empty_map` for length/map_size(x) == n when n > 0. Added all the test cases suggested by @gldubc

**Review by gldubc — APPROVED** [review]
I think it's good now!

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
