### PR TITLE
Fix dialyzer opaqueness warnings on module attrs in OTP28

### LINKED ISSUE #14750: Opaqueness warning on OTP28
### Elixir and Erlang/OTP versions

1.18.4 and v1.19 branches, OTP28

### Operating system

-

### Current behavior

```elixir
  @base_uri URI.new!("https://example.com")
  def foo_uri do
    @base_uri |> URI.append_path("/foo")
  end
```

```
Function call without opaqueness type mismatch.

Call does not have expected term of type %URI{
  :authority => URI.authority(),
  :fragment => nil | binary(),
  :host => nil | binary(),
  :path => nil | binary(),
  :port => nil | char(),
  :query => nil | binary(),
  :scheme => nil | binary(),
  :userinfo => nil | binary()
} (with opaque subterms) in the 1st position.

URI.append_path(
  %URI{
    :authority => nil,
    :fragment => nil,
    :host => <<103, 111, 111, 103, 108, 101, 46, 99, 97>>,
    :path => nil,
    :port => 443,
    :query => nil,
    :scheme => <<104, 116, 116, 112, 115>>,
    :userinfo => nil
  },
  <<47, 102, 111, 111>>
)
```

### Expected behavior

No warning.

This is exactly like https://github.com/elixir-lang/elixir/issues/14576 all over again, but for module attributes rather than inline calls 😭

We could:
1. mark as generated after escaping (again, reducing the usefulness of the type system :/)
2. remove opaqueness as previously suggested - this should eventually be checked via the new type system anyway?
3. do nothing and require people to locally silent warning in such cases
4. disable dialyzer opaqueness checks as previously mentioned - not sure at which level though?

### PR DESCRIPTION
**Pull request by sabiwara**
Marks module attributes as generated in case they contain opaque terms

Close https://github.com/elixir-lang/elixir/issues/14750

To be backported to 1.19

### CODE REVIEW

**Comment by josevalim** [comment]
I wonder if instead we should do `Macro.escape(..., generated: true)`? I can see this being handy in other occasions. But this PR also works as is!

**Comment by sabiwara** [comment]
> I wonder if instead we should do `Macro.escape(..., generated: true)`? I can see this being handy in other occasions. But this PR also works as is!

I thought about it too, yeah it sounds good!
I was worried about bootstrapping issues but it seems to work just fine. Will push.

**Comment by sabiwara** [comment]
[c351990](https://github.com/elixir-lang/elixir/pull/14755/commits/c3519907b8e0288140a96c793f8542794b5277c9)

File: lib/elixir/lib/macro.ex [hunk 1]
```diff
@@ -808,6 +808,10 @@ defmodule Macro do
       nodes. Note this option changes the semantics of escaped code and
       it should only be used when escaping ASTs. Defaults to `false`.
 
+    * `:generated` - (since v1.19.0) Whether the AST should be considered as generated
+      by the compiler or not. This means the compiler and tools like Dialyzer may not
+      emit certain warnings.
```
Comment (sabiwara) [inline lib/elixir/lib/macro.ex:813]: Basically the same as https://hexdocs.pm/elixir/1.19.0-rc.0/Macro.html#t:metadata/0

File: lib/elixir/lib/macro.ex [hunk 2]
```diff
@@ -908,7 +912,17 @@ defmodule Macro do
...
     unquote = Keyword.get(opts, :unquote, false)
     kind = if Keyword.get(opts, :prune_metadata, false), do: :prune_metadata, else: :none
-    :elixir_quote.escape(expr, kind, unquote)
+    generated = Keyword.get(opts, :generated, false)
+
+    case :elixir_quote.escape(expr, kind, unquote) do
+      # mark module attrs as shallow-generated since the ast for their representation
+      # might contain opaque terms
+      {caller, meta, args} when generated and is_list(meta) ->
+        {caller, [generated: true] ++ meta, args}
```
Comment (sabiwara) [inline lib/elixir/lib/macro.ex:921]: Should we wrap with a `__block__` for other ASTs?
It feels a bit too much, we shouldn't need it for this use case and `quote` doesn't do it either.

Comment (josevalim) [reply lib/elixir/lib/macro.ex:921]: I think there is no need, yeah.

**Review by josevalim — APPROVED** [review]

**Comment by sabiwara** [comment]
Backported ✅

File: lib/elixir/lib/macro.ex [hunk 3]
```diff
@@ -808,6 +808,10 @@ defmodule Macro do
       nodes. Note this option changes the semantics of escaped code and
       it should only be used when escaping ASTs. Defaults to `false`.
 
+    * `:generated` - (since v1.19.0) Whether the AST should be considered as generated
```
Comment (lukaszsamson) [inline lib/elixir/lib/macro.ex:811]: @sabiwara the new options should be included in `escape_opts` type

Comment (sabiwara) [reply lib/elixir/lib/macro.ex:811]: Wooops, thank you for catching this one ! 💜
Will fix

Comment (sabiwara) [reply lib/elixir/lib/macro.ex:811]: Fixed and backported https://github.com/elixir-lang/elixir/pull/14761 ✅

Comment (hez) [reply lib/elixir/lib/macro.ex:811]: Was this backported to Elixir 1.19?  It still appears to be happening on elixir 1.19.5 and otp 28.3.2

Comment (itsGabriel) [reply lib/elixir/lib/macro.ex:811]: @sabiwara  i'm still having the issue at Elixir 1.19.5 with otp 28.4.1. Should I upgrate to recent versions?

Comment (sabiwara) [reply lib/elixir/lib/macro.ex:811]: @itsGabriel @hez this PR has been backported to 1.19.5, but wasn't enough to fix all instances of https://github.com/elixir-lang/elixir/issues/14837 due to the way OTP28 contract checking ignores `generated` annotations.

An example of this is:

```elixir
  @map_set MapSet.new(1..10)
  @spec contract_violation :: MapSet.t()
  def contract_violation, do: @map_set
```

raises a `contract_with_opaque` on 1.19.5 / OTP28:

```
file:line:contract_with_opaque
The @spec for Repro.contract/0 has an opaque
subtype %MapSet{:map => MapSet.internal(_)} which is violated by the success typing.
```

We ended up removing `@opaque` from `MapSet` or `URI` types, but this part was done after 1.19.5 and hasn't been backported.

The 1.20 rc should fix this, but until the stable release, you can suppress it by temporarily adding `@dialyzer {:no_opaque, [fun: arity]}` (or just `@dialyzer :no_opaque`).
