### PR TITLE
ExUnit.Diff: Escape pinned values when computing diff

### LINKED ISSUE #13348: ExUnit: Fails to correctly highlight diffs in tuples with lists in them
### Elixir and Erlang/OTP versions

$ elixir --version
Erlang/OTP 25 [erts-13.2.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.16.1 (compiled with Erlang/OTP 25)

### Operating system

NixOS

### Current behavior

Here is my test file:

```elixir
defmodule HighlightingTest do
  use ExUnit.Case, async: true

  test "correct1" do
    val = {[:foo]}
    assert ^val = {[:bar]}
  end

  test "correct2" do
    val = [:foo]
    assert ^val = [:bar]
  end

  test "correct3" do
    val = {:foo}
    assert ^val = {:bar}
  end

  test "incorrectly colored" do
    val = [{:foo}]
    assert ^val = [{:bar}]
  end
end
```

And here is the colored output I get from running `mix test` on the file:

screenshot

Notice that in the last test the entire `{:bar}` is highlighted in green, instead of just `:bar`, as in the rest of the tests.

### Expected behavior

Only `:bar` is highlighted.

### PR DESCRIPTION
**Pull request by Munksgaard**
Take these two tests:

```elixir
  test "correctly colored" do
    assert [{:foo}] = [{:bar}]
  end

  test "incorrectly colored" do
    val = [{:foo}]
    assert ^val = [{:bar}]
  end
```

When diffing the match without a pin, `diff_value/3` would be passed the quoted version of `[{:foo}]` (`[{:{}, [], [:foo]}]`) as the left argument, allowing it to recurse deeper into the structure to find the correct diff.

When diffing the match with the pin, `diff_value/3` would be passed `[{:foo}]` instead, prohibiting it from recursively refining the diff, leading to overly broad diffs. The fix is to explicitly escape the pin value in the call to `diff_value/3` inside of `diff_pin/3`.

This fixes #13348

### CODE REVIEW

File: lib/ex_unit/lib/ex_unit/diff.ex [hunk 1]
```diff
@@ -286,7 +286,7 @@ defmodule ExUnit.Diff do
   defp diff_pin({:^, _, [var]} = pin, right, %{pins: pins} = env) do
     identifier = var_context(var)
     %{^identifier => pin_value} = pins
-    {diff, post_env} = diff_value(pin_value, right, env)
+    {diff, post_env} = diff_value(Macro.escape(pin_value), right, env)
 
     diff_left = update_diff_meta(pin, not diff.equivalent?)
     {%{diff | left: diff_left}, post_env}
```
Comment (josevalim) [inline lib/ex_unit/lib/ex_unit/diff.ex:292]:
```suggestion
    {diff, post_env} = diff_value(pin_value, right, %{env | context: :===})

    diff_left = update_diff_meta(pin, not diff.equivalent?)
    {%{diff | left: diff_left}, %{post_env | context: :match}}
```

Comment (josevalim) [reply lib/ex_unit/lib/ex_unit/diff.ex:292]: diff_value works on values, so we shouldn't pass Macro.escape (an AST), the correct fix is to tell we should use a different context. :)

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
