### PR TITLE
Fix module inspect on case insensitive filesystems

### LINKED ISSUE #8780: Running `i :Kernel` in IEx seems to crash
### Environment

```
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
```

### Current behavior

```
ex(15)> i :Kernel
Term

10:46:53.462 [error] beam/beam_load.c(1428): Error loading module 'Kernel':
  module name in object code is kernel


  :Kernel

10:46:53.462 [error] Loading of /usr/local/Cellar/erlang/21.2/lib/erlang/lib/kernel-6.2/ebin/Kernel.beam failed: :badfile

Data type
  Atom
Reference modules
  Atom
Implemented protocols
  IEx.Info, Inspect, String.Chars, List.Chars
```

### Expected behavior

The current behavior lets the user think a crash happened somewhere.

I suppose this is not desired, and the normal behavior is expected as for other non-special modules.

Perhaps it is needed to treat some modules as special for the `i` command to behave normally.

### PR DESCRIPTION
**Pull request by hauleth**
Earlier this outputted error messages when loaded module that existed
with different casing, ex.:

    iex> i Datetime

Caused errors to be shown. Now this checks if there is module file
defines module with the same name as the provided atom to prevent such
cases.

Close #8780

### CODE REVIEW

**Comment by hauleth** [comment]
I am not sure how we could test that on case-sensitive systems so there are no tests. If someone have any idea then I am open to it.

**Comment by whatyouhide** [comment]
@hauleth could we write a test for this that would just do nothing on case-sensitive systems so that at least when the test is running on case-insensitive systems we are testing the correct behaviour?

**Comment by hauleth** [comment]
@whatyouhide I can write one like that.

**Comment by josevalim** [comment]
Looks great, just a test and it should be good to go. I don't think the test needs to check for the filesystem because for case sensitive ones we will never show the warning either.

**Comment by hauleth** [comment]
@josevalim done

File: lib/iex/lib/iex/info.ex [hunk 1]
```diff
@@ -43,6 +43,22 @@ defimpl IEx.Info, for: Atom do
     [{"Data type", "Atom"}] ++ description ++ specific_info
   end
 
+  defp module?(atom) do
+    case :code.get_object_code(atom) do
+      :error ->
+        Code.ensure_loaded?(atom)
+
+      {^atom, beam, _path} ->
+        module_name =
```
Comment (fertapric) [inline lib/iex/lib/iex/info.ex]: What do you think about using `Keyword.fetch` to avoid the comment and the default `0` value?

```elixir
beam_info = :beam_lib.info(beam)

case Keyword.fetch(beam_info, :module) do
  {:ok, ^atom} -> true
  _ -> false
end
```

Comment (hauleth) [reply lib/iex/lib/iex/info.ex]: Changed to `match?/2`.

**Comment by josevalim** [comment]
This match is equivalent to == {:ok, atom}.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by hauleth** [comment]
@josevalim right, I have missed that.

File: lib/iex/lib/iex/info.ex [hunk 2]
```diff
@@ -43,6 +43,18 @@ defimpl IEx.Info, for: Atom do
...
 
+  defp module?(atom) do
+    case :code.get_object_code(atom) do
+      :error ->
+        Code.ensure_loaded?(atom)
+
+      {^atom, beam, _path} ->
+        info = :beam_lib.info(beam)
+
+        {:ok, atom} == Keyword.fetch(info, :module)
```
Comment (whatyouhide) [inline lib/iex/lib/iex/info.ex]: Personally, I feel more comfortable with this check being the other way around for some reason. If you also think it's a good change, here's a nice little change that you can just commit otherwise no problem! 😄 

```suggestion
        Keyword.fetch(info, :module) == {:ok, atom}
```

File: lib/iex/lib/iex/info.ex [hunk 3]
```diff
@@ -43,6 +43,18 @@ defimpl IEx.Info, for: Atom do
...
   end
 
+  defp module?(atom) do
+    case :code.get_object_code(atom) do
+      :error ->
+        Code.ensure_loaded?(atom)
+
+      {^atom, beam, _path} ->
+        info = :beam_lib.info(beam)
+
```
Comment (whatyouhide) [inline lib/iex/lib/iex/info.ex]:
```suggestion
```

Comment (hauleth) [reply lib/iex/lib/iex/info.ex]: I personally always separate variables and "main body" of the function, but this is up to you.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
