### PR TITLE
Fix assertion errors with more than 1 pinned var

### LINKED ISSUE #3771: Error message for assertions with more than 1 pinned var are generated incorrectly
In v1.1.0, error messages for assertions with pinned vars are generated using unquote_splicing, which fails when there's more than 1 pinned var:

https://github.com/elixir-lang/elixir/blob/1a9a264b2ebe5b7f332fb101ce5a0efa5056b6ea/lib/ex_unit/lib/ex_unit/assertions.ex#L364

I'm working on a PR to fix this, after confirming it was an issue with @ericmj.

### PR DESCRIPTION
**Pull request by antipax**
Fixes #3771

### CODE REVIEW

File: lib/ex_unit/lib/ex_unit/assertions.ex [hunk 1]
```diff
@@ -359,9 +359,14 @@ defmodule ExUnit.Assertions do
...
     end)
+    |> Enum.reduce(fn(pin, acc) ->
+      quote do
+        unquote(acc) <> unquote(pin)
+      end
+    end)
 
     quote do
-      "\nThe following variables were pinned:" <> unquote_splicing(content)
+      "\nThe following variables were pinned:" <> unquote(content)
```
Comment (lexmag) [inline lib/ex_unit/lib/ex_unit/assertions.ex]: It'd be better to keep `unquote_splicing/1` with:
```elixir
<<"\nThe following variables were pinned:", unquote_splicing(content)>>
```
and no need for extra `Enum.reduce/2` then.

**Comment by lexmag** [comment]
:+1: good catch.

File: lib/ex_unit/test/ex_unit/assertions_test.exs [hunk 2]
```diff
@@ -127,6 +127,22 @@ defmodule ExUnit.AssertionsTest do
...
+    status = :valid
+    send self(), {:status, :invalid, :invalid}
+    try do
+      "This should never be tested" = assert_received {:status, ^status, ^status}
+    rescue
+      error in [ExUnit.AssertionError] ->
+        "No message matching {:status, ^status, ^status} after 0ms.\n" <>
+        "The following variables were pinned:\n" <>
+        "  status = :valid\n" <>
+        "  status = :valid\n" <>
```
Comment (josevalim) [inline lib/ex_unit/test/ex_unit/assertions_test.exs]: We should likely not show status twice. :D Let's call `Enum.uniq` on the names but still leave this test here (showing that dup variables will be showed once).

**Comment by antipax** [comment]
Ok, thanks @lexmag and @josevalim. Feedback applied

**Comment by antipax** [comment]
Wait, do not merge. The uniq call is incorrect (will produce multiple outputs if they are on different lines)

**Comment by antipax** [comment]
Ok, I think we're good now :+1:

File: lib/ex_unit/test/ex_unit/assertions_test.exs [hunk 3]
```diff
@@ -127,6 +127,25 @@ defmodule ExUnit.AssertionsTest do
...
   end
 
+  test "assert received with multiple pinned variables" do
+    status = :valid
+    send self(), {:status, :invalid, :invalid}
+    try do
+      "This should never be tested" = assert_received {
+        :status,
+        ^status,
+        ^status
```
Comment (josevalim) [inline lib/ex_unit/test/ex_unit/assertions_test.exs]: We need the test to show two different variables otherwise this test is not really checking the bug you have originally fixed. :)

Comment (lexmag) [inline lib/ex_unit/test/ex_unit/assertions_test.exs]: Let's make previously added test to check for uniqueness and new one for multiple variables. :bowtie:

Comment (antipax) [inline lib/ex_unit/test/ex_unit/assertions_test.exs]: Haha, that is true. Adding now

File: lib/ex_unit/lib/ex_unit/assertions.ex [hunk 4]
```diff
@@ -353,7 +353,8 @@ defmodule ExUnit.Assertions do
 
   defp pinned_vars([]), do: ""
   defp pinned_vars(pins) do
-    content = Enum.map(pins, fn(var) ->
+    content = Enum.uniq_by(pins, &Macro.to_string/1)
```
Comment (lexmag) [inline lib/ex_unit/lib/ex_unit/assertions.ex]: Maybe just `Enum.uniq_by(pins, &elem(&1, 0))`?

Comment (antipax) [inline lib/ex_unit/lib/ex_unit/assertions.ex]: I had originally had that basically, but I figured this was safer and more explicit. Should I change it still?

Comment (lexmag) [inline lib/ex_unit/lib/ex_unit/assertions.ex]: I think so, `&elem(&1, 0)` clearly says that we are interested only in variable name.

**Comment by antipax** [comment]
Ok, updated.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
