### PR TITLE
Fix invalid module reference in prune_stacktrace

### LINKED ISSUE #15271: Internal elixir_expand module not pruned from stacktrace
### Elixir and Erlang/OTP versions

Erlang/OTP 28 [erts-16.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Interactive Elixir (1.20.0-rc.4)

### Operating system

any

### Current behavior

This code reproduces the bug:
```
defmodule Repro do
  defmacro bad do
    quote do
      receive 1
    end
  end
end
try do
  Code.eval_quoted(
    quote do
      require Repro
      Repro.bad()
    end
  )
rescue
  e ->
    IO.puts(Exception.message(e))
    IO.inspect(__STACKTRACE__)
end
```

Result
```
error: invalid arguments for "receive"
└─ nofile:1

nofile: cannot compile file (errors have been logged)
[
  {:elixir_expand, :expand, 3, [file: ~c"src/elixir_expand.erl", line: 343]},
  {Repro, :bad, 0, [file: ~c"expanding macro"]},
  {:elixir_compiler, :__FILE__, 1, [file: ~c"iex", line: 3]}
]
```

Reason: invalid module atom in https://github.com/elixir-lang/elixir/blob/03b45e521d72cb8a2bec3832961a1c5a7e969321/lib/elixir/src/elixir_dispatch.erl#L352

### Expected behavior

elixir_expand pruned

### PR DESCRIPTION
**Pull request by lukaszsamson**
Fixes #15271

### CODE REVIEW

File: lib/elixir/test/elixir/code_test.exs [hunk 1]
```diff
@@ -215,6 +215,30 @@ defmodule CodeTest do
...
+            quote do
+              require PruneStacktraceMacro
+              PruneStacktraceMacro.bad()
+            end
+          )
+        rescue
+          CompileError -> __STACKTRACE__
+        end
+
+      refute Enum.any?(stacktrace, &match?({:elixir_expand, :expand, 3, _}, &1))
```
Comment (josevalim) [inline lib/elixir/test/elixir/code_test.exs:239]: Let’s check for both elixir_dispatch and elixir_expand, no need to match in the function name.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
