### PR TITLE
Provide tab-completion for aliases

### LINKED ISSUE #2519: Tab completion does not work for aliases
```elixir
defmodule A.B.C do
  def a do end

  def b(x) do x end

  def c(y) do -y end
end
```

```iex
iex(1)> A.B.C.<tab>
a/0    b/1    c/1

iex(2)> alias A.B.C
nil
iex(3)> C.<tab>
# nothing

iex(4)> alias A.B.C, as: Other
nil
iex(5)> Other.<tab>
# nothing
```

### PR DESCRIPTION
**Pull request by lexmag**
Closes #2519.

It is based on `IEx.Server.whereis/0` usage, as there is no other way to reach current `%IEx.State{}`.
Probably we can use separate agent to track state, not sure if it worth it though; the current implementation might be OK for a first iteration.
I'd like to have any feedback or suggestions ot it. Just for reference: https://github.com/elixir-lang/elixir/issues/2519#issuecomment-48834111.

This also makes possible to add tab-completion for user imports.

### CODE REVIEW

File: lib/iex/lib/iex/autocomplete.ex [hunk 1]
```diff
@@ -167,12 +175,15 @@ defmodule IEx.Autocomplete do
...
-
-    if :code.get_mode() === :interactive do
-      modules ++ get_modules_from_applications()
-    else
-      modules
+    fun = fn {mod, _} -> Atom.to_string(mod) end
+    aliases = Enum.map(env_aliases(), fun)
+    modules =
+      Enum.map(:code.all_loaded(), fun)
+      |> Enum.into(aliases)
```
Comment (josevalim) [inline lib/iex/lib/iex/autocomplete.ex]: isn't it clearer to make it `aliases ++ Enum.map(...)`?

File: lib/iex/lib/iex/autocomplete.ex [hunk 2]
```diff
@@ -136,8 +136,16 @@ defmodule IEx.Autocomplete do
...
     mod = Module.concat(list)
-    format_expansion match_elixir_modules(mod, hint, list == []) ++
-                     match_module_funs(mod, hint), hint
+    match_elixir_modules(mod, hint, list == [])
+    |> Kernel.++(match_module_funs(mod, hint))
+    |> format_expansion(hint)
+  end
+
+  defp env_aliases() do
+    send(IEx.Server.whereis(), {:peek, self()})
```
Comment (josevalim) [inline lib/iex/lib/iex/autocomplete.ex]: I would rather make it message that asks just for the env to avoid copying the whole state.

File: lib/iex/lib/iex/autocomplete.ex [hunk 3]
```diff
@@ -136,8 +136,16 @@ defmodule IEx.Autocomplete do
...
+    receive do
+      {:peek, %IEx.State{env: env}} -> env.aliases
```
Comment (josevalim) [inline lib/iex/lib/iex/autocomplete.ex]: I am worried about going into a situation where the server can't really reply but I can't think of any way it would happen. It would be nice to have a 5 seconds timeout just in case.

**Comment by josevalim** [comment]
Thank you! I have added some comments!

**Comment by lexmag** [comment]
Thanks for your comments.
It turned out that proposed implementation not includes one case:
```
iex(1)> alias IEx, as: I
nil
iex(2)> IEx.
App                Autocomplete       CLI                Config             
Evaluator          Helpers            History            Introspection      
Remsh              Server             State              after_spawn/0      
after_spawn/1      color/2            configuration/0    configure/1        
inspect_opts/0     pry/1              pry/3              started?/0         
width/0            
iex(2)> I.  
after_spawn/0      after_spawn/1      color/2            configuration/0    
configure/1        inspect_opts/0     pry/1              pry/3              
started?/0 
```
note the lack of modules for `I.` return. Will rework PR to support it.

**Comment by lexmag** [comment]
@josevalim this is ready for merge. Don't see a way to make tests for it (we can start IEx with predefined `%Env{}` but `capture_io` swaps `group_leader` thus `IEx.Server` is getting unreachable).
Here is a showcase:
```
iex(1)> alias IEx, as: I
nil
iex(2)> I
I          IEx        IO         Inspect    Integer    
iex(2)> I.
App                Autocomplete       CLI                Config             
Evaluator          Helpers            History            Introspection      
Remsh              Server             State              after_spawn/0      
after_spawn/1      color/2            configuration/0    configure/1        
inspect_opts/0     pry/1              pry/3              started?/0         
width/0            
iex(2)> I.App.start
start/2
```

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
