### PR TITLE
Fix bug when formatting :"\\"

### LINKED ISSUE #11698: Formatting bug for the atom :"\\"
### Environment

* Elixir & Erlang/OTP versions (elixir --version): `Elixir 1.13.3 (compiled with Erlang/OTP 24)`
* Operating system: MacOS Monterey

### Current behavior
When saving `:"\\"`, the formatter transforms it as `:\\`, which is a different atom (technically `:"\\\\"`).

```elixir
iex> :"\\" |> inspect() |> Code.format_string!() |> IO.puts()
:\\
:ok
iex> :"\\" == :\\
false
```

### Expected behavior

The formatter should only replace by something equivalent if possible.

```elixir
iex> :"\\" |> inspect() |> Code.format_string!() |> IO.puts()
:"\\"
:ok
```

Note: I have a working fix, will open a PR.

### PR DESCRIPTION
**Pull request by sabiwara**
Formatting `:"\\"` preserves the quotes and doesn't transform it as `:\\`, which is a different atom.

Closes #11698

### CODE REVIEW

File: lib/elixir/lib/code/formatter.ex [hunk 1]
```diff
@@ -1487,16 +1487,29 @@ defmodule Code.Formatter do
...
-  defp atom_to_algebra(atom) do
+  defp atom_to_algebra(:\\, meta) do
+    string =
+      case Keyword.get(meta, :delimiter) do
+        "\"" ->
+          ":\"\\\\\""
+
+        _ ->
+          ":\\\\"
+      end
```
Comment (josevalim) [inline lib/elixir/lib/code/formatter.ex:1507]:
```suggestion
  defp atom_to_algebra(:\\, meta) do
    string =
      # Since we parse strings without unescaping, the atoms
      # :\\ and :"\\" have the same representation, so we need
      # to check the delimiter and handle them accordingly.
      case Keyword.get(meta, :delimiter) do
        "\"" -> ":\"\\\\\""
        _ -> ":\\\\"
      end
```

File: lib/elixir/lib/code/formatter.ex [hunk 2]
```diff
@@ -1487,16 +1487,29 @@ defmodule Code.Formatter do
...
+  defp atom_to_algebra(:"..//", _) do
     string(":\"..//\"")
   end
 
-  defp atom_to_algebra(atom) do
+  defp atom_to_algebra(:\\, meta) do
+    string =
+      # Since we parse strings without unescaping, the atoms
+      # :\\ and :"\\" have the same representation, so we need
+      # to check the delimiter and handle them accordingly.
```
Comment (josevalim) [inline lib/elixir/lib/code/formatter.ex:1503]:
```suggestion
    # Since we parse strings without unescaping, the atoms
    # :\\ and :"\\" have the same representation, so we need
    # to check the delimiter and handle them accordingly.
    string =
```

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
