### PR TITLE
Fix ExUnit stacktrace formatting when its entry has no location

### LINKED ISSUE #4570: Getting weird stacktrace (`:`) via `assert a.nil == :b` when `a()` returns `nil`
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.2.1
```

* Operating system:

OS X El Capitan

### Current behavior

``` elixir
defmodule NilTest do
  use ExUnit.Case, async: true

  test "`function_returning_nil.foo`" do
    assert function_returning_nil.foo == :bar
  end

  test "`nil.foo`" do
    assert nil.foo == :bar
  end

  defp function_returning_nil do
    nil
  end
end
```

Running these tests produces:

```
NilTest
  * `function_returning_nil.foo` (21.4ms)

  1) test `function_returning_nil.foo` (NilTest)
     test/unit/nil_test.exs:4
     ** (UndefinedFunctionError) undefined function nil.foo/0
     stacktrace:
       nil.foo()
       :

  * `nil.foo` (13.8ms)

  2) test `nil.foo` (NilTest)
     test/unit/nil_test.exs:8
     ** (UndefinedFunctionError) undefined function nil.foo/0
     stacktrace:
       nil.foo()
       test/unit/nil_test.exs:9
```

### Expected behavior

For the stacktrace for the `function_returning_nil.foo` failure I'd expect it to print `test/unit/nil_test.exs:5` instead of `:`.

On a completely unrelated note: I'm surprised these tests are taking 21.4ms and 13.8ms.  They are not really doing anything.  I'm used to seeing test runtimes like `0.03ms` for such simple tests...but these are taking a couple orders-of-magnitude longer for some reason.  I'm not opening this issue to report that, but if someone knows why it's taking so much longer and can explain it to me, I'd be very curious to hear :).

### PR DESCRIPTION
**Pull request by lexmag**
Closes #4570.

### CODE REVIEW

File: lib/ex_unit/lib/ex_unit/formatter.ex [hunk 1]
```diff
@@ -236,16 +236,17 @@ defmodule ExUnit.Formatter do
...
-      Enum.map_join(stacktrace,
-        fn(s) -> stacktrace_info format_stacktrace_entry(s, test_case, test), color end)
+      Enum.map_join(stacktrace, fn entry ->
+        stacktrace_info format_stacktrace_entry(entry, test_case, test), color
+      end)
   end
 
   defp format_stacktrace_entry({test_case, test, _, location}, test_case, test) do
-    "#{location[:file]}:#{location[:line]}"
+    format_file_line(location[:file], location[:line], " (file)")
```
Comment (josevalim) [inline lib/ex_unit/lib/ex_unit/formatter.ex]: I don't understand why we need to pass " (file)". Shouldn't it be solved in the Exception formatter itself?

Comment (lexmag) [inline lib/ex_unit/lib/ex_unit/formatter.ex]: It was needed because of the `suffix`ing inside `Exception.format_file_line/3`, I have changed it to allow `nil` suffixes.

File: lib/elixir/lib/exception.ex [hunk 2]
```diff
@@ -464,17 +464,15 @@ defmodule Exception do
       ""
 
   """
-  def format_file_line(file, line) do
-    format_file_line(file, line, "")
-  end
-
-  defp format_file_line(file, line, suffix) do
+  def format_file_line(file, line, suffix \\ "") do
```
Comment (josevalim) [inline lib/elixir/lib/exception.ex]: I don't like the implicit nil behaviour but I don't have any other suggestion. :(

Comment (lexmag) [inline lib/elixir/lib/exception.ex]: As alternative option we can either copy part of `format_file_line` to `ExUnit.Formatter` or have `(test)` suffix, e.g. `test/my_app/nil_test.exs:3: (test)`. ¯\\_(ツ)_/¯

Comment (josevalim) [inline lib/elixir/lib/exception.ex]: I like "(test)" suffix. This way we don't need to support `nil` here. Let's roll with that. :D
