### PR TITLE
 change DynamicSupervisor doc to avoid confusions

### LINKED ISSUE #13675: DynamicSupervisor: the option "max_restarts" only work if provided as initial argument
### Elixir and Erlang/OTP versions

elixir 15.4
otp 26

### Operating system

linux

### Current behavior

When specifying the "max_restarts" option as a regular  when using `DynamicSupervisor`, it doesn't work.

## How to check?

Have this two modules:

```elixir
defmodule Test2 do             
  use GenServer                                                                                                                         
                                                                                                                                                    
  def start_link(_opts \\ []) do                                                                                                    
    GenServer.start_link(__MODULE__, [])                                                                                            
  end                                                                                                                               
                                                                                                                                    
  def init(_opts \\ []) do     
    Process.send_after(self(), :boom, 2000)    
    {:ok, :ok}                                                                                           
  end                          
                                                                                                                                                                               
  def handle_info(:boom, _), do: raise "Boom!"    
end  
```

and

```elixir
defmodule Pipo do              
  def start(options_mr, args_mr) do                                                                                                     
    do_start(options_mr, args_mr)                                                                                                                   
  end                                                                                                                               
                                                                                                                                    
  @impl true                                                                                                                        
  def init(args_mr) do                                                                                                              
    DynamicSupervisor.init(max_restarts: args_mr, strategy: :one_for_one, max_seconds: 10)    
  end                                          
                                                                                                         
  def add_children do          
    DynamicSupervisor.start_child(__MODULE__, Test2)                                                                                                                           
  end                                             
                                                                                                         
  defp do_start(options_mr, args_mr) do    
    DynamicSupervisor.start_link(__MODULE__, args_mr, name: __MODULE__, max_restarts: options_mr)    
  end    
end    
```

an then on a shell, do:
```elixir
iex> Pipo.start(100,3)
iex> Pipo.add_children
```
and you'll see how it explodes only three times (because after 3 restarts, the dynamicsupervisor dies), in spite of you specifying "100" restarts in the options

however, if you do:
```elixir
iex> Pipo.start(3, 100)
iex> Pipo.add_children
```
you'll see it restarts the children more than three times.

### Expected behavior

Based on documentation, I expect that providing `max_restarts` as regular option:

```elixir
DynamicSupervisor.start_link(__MODULE__, _init_args, max_restarts: 100)
```
would work

But only work if provided as initial option:
```elixir
DynamicSupervisor.init(max_restarts: 100)
```

### PR DESCRIPTION
**Pull request by JoeZ99**
Clearly distinguishes between an init option provided as initial argument to DynamicSupervisor, and a regular "GenServer type" option provided as third argument in `start_link/3`

fix #13675

### CODE REVIEW

File: lib/elixir/lib/dynamic_supervisor.ex [hunk 1]
```diff
@@ -381,9 +380,13 @@ defmodule DynamicSupervisor do
   Note that a supervisor started with this function is linked to the parent
   process and exits not only on crashes but also if the parent process exits
   with `:normal` reason.
+
+  ## Opts
+
+  Any regular [GenServer options](`t:GenServer.option/0`). Attention: _Not to confuse with `t:init_option/0`_
```
Comment (josevalim) [inline lib/elixir/lib/dynamic_supervisor.ex:386]:
```suggestion
  ## Options

  This function accepts any regular [GenServer options](`t:GenServer.option/0`).
  Options specific to `DynamicSupervisor` must be returned from the `c:init/1`
  callback.
```

**Review by josevalim — APPROVED** [review]

File: lib/elixir/lib/dynamic_supervisor.ex [hunk 2]
```diff
@@ -381,9 +380,15 @@ defmodule DynamicSupervisor do
...
+
+  ## Options
+
+  This function accepts any regular [`GenServer` options](`t:GenServer.option/0`).
+  Options specific to `DynamicSupervisor` must be returned from the `c:init/1`
+  callback.
   """
   @doc since: "1.6.0"
-  @spec start_link(module, term, [option]) :: Supervisor.on_start()
+  @spec start_link(module, term, [GenServer.option]) :: Supervisor.on_start()
```
Comment (josevalim) [inline lib/elixir/lib/dynamic_supervisor.ex:391]:
```suggestion
  @spec start_link(module, term, [GenServer.option()]) :: Supervisor.on_start()
```

**Comment by JoeZ99** [comment]
@josevalim , I removed the suggested change of writing `@spec xxx(GenServer.option())` instead of `@spec xxx(GenServer.option)`, because I suspect that's what's making format fails ...

File: lib/elixir/lib/dynamic_supervisor.ex (hunk 2 above)
Comment (josevalim) [inline lib/elixir/lib/dynamic_supervisor.ex:391]:
```suggestion
  @spec start_link(module, term, [GenServer.option()]) :: Supervisor.on_start()
```

File: lib/elixir/lib/dynamic_supervisor.ex [hunk 3]
```diff
@@ -345,9 +342,11 @@ defmodule DynamicSupervisor do
       specified in the child spec given to `start_child/2`. Defaults to
       an empty list.
 
+    * Any of the standard [GenServer options](`t:GenServer.option/0`)
+
   """
   @doc since: "1.6.0"
-  @spec start_link([option | init_option]) :: Supervisor.on_start()
+  @spec start_link([init_option | GenServer.option]) :: Supervisor.on_start()
```
Comment (josevalim) [inline lib/elixir/lib/dynamic_supervisor.ex:349]:
```suggestion
  @spec start_link([init_option | GenServer.option()]) :: Supervisor.on_start()
```

**Comment by josevalim** [comment]
Parenthesis are required on both, that should fix it. CI should show the difference too!

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

File: lib/elixir/lib/dynamic_supervisor.ex [hunk 4]
```diff
@@ -215,10 +215,7 @@ defmodule DynamicSupervisor do
           extra_arguments: [term()]
         }
 
-  @typedoc "Options given to `start_link` functions"
-  @type option :: GenServer.option()
```
Comment (michallepicki) [inline lib/elixir/lib/dynamic_supervisor.ex:219]: This now-removed type was being used at https://github.com/elixir-lang/elixir/blob/main/lib/elixir/lib/task/supervisor.ex#L77C1-L77C37 which now needs to be updated

Comment (JoeZ99) [reply lib/elixir/lib/dynamic_supervisor.ex:219]: done and thanks:
https://github.com/elixir-lang/elixir/pull/13704
