### PR TITLE
Do not consider remote typespecs as a compile-time dependency

### LINKED ISSUE #5087: Using a type defined in another module implies in compile-time dependency
### Environment

* Elixir version (elixir -v): 1.3.2 & 1.2.6
* Operating system: debian8 (jessie)

### Current behavior

While debugging recompilation issues in my project I noticed that whenever we
add a reference to a type defined in another module in a typespec, the other
module is added as compile-time dependency.

For example, if we have something like this:

```elixir
## type_a.ex
defmodule TypeA do
  @type t :: integer
end

## type_c.ex
defmodule TypeC do
  @type t :: integer
end

## type_b.ex
defmodule TypeB do
  @spec a() :: TypeA.t
  def a, do: ()

  @spec c() :: TypeC.t
  def c, do: ()
end
```

I will end up with the following dependency graph:

screenshot from 2016-08-03 13 55 08

This contributes to unnecessary re-compilation. Because of this, some "cycles"
appeared in my project and changing a particular file implied in the
recompilation of 200+ others. I ended up commenting all type declarations and
specs to workaround the issue.

I have been able to reproduce this behavior in both v1.3.2 and v1.2.6.

(I have created a [repository](https://github.com/rranelli/comptest) to
exemplify the problem.)

### Expected behavior

I have talked with @josevalim over IRC about this and it seems to him that this
behavior is a bug.

### PR DESCRIPTION
**Pull request by antipax**
Fixes #5087.

Also adds some comments to the cases in which a compile time dependency must be added for a typespec (structs, records). Perhaps the documentation should be altered to suggest using a remote type instead of a struct or record macro to avoid this case, if possible.

Also, I am pushing a commit with the added test first, to show that it fails on the current master. I will then immediately push the commit with the actual fix.

### CODE REVIEW

**Comment by antipax** [comment]
Ok, even though the test failed as expected, it wasn't the failure I was expecting. If preferred, let me do some more investigation as to why it fails locally on current master but not in CI before merging. I have manually verified the fix with #5087's test repository however, so at the least the issue is no longer present if we feel good about merging as is.

**Comment by antipax** [comment]
Ok, tried to be all fancy and leave a paper trail, but it turns out that the PR is checked out in CI by the PR #, so by the time the builds *actually* started, I had already pushed the second commit. I have verified locally that the test fails on current master, so this PR actually fixes an existing issue. I think it's ready to :shipit:

File: lib/elixir/lib/kernel/typespec.ex [hunk 1]
```diff
@@ -883,7 +887,9 @@ defmodule Kernel.Typespec do
 
   # Handle remote calls
   defp typespec({{:., meta, [remote, name]}, _, args} = orig, vars, caller) do
-    remote = Macro.expand remote, caller
+    # We set a function name to avoid tracking
+    # aliases in typespecs as compile time dependencies.
+    remote = Macro.expand remote, %{caller | function: {:typespec, 0}}
```
Comment (josevalim) [inline lib/elixir/lib/kernel/typespec.ex]: I thought the fix would be something exactly like that. :D

Should we do `__info__` or `__typespec__` as the function name though? Another option is to disable the lexical tracker since it is a field in the environment and that would disable the tracking.

Comment (antipax) [inline lib/elixir/lib/kernel/typespec.ex]: There is some existing code that uses this approach here:
https://github.com/antipax/elixir/blob/99a911aee81ce634f0725e274b2ea7ed131799b1/lib/elixir/lib/kernel/typespec.ex#L853

I think it's still a good idea to track the reference as runtime, so personally I'd be against disabling the lexical tracker, unless we want to consider types as existing outside of normal code. I don't think we need to change the env function name since for tracking purposes it's only used in terms of presence vs. nil to determine whether it's compile or runtime.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
