### PR TITLE
Invert the order of non matching token messages (closes #2993)

### LINKED ISSUE #2993: Invert the order of non matching token messages
** (SyntaxError) test/plug/static_test.exs:68: "do" starting at line 64 is missing terminator "end". Unexpected token: )

Should read as:

    ** (SyntaxError) test/plug/static_test.exs:68: unexpected token: ")". "do" starting at line 64 was expecting terminator "end"

### PR DESCRIPTION
**Pull request by xavier**
Added a new way to return errors from the tokenizer by providing a prefix and suffix message to improve the flexibility of message formatting.

### CODE REVIEW

File: lib/elixir/src/elixir_tokenizer.erl [hunk 1]
```diff
@@ -919,9 +919,10 @@ check_terminator({E, _}, [{S, _}|Terminators]) when
 check_terminator({E, {Line, _, _}}, [{Start, {StartLine, _, _}}|_]) when
     E == 'end'; E == ')'; E == ']'; E == '}'; E == '>>' ->
   End = terminator(Start),
-  Message = io_lib:format("\"~ts\" starting at line ~B is missing terminator \"~ts\". "
-                          "Unexpected token: ", [Start, StartLine, End]),
-  {error, {Line, Message, atom_to_list(E)}};
+  MessagePrefix = "Unexpected token: \"",
```
Comment (josevalim) [inline lib/elixir/src/elixir_tokenizer.erl]: Perfect! Just one very tiny nitpick (sorry), our error messages start with lowercase, so this would need to be "unexpected token: \"". Can you please amend and i will merge it straight-away! Thank you so much!

Comment (xavier) [inline lib/elixir/src/elixir_tokenizer.erl]: Fixed!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
