### PR TITLE
Fix Calendar.strftime/2 format negative year incorrectly

### LINKED ISSUE #12266: Calendar.strftime/2 strange behaviour when year is negative integer
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.14.1 (compiled with Erlang/OTP 25)

### Operating system

macOS 12.5 (Monterey)

### Current behavior

In the [Calendar.strftime](https://github.com/elixir-lang/elixir/blob/947717755f3c9c59d326599db1bcbc556767402c/lib/elixir/lib/calendar.ex#L472) said that year will format as `-0001` when `year` in `Date` is negative value. But it's not in version 1.14.1:

```elixir
iex(3)> Date.new!(-1, 11, 30) |> Calendar.strftime("%Y%m%d")
"00-11130"
iex(4)> Date.new!(-11, 11, 30) |> Calendar.strftime("%Y%m%d")
"0-111130"
iex(5)> Date.new!(-111, 11, 30) |> Calendar.strftime("%Y%m%d")
"-1111130"
iex(6)> Date.new!(-1111, 11, 30) |> Calendar.strftime("%Y%m%d")
```

### Expected behavior

I expected that `-` sign should appear first and year with zero padding. For example:

```
-0001
-0011
-0111
-1111
```

### PR DESCRIPTION
**Pull request by wingyplus**
Closes #12266

### CODE REVIEW

File: lib/elixir/lib/calendar.ex [hunk 1]
```diff
@@ -793,7 +793,14 @@ defmodule Calendar do
 
   # Year
   defp format_modifiers("Y" <> rest, width, pad, datetime, format_options, acc) do
-    result = datetime.year |> Integer.to_string() |> pad_leading(width, pad)
+    {sign, year} =
+      if datetime.year < 0 do
+        {"-", datetime.year * -1}
+      else
+        {"", datetime.year}
```
Comment (josevalim) [inline lib/elixir/lib/calendar.ex:800]:
```suggestion
        {?-, -datetime.year}
      else
        {[], datetime.year}
```

Comment (josevalim) [reply lib/elixir/lib/calendar.ex]: This is a micro optimization but those data structures use less memory (micro because it won't matter here at all :D but I thought I would comment).

Comment (wingyplus) [reply lib/elixir/lib/calendar.ex]: Add suggestion. 🙇

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
