### PR TITLE
Escape meta within existing quote extensions

### LINKED ISSUE #14829: Macro.escape/2 doesn't honor :unquote option inside maps on 1.19rc
### Elixir and Erlang/OTP versions

Erlang/OTP 28 [erts-16.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.19.0-rc.2 (957f84b) (compiled with Erlang/OTP 28)

### Operating system

MacOS

### Current behavior

```elixir
iex> Macro.escape(%{field: {:unquote, [], [:test]}}, unquote: true)
{:%{}, [], [field: {:{}, [], [:unquote, [], [:test]]}]}
```

### Expected behavior

Like in 1.18:

```elixir
iex> Macro.escape(%{field: {:unquote, [], [:test]}}, unquote: true)
{:%{}, [], [field: :test]}
```

Originally reported here: https://elixirforum.com/t/macro-escape-2-unquote-option-behaviour-in-elixir-1-19/72859

Regression introduced by https://github.com/elixir-lang/elixir/pull/14773

### PR DESCRIPTION
**Pull request by josevalim**
Closes #14829
Closes #14830

Effectively reverts 7be008c1b0198708b7e150ce77d620c1e647a50b with another fix. :)

### CODE REVIEW

File: lib/elixir/src/elixir_quote.erl [hunk 1]
```diff
@@ -245,28 +241,6 @@ do_escape(Fun, _) when is_function(Fun) ->
 do_escape(Other, _) ->
   bad_escape(Other).
 
-escape_map_key_value(K, V, Map, Q) ->
-  MaybeRef = if
-    is_reference(V) -> V;
-    is_tuple(V) -> find_tuple_ref(V, 1);
```
Comment (josevalim) [inline lib/elixir/src/elixir_quote.erl:251]: I removed this for now, since we added it exclusively for regexes. We can perhaps add it back but given it could also be inside lists and other places, not sure if it makes sense to special case it.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
