### PR TITLE
Remove `child_spec/1` from `StringIO` docs

### LINKED ISSUE #11619: StringIO fails to start under supervisor
### Environment

* Elixir & Erlang/OTP versions (elixir --version):  Elixir 1.13.2, OTP 24
* Operating system: PopOS 21.10

### Current behavior

The documentation for `StringIO` mentions a `child_spec/1` function which makes me think I should be able to start the `StringIO` under a supervisor (or with `start_supervised/1`. Unfortunately when I try to have the supervisor start it, the following exception is raised.

```
     ** (RuntimeError) failed to start child with the spec StringIO.
     Reason: an exception was raised:
         ** (UndefinedFunctionError) function StringIO.start_link/1 is undefined or private
             (elixir 1.13.2) StringIO.start_link([])
             (stdlib 3.17) supervisor.erl:414: :supervisor.do_start_child_i/3
             (stdlib 3.17) supervisor.erl:400: :supervisor.do_start_child/2
             (stdlib 3.17) supervisor.erl:706: :supervisor.handle_start_child/2
             (stdlib 3.17) supervisor.erl:455: :supervisor.handle_call/3
             (stdlib 3.17) gen_server.erl:721: :gen_server.try_handle_call/4
             (stdlib 3.17) gen_server.erl:750: :gen_server.handle_msg/6
             (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

### Expected behavior

I'd expect to either be able to start a `StringIO` via a supervisor (where `child_spec` calls `open/3`) or the `child_spec` function shouldn't exist in the documentation.

### PR DESCRIPTION
**Pull request by aaronrenner**
This fixes #11619 by removing `child_spec/1` from the `StringIO` docs.

### CODE REVIEW

**Comment by josevalim** [comment]
I am thinking instead of replacing `use GenServer` by `@behaviour GenServer`. WDYT?

**Comment by whatyouhide** [comment]
Agreed with @josevalim as long as we leave a comment above `@behaviour GenServer` explaining _why_ we're using that instead of `use GenServer` 😉

**Comment by aaronrenner** [comment]
That's a great idea. I didn't even realize we could do that.

I left a comment about why we're implementing the behavior instead of using the `__using__` macro and didn't implement any additional callback functions. From erlang :gen_server docs, it appears that everything will still work if the optional callbacks aren't defined.

If there's any other changes I need to make or if you'd like me to reword the comment, please let me know!

File: lib/elixir/lib/string_io.ex [hunk 1]
```diff
@@ -13,7 +13,12 @@ defmodule StringIO do
 
   """
 
-  use GenServer
+  # We're implementing the GenServer behaviour instead of using the
+  # `use GenServer` macro, because we don't want the `child_spec/1` function
+  # that `use GenServer` generates. Although this module is implemented as a
+  # GenServer, it doesn't make sense to be started under a supervisor so a
+  # `child_spec/1` function isn't needed.
```
Comment (josevalim) [inline lib/elixir/lib/string_io.ex:20]:
```suggestion
  # We're implementing the GenServer behaviour instead of using the
  # `use GenServer` macro, because we don't want the `child_spec/1`
  # function as it doesn't make sense to be started under a supervisor.
```

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
