### PR TITLE
Always adding :debug_info on erlc_options

### LINKED ISSUE #9184: erlc_options should behave more like elixirc_options
## Environment

- Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.8.2 (compiled with Erlang/OTP 22)
```
- Operating system: macOS Mojave

## Current behavior

There difference in behaviour of `:elixirc_options` and `:elrc_options`. This is the inclusion of `:debug_info`. In `:elixirc_options` it is added always (or at least seems so when running Dialyzer) while in `:erlc_options` it need to be explicitly stated, otherwise Dialyzer will fail with information that it cannot find Erlang Core informations.

Example repo: https://github.com/hauleth/example_error

Way to reproduce error:

```
mix do compile --force, dialyzer
```

Way to resolve error:

```
env DEBUG_INFO=1 mix do compile --force, dialyzer
```

## Expected behavior

Mix should always add `:debug_info` option or should provide different way to ensure, that this is handled properly. Otherwise it has limited capabilities as the Erlang projects build tool.

### PR DESCRIPTION
**Pull request by kelvinst**
That way, if someone sets erlc_options to `[warnings_as_errors: true]`, `:debug_info` would still be on the options. To configure it to not save debug info, one should only add `debug_info: false` to erlc_options

Closes #9184

### CODE REVIEW

**Comment by kelvinst** [comment]
I also fixed a doc that was pointing to the wrong default value for `:debug_info` option on `Code.put_compiler_option`

**Comment by kelvinst** [comment]
I'm checking how to add tests for this now.

Also, there should be a changelog notice or something like that, since the change breaks compatibility. e.g. if anyone was just dismissing `:debug_info` on `:erlc_options` to disable it, that would not work anymore, they would have to change their options to `debug_info: false`

**Comment by kelvinst** [comment]
> I'm checking how to add tests for this now.

So as it is done now, I'm not sure there is any good way of testing it, since it is an inner logic inside `Mix.Tasks.Compile.Erlang.do_run`. Should I extract the erlc_options build to a public function and unit test it? Maybe we can extract it to `Mix.Compilers.Erlang.erlc_options` and even document it better there. WDYT?

**Comment by josevalim** [comment]
You should be able to test it like this: https://github.com/elixir-lang/elixir/blob/master/lib/mix/test/mix/tasks/compile.erlang_test.exs#L14

**Comment by kelvinst** [comment]
Yeah, I saw that, but what I couldn't figure out yet is how to check if the `:debug_info` option was actually applied to compilation.

**Comment by michalmuskala** [comment]
@kelvinst it should be possible to check the generated files with `:beam_lib(path, [:debug_info])`

**Comment by kelvinst** [comment]
Cool! Thanks @michalmuskala! Really helpful tip (I suppose you mean `:beam_lib.chunks`, right?)

**Comment by kelvinst** [comment]
PS.: I just realized that I added the default options to the wrong place I guess, that way it will apply it only for the `mix compile.erlang` task, not when using `mix compile`. Will fix later.

**Comment by kelvinst** [comment]
Actually, nevermind, just realized `mix compile` does call `mix compile.erlang` 🤦‍♂ I'm investigating why @hauleth's example app still don't work with my solution.

**Comment by kelvinst** [comment]
Right, so the problem was that I was just running `../elixir/bin/mix do compile, dialyzer` from inside @hauleth's project,  and that was not using `../elixir/bin/mix` to run the subtasks I suppose. Did test setting `PATH=../elixir/bin:$PATH mix do compile, dialyzer` and it did work that way, so that really worked.

File: lib/mix/test/mix/tasks/compile.erlang_test.exs [hunk 1]
```diff
@@ -174,4 +174,18 @@ defmodule Mix.Tasks.Compile.ErlangTest do
...
+  test "adds :debug_info to erlc_options by default" do
+    in_fixture("compile_erlang", fn ->
+      Mix.Tasks.Compile.Erlang.run([])
+
+      binary = File.read!("_build/dev/lib/sample/ebin/b.beam")
+
+      {:ok, {module, [debug_info: {:debug_info_v1, backend, data}]}} =
+        :beam_lib.chunks(binary, [:debug_info])
+
+      assert backend.debug_info(:elixir_v1, module, data, []) != {:error, :missing}
```
Comment (michalmuskala) [inline lib/mix/test/mix/tasks/compile.erlang_test.exs]: I think this should assert with `:erlang_v1` - after all it's compiling erlang modules, so it's kind of expected it won't be able to return elixir debug info.
```suggestion
      assert backend.debug_info(:erlang_v1, module, data, []) != {:error, :missing}
```

Comment (kelvinst) [reply lib/mix/test/mix/tasks/compile.erlang_test.exs]: Alrighty!

Comment (josevalim) [reply lib/mix/test/mix/tasks/compile.erlang_test.exs]: I wouldn't even assert this. Asserting it returns a debug info chunk is probably good enough!

Comment (kelvinst) [reply lib/mix/test/mix/tasks/compile.erlang_test.exs]: You mean something like this?

```elixir 
{:ok, {_, [debug_info: {:debug_info_v1, _, {info, _}}]}} = :beam_lib.chunks(binary, [:debug_info])
assert info != :none
```

Comment (kelvinst) [reply lib/mix/test/mix/tasks/compile.erlang_test.exs]: I've checked and the only difference is that it returns `:none` for that part when debug info is disabled, instead of the list of attributes.

Comment (kelvinst) [reply lib/mix/test/mix/tasks/compile.erlang_test.exs]: I have started with that actually, just changed to use `backend.debug_info` because I was afraid that maybe the format could change in the future and then the test could fail. Very unlikely, but who knows 🤷‍♂

**Comment by josevalim** [comment]
The point is that if they change the format, this test should not fail. It
is ok for them to do that. As long as there is something, we are good.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

File: lib/mix/lib/mix/project.ex [hunk 2]
```diff
@@ -729,7 +729,7 @@ defmodule Mix.Project do
       elixirc_paths: ["lib"],
       erlc_paths: ["src"],
       erlc_include_path: "include",
-      erlc_options: [:debug_info],
+      erlc_options: [],
```
Comment (kelvinst) [inline lib/mix/lib/mix/project.ex]: This can be empty since we already add it everytime when compiling erlang.

File: lib/mix/lib/mix/tasks/compile.erlang.ex [hunk 3]
```diff
@@ -41,14 +41,19 @@ defmodule Mix.Tasks.Compile.Erlang do
...
       For a complete list of options, see `:compile.file/2`.
 
-  For example, to configure the `erlc_options` for your Erlang project you
-  may run:
+  ### Important notice
 
-      erlc_options: [:debug_info, {:i, 'path/to/include'}]
+  The following options are always added to `:erlc_options` when running the compiler:
+
+      [:debug_info, :return, :report, outdir: compile_path, i: include_path]
```
Comment (josevalim) [inline lib/mix/lib/mix/tasks/compile.erlang.ex]: Return and report are implementation details. If the user changes them, then the compiler will fail. I would remove this section (or talk about only debug_info).

Comment (kelvinst) [reply lib/mix/lib/mix/tasks/compile.erlang.ex]: Cool, thanks!! I will comment only about debug_info.

**Comment by fertapric** [comment]
Thanks @kelvinst! 💜
