### PR TITLE
Move evaluation of default timeout in ExUnit to runtime

### LINKED ISSUE #9744: [ex_unit] Missleading error message when using `{assert,refute}_receive` not in `test/2,3`
### Environment

* Elixir & Erlang/OTP versions (elixir --version): tested with 1.9.3-otp-22 and 1.9.4-otp-22, probably affects earlier versions as well
* Operating system: Arch Linux

### Current behavior

Example code available at GitHub: https://github.com/kbredemeier/test_template_issue

Running `mix test` yields the following compile error:

```plain
Compiling 2 files (.ex)

== Compilation error in file test/support/template.ex ==
** (ArgumentError) could not fetch application environment :assert_receive_timeout for application :ex_unit because the application was not loaded/started. If your application depends on :ex_unit at runtime, make sure to load/start it or list it under :extra_applications in your mix.exs file
    (elixir) lib/application.ex:498: Application.fetch_env!/2
    expanding macro: ExUnit.Assertions.assert_receive/1
    test/support/template.ex:13: Template.test_something/0
```

The proposed fix of adding `:ex_unit` to `:extra_applications` does of course not work.

Instead providing a timeout manually to `assert_receive` does indeed fix the error message or calling `Application.ensure_started(:ex_unit)` during compiletime.

### Expected behavior

I see 2 alternative expactations:

#### Improved error message and docs

The error message and the documentation should suggest to provide a default argument instead when not inside of `test/2,3`.

#### Change the default argument

Change the current default value, such that it is quaranteed to be resolved at runtime instead of compiletime-ish.

### PR DESCRIPTION
**Pull request by devonestes**
There were some confusing errors around this evaluation of the default
timeout at compile time, so now it's been moved to runtime.

Resolves #9744

### CODE REVIEW

File: lib/ex_unit/lib/ex_unit/assertions.ex [hunk 1]
```diff
@@ -493,10 +489,10 @@ defmodule ExUnit.Assertions do
       end
 
     timeout =
-      if is_integer(timeout) do
-        timeout
-      else
-        quote do: ExUnit.Assertions.__timeout__(unquote(timeout))
+      case timeout do
```
Comment (josevalim) [inline lib/ex_unit/lib/ex_unit/assertions.ex]: Unfortunately the value can be `nil` at runtime but a var at compilation time, so I think we can always call `ExUnit.Assertions.__timeout__` instead and handle `nil` and defaults in there. WDYT?

Comment (devonestes) [reply lib/ex_unit/lib/ex_unit/assertions.ex]: Yeah, that works better.

File: lib/ex_unit/lib/ex_unit/assertions.ex [hunk 2]
```diff
@@ -529,9 +518,11 @@ defmodule ExUnit.Assertions do
...
 
   @doc false
-  def __timeout__(timeout) when is_integer(timeout) and timeout >= 0, do: timeout
+  def __timeout__(timeout, _) when is_integer(timeout) and timeout >= 0, do: timeout
 
-  def __timeout__(timeout),
+  def __timeout__(nil, key), do: Application.fetch_env!(:ex_unit, key)
+
+  def __timeout__(timeout, _),
     do: raise(ArgumentError, "timeout must be a non-negative integer, got: #{inspect(timeout)}")
```
Comment (fertapric) [inline lib/ex_unit/lib/ex_unit/assertions.ex]: Now that we have the key in here, what do you think about including it in the error message?

Comment (devonestes) [reply lib/ex_unit/lib/ex_unit/assertions.ex]: In what way would we use that key? Something like "timeout must be a non-negative integer, got #{timeout} - set this default in ex_unit.#{key}"?

I'm not totally sure that would be helpful for folks, but I'm happy to include it if y'all think it would be a good thing.

Comment (josevalim) [reply lib/ex_unit/lib/ex_unit/assertions.ex]: Yeah, I don't see how we can use the key here given that we use it only when a timeout is not given?

Comment (fertapric) [reply lib/ex_unit/lib/ex_unit/assertions.ex]: I thought we could use it for saying something like:

> assert_receive timeout must be a non-negative integer, got: ...

But nevermind, probably not worth it

**Comment by fertapric** [comment]
Thanks @devonestes! 💜
