### PR TITLE
Reject invalid line numbers in ExUnit filters

### LINKED ISSUE #9727: Unexpected behavior of mix test with specific invalid line numbers
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.9.4 (compiled with Erlang/OTP 20)
* Operating system: Ubuntu 18.04.3 LTS (kernel 4.15.0-72-generic)

### Current behavior

Create a new Elixir project with `mix new foo`, enter the project path with `cd foo`, then edit  `test/foo_test.exs` to the following:
```elixir
defmodule FooTest do
  use ExUnit.Case
  test "A", do: assert(true)

  test "B", do: assert(true)
  test "C", do: assert(true)
end
```

Examples of current behavior:
```
$ mix test --trace test/foo_test.exs:-43:0:1:2
Excluding tags: [:test]
Including tags: [line: "-43", line: "0", line: "1", line: "2"]


FooTest
  * test A (excluded)
  * test C (excluded)
  * test B (excluded)


Finished in 0.01 seconds
3 tests, 0 failures, 3 excluded

Randomized with seed 642462
```
```
$ mix test --trace test/foo_test.exs:4
Excluding tags: [:test]
Including tags: [line: "4"]


FooTest
  * test B (excluded)
  * test C (excluded)
  * test A (0.00ms)


Finished in 0.01 seconds
3 tests, 0 failures, 2 excluded

Randomized with seed 258138
```
```
$ foo mix test --trace test/foo_test.exs:42
Excluding tags: [:test]
Including tags: [line: "42"]


FooTest
  * test B (excluded)
  * test A (excluded)
  * test C (0.00ms)


Finished in 0.01 seconds
3 tests, 0 failures, 2 excluded

Randomized with seed 489324
```

### Expected behavior

It seems to me that the expected behavior would be (i) to warn about the specific lines that do not exist, such as -43, 0 and 42 (first and last examples); (ii) to warn about specific lines that do not contain any test definition, such as line 1 and 4 (first and second examples); and (iii) to not run any test.

### PR DESCRIPTION
**Pull request by devonestes**
Now if folks give line numbers that are 0 or less, we show a warning and
reject those bad line numbers.

Resolves #9727

### CODE REVIEW

File: lib/ex_unit/lib/ex_unit/filters.ex [hunk 1]
```diff
@@ -47,6 +48,18 @@ defmodule ExUnit.Filters do
     end
   end
 
+  defp invalid_line_number?("0") do
+    IO.warn("Invalid line number given as ExUnit filter: 0", [])
+    true
+  end
+
+  defp invalid_line_number?("-" <> _ = num) do
+    IO.warn("Invalid line number given as ExUnit filter: #{num}", [])
```
Comment (josevalim) [inline lib/ex_unit/lib/ex_unit/filters.ex]:
```suggestion
    IO.warn("invalid line number given as ExUnit filter: #{num}", [])
```

File: lib/ex_unit/lib/ex_unit/filters.ex [hunk 2]
```diff
@@ -47,6 +48,18 @@ defmodule ExUnit.Filters do
     end
   end
 
+  defp invalid_line_number?("0") do
+    IO.warn("Invalid line number given as ExUnit filter: 0", [])
```
Comment (josevalim) [inline lib/ex_unit/lib/ex_unit/filters.ex]:
```suggestion
    IO.warn("invalid line number given as ExUnit filter: 0", [])
```

File: lib/ex_unit/test/ex_unit/filters_test.exs [hunk 3]
```diff
@@ -227,5 +227,10 @@ defmodule ExUnit.FiltersTest do
 
     assert ExUnit.Filters.parse_path("C:\\some\\path.exs:123:456notalinenumber456") ==
              {"C:\\some\\path.exs:123:456notalinenumber456", []}
+
+    ExUnit.CaptureIO.capture_io(:stderr, fn ->
+      assert ExUnit.Filters.parse_path("test/some/path.exs:123:0:-789:456") ==
+              {"test/some/path.exs", [exclude: [:test], include: [line: "123", line: "456"]]}
+    end)
```
Comment (josevalim) [inline lib/ex_unit/test/ex_unit/filters_test.exs]: Let's assert that the warning was printed. :)

**Comment by ericmj** [comment]
Thank you! 💜
