### PR TITLE
Tokenizer uses static_atoms_encoder on quoted keys 3ae53ac 

### LINKED ISSUE #11312: `Code.string_to_quoted/2` `static_atoms_encoder` is not called for quoted keys
### Environment

* Elixir & Erlang/OTP versions (elixir --version): `Elixir 1.12.1 (compiled with Erlang/OTP 24)` (reproduced on master)
* Operating system: Ubuntu 18.04

### Current behavior

```elixir
iex> Code.string_to_quoted(~S(["foo bar": :baz]), static_atoms_encoder: fn x, _ -> {:ok, x} end)
{:ok, ["foo bar": "baz"]}
```

The `:"foo bar"` atom actually gets created. If adding `existing_atoms_only`, it fails:

```elixir
iex> Code.string_to_quoted(~S(["foo bar 2": :baz]), static_atoms_encoder: fn x, _ -> {:ok, x} end, existing_atoms_only: true)
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: invalid UTF8 encoding

    :erlang.binary_to_existing_atom("foo bar 2", :utf8)

```

### Expected behavior

The encoder should be called on all static atoms and prevent atom leaks:

```elixir
iex> Code.string_to_quoted(~S(["foo bar": :baz]), static_atoms_encoder: fn x, _ -> {:ok, x} end)
{:ok, [{"foo bar", "baz"}]}
```

Note: I have a working fix, will open a PR.

### PR DESCRIPTION
**Pull request by sabiwara**
Make the tokenizer call `static_atoms_encoder` on quoted keys.

Question: I re-used `kw_identifier`, should I introduce a new one like `kw_identifier_quoted` to be consistent with `atom_qoted`?

Closes #11312

### CODE REVIEW

File: lib/elixir/src/elixir_tokenizer.erl [hunk 1]
```diff
@@ -757,16 +757,26 @@ handle_strings(T, Line, Column, H, Scope, Tokens) ->
...
+            when is_function(StaticAtomsEncoder) and is_binary(Part) ->
+          case unsafe_to_atom(Part, Line, Column - 1, Scope) of
+            {ok, Atom} ->
+              Token = {kw_identifier, {Line, Column - 1, nil}, Atom},
+              tokenize(Rest, NewLine, NewColumn + 1, NewScope, [Token | Tokens]);
+            {error, Reason} ->
+              {error, Reason, Rest, Tokens}
+          end;
+
+        {{ok, Unescaped}, _} ->
```
Comment (josevalim) [inline lib/elixir/src/elixir_tokenizer.erl:771]:
```suggestion
      case unescape_tokens(Parts, Line, Column, NewScope) of
        {ok, [Part]} when is_binary(Part) ->
          case unsafe_to_atom(Part, Line, Column - 1, Scope) of
            {ok, Atom} ->
              Token = {kw_identifier, {Line, Column - 1, nil}, Atom},
              tokenize(Rest, NewLine, NewColumn + 1, NewScope, [Token | Tokens]);
            {error, Reason} ->
              {error, Reason, Rest, Tokens}
          end;

        {ok, Unescaped} ->
```

File: lib/elixir/test/elixir/kernel/parser_test.exs [hunk 2]
```diff
@@ -154,6 +154,23 @@ defmodule Kernel.ParserTest do
                Code.string_to_quoted("there_is_no_such_var", static_atoms_encoder: encoder)
     end
 
+    test "encodes quoted atom keys" do
```
Comment (josevalim) [inline lib/elixir/test/elixir/kernel/parser_test.exs:157]:
```suggestion
    test "encodes quoted keyword keys" do
```

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
