### PR TITLE
Fix bug in Enum.drop/2

### LINKED ISSUE #12039: `Enum.drop/2` returns an incorrect value for streams
### Elixir and Erlang/OTP versions

```
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.0-rc.0 (6449239) (compiled with Erlang/OTP 25)
```

### Operating system

macOS 12.4

### Current behavior

```elixir
iex> 1..3 |> Stream.map(& &1) |> Enum.drop(-2)
[1, 2, 3]
# which is inconsistent with:
iex> 1..3 |> Enum.drop(-2)
[1]
```

This bug has been introduced in the latest RC, will send a PR.

### Expected behavior

```elixir
iex> 1..3 |> Stream.map(& &1) |> Enum.drop(-2)
[1]
```

### PR DESCRIPTION
**Pull request by sabiwara**
Closes #12039.

We should probably backport this to 1.14 as well.

### CODE REVIEW

File: lib/elixir/test/elixir/enum_test.exs [hunk 1]
```diff
@@ -265,6 +265,20 @@ defmodule EnumTest do
     end
   end
 
+  test "drop/2 with streams" do
+    drop_stream = fn list, count -> list |> Stream.map(& &1) |> Enum.drop(count) end
```
Comment (sabiwara) [inline lib/elixir/test/elixir/enum_test.exs:269]: For now, I went with the same approach as `dedup/1 with streams`, but maybe in the longer run we should have a test case for streams for each function, like `EnumTest.Range`.

**Review by ericmj — APPROVED** [review]
