### PR TITLE
show UTF-8 BOM on inspected strings

### LINKED ISSUE #7084: Show BOM on inspected strings
### Environment

Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.5.2
Ubuntu 17.10

### Current behavior

Strings produced with the `~s` sigil sometimes contain the BOM. If that's the case, then subsequent comparison with the same string created with plain quotes will fail.

Reproduction:
```
iex(50)> s1 = ~s(﻿2017-11-29\t2017-12-02\t"QUOTED"\t"ABCDE"\t"EFG"\t"HIJKLMON"\tPQR)
"﻿2017-11-29\t2017-12-02\t\"QUOTED\"\t\"ABCDE\"\t\"EFG\"\t\"HIJKLMON\"\tPQR"
iex(51)> s2 = "2017-11-29\t2017-12-02\t\"QUOTED\"\t\"ABCDE\"\t\"EFG\"\t\"HIJKLMON\"\tPQR"
"2017-11-29\t2017-12-02\t\"QUOTED\"\t\"ABCDE\"\t\"EFG\"\t\"HIJKLMON\"\tPQR"
iex(52)> s1 == s2
false
```
The BOM is visible upon inspection with `i`:
```
iex(53)> i s1
Term
  "﻿2017-11-29\t2017-12-02\t\"QUOTED\"\t\"ABCDE\"\t\"EFG\"\t\"HIJKLMON\"\tPQR"
Data type
  BitString
Byte size
  62
Description
  This is a string: a UTF-8 encoded binary. It's printed surrounded by
  "double quotes" because all UTF-8 encoded codepoints in it are printable. 
Raw representation
  <<239, 187, 191, 50, 48, 49, 55, 45, 49, 49, 45, 50, 57, 9, 50, 48, 49, 55, 45, 49, 50, 45, 48, 50, 9, 34, 81, 85, 79, 84, 69, 68, 34, 9, 34, 65, 66, 67, 68, 69, 34, 9, 34, 69, 70, 71, 34, 9, 34, 72, ...>>
Reference modules
  String, :binary
Implemented protocols
  IEx.Info, List.Chars, Inspect, String.Chars, Collectable
iex(54)> i s2
Term
  "2017-11-29\t2017-12-02\t\"QUOTED\"\t\"ABCDE\"\t\"EFG\"\t\"HIJKLMON\"\tPQR"
Data type
  BitString
Byte size
  59
Description
  This is a string: a UTF-8 encoded binary. It's printed surrounded by
  "double quotes" because all UTF-8 encoded codepoints in it are printable. 
Raw representation
  <<50, 48, 49, 55, 45, 49, 49, 45, 50, 57, 9, 50, 48, 49, 55, 45, 49, 50, 45, 48, 50, 9, 34, 81, 85, 79, 84, 69, 68, 34, 9, 34, 65, 66, 67, 68, 69, 34, 9, 34, 69, 70, 71, 34, 9, 34, 72, 73, 74, 75, ...>>
Reference modules
  String, :binary
Implemented protocols
  IEx.Info, List.Chars, Inspect, String.Chars, Collectable
```

### Expected behavior

I would expect the string comparison to pass. I had this exact case in ExUnit case and the test would fail with printing the same strings and saying they failed the equality check, which is super-confusing.

### PR DESCRIPTION
**Pull request by dmlittle**
As per #7084, this PR adds the printing of the UTF-8 BOM on inspected strings. I think this is the right behavior, but if anything needs being revisited I'm happy to talk about it.

Closes #7084

### CODE REVIEW

File: lib/elixir/test/elixir/inspect_test.exs [hunk 1]
```diff
@@ -175,6 +175,10 @@ defmodule Inspect.BitStringTest do
     # non printable strings aren't affected by printable limit
     assert inspect(<<0, 1, 2, 3, 4>>, printable_limit: 3) == ~s(<<0, 1, 2, 3, 4>>)
   end
+
+  test "utf-8 BOM" do
+    assert inspect("\uFEFFhello world") == "\"\\uFEFFhello world\""
```
Comment (AndrewDryga) [inline lib/elixir/test/elixir/inspect_test.exs]: Right part is a little bit ugly, maybe string literal `~s("\\uFEFFhello world")` would look there better?

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
What about zero width spaces? Shouldn't it be the same approach?
