### PR TITLE
Raise if a macro is invoked before its definition

### LINKED ISSUE #8626: internal error in beam_dead on wrong record usage
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.9.0-dev (786740a79) (compiled with Erlang/OTP 21)
* Operating system: macOS 

### Current behavior

As I've been moving code around I've accidentally ended up with a record definition _below_ the usage of generated some_record/2 function. Here's a repro:

This works:

```elixir
defmodule M do
  require Record
  Record.defrecord :point, [:x, :y]

  def xs(points) do
    Enum.map(points, &point(&1, :x))
  end
end
```

This crashes:

```elixir
defmodule M do
  def xs(points) do
    Enum.map(points, &point(&1, :x))
  end

  require Record
  Record.defrecord :point, [:x, :y]
end
```

```
% elixir a.ex
Function -xs/1-fun-0-/1 refers to undefined label 39
** (CompileError) a.ex: internal error in beam_dead;
crash reason: {case_clause,{'EXIT',{undefined_label,39}}}

  in function  compile:'-select_passes/2-anonymous-2-'/3 (compile.erl, line 585)
  in call from compile:'-internal_comp/5-anonymous-1-'/3 (compile.erl, line 349)
  in call from compile:fold_comp/4 (compile.erl, line 376)
  in call from compile:internal_comp/5 (compile.erl, line 360)
  in call from compile:'-do_compile/2-anonymous-0-'/2 (compile.erl, line 177)
  in call from elixir_erl_compiler:compile/4 (src/elixir_erl_compiler.erl, line 52)
  in call from elixir_erl:load_form/5 (src/elixir_erl.erl, line 444)
  in call from elixir_erl_compiler:'-spawn/2-fun-0-'/3 (src/elixir_erl_compiler.erl, line 12)
    (stdlib) lists.erl:1338: :lists.foreach/2
    (elixir) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
    (elixir) lib/code.ex:767: Code.require_file/2

shell returned 1
```
### Expected behavior

Undefined function error.

### PR DESCRIPTION
**Pull request by fertapric**
Closes #8626

### CODE REVIEW

File: lib/elixir/lib/module/locals_tracker.ex [hunk 1]
```diff
@@ -104,13 +105,31 @@ defmodule Module.LocalsTracker do
...
   end
 
+  @doc """
+  Collects incorrect dispatches based on local calls and existing
+  definitions.
+
+  An incorrect dispatch occurs when a macro is invoked before its
+  definition.
+  """
+  def collect_incorrect_dispatches({set, bag}, all_defined) do
```
Comment (josevalim) [inline lib/elixir/lib/module/locals_tracker.ex]: Unfortunately this requires you to traverse all definitions and all calls.

I wonder if instead we should have a new entry in the table like this:

    {:macro_call, caller, callee}

And  then we just need to traverse the calls. Thoughts?

Comment (fertapric) [reply lib/elixir/lib/module/locals_tracker.ex]: This function detects "function calls" that should have been dispatched as "macro calls". I think the structure should be then `{:function_call, caller, callee}`.

Regarding performance, I thought about merging all the `collect_*` functions in the locals tracker so we only traverse definitions and calls once, but I was thinking on doing that in a different PR 🙂 

Thoughts?

Comment (josevalim) [reply lib/elixir/lib/module/locals_tracker.ex]: The other `collect` functions end-up looking up for different data, so I wouldn't worry about merging them, but this could definitely be merged with `unused_locals`. They are even part of the same problem. So what if we merge those two already and have it return something like `{pair, line, reason}` as you proposed? Then I don't think we need to do the changes I mentioned above.  :+1:

Comment (fertapric) [reply lib/elixir/lib/module/locals_tracker.ex]: > but this could definitely be merged with `unused_locals`

This was prevously raising an “undefined function error”, so I was thinking on merging it with `collect_undefined_locals`.

Comment (josevalim) [reply lib/elixir/lib/module/locals_tracker.ex]: Sorry, I meant indeed to merge with `collect_undefined_locals`, that's the closest one. :)

File: lib/elixir/lib/module/locals_tracker.ex [hunk 2]
```diff
@@ -100,36 +100,30 @@ defmodule Module.LocalsTracker do
...
+  Collect undefined functions based on local calls and existing definitions.
   """
   def collect_undefined_locals({set, bag}, all_defined) do
     undefined =
       for {pair, _, _, _} <- all_defined,
-          {local, line, _} <- out_neighbours(bag, {:local, pair}),
-          not :ets.member(set, {:def, local}),
-          do: {build_meta(line), local}
+          {local, line, macro_dispatch?} <- out_neighbours(bag, {:local, pair}),
+          reduce: [] do
```
Comment (josevalim) [inline lib/elixir/lib/module/locals_tracker.ex]: I would say this would be clearer as something like:

    for {pair, _, _, _} <- all_defined,
        {local, line, macro_dispatch?} <- out_neighbours(bag, {:local, pair}),
        warning = undefined_or_invalid_local(set, local, line, kind, macro_dispatch?),
        do: warning

Thoughts?

Comment (josevalim) [reply lib/elixir/lib/module/locals_tracker.ex]: Or perhaps even better:

```elixir
for {pair, _, _, _} <- all_defined,
    {local, line, macro_dispatch?} <- out_neighbours(bag, {:local, pair}),
    warning = undefined_or_invalid_local(set, local, kind, macro_dispatch?),
    do: {build_meta(line), local, warning} 
```

File: lib/elixir/test/elixir/module/locals_tracker_test.exs [hunk 3]
```diff
@@ -51,37 +51,37 @@ defmodule Module.LocalsTrackerTest do
...
   test "private definitions with all used default arguments", config do
-    D.add_local(config[:ref], {:public, 1}, {:private, 0}, line: 1)
+    D.add_local(config[:ref], {:public, 1}, {:private, 0}, [line: 1], false)
     unused = D.collect_unused_locals(config[:ref], @used, @unused)
     assert unused == {[private: 3], []}
   end
 
   ### Undefined functions
 
   test "undefined functions are marked as so", config do
```
Comment (josevalim) [inline lib/elixir/test/elixir/module/locals_tracker_test.exs]: Shall we have a unit test for this new behaviour too?

File: lib/elixir/lib/module/locals_tracker.ex (hunk 2 above)
Comment (fertapric) [reply lib/elixir/lib/module/locals_tracker.ex]: I got carried away with `for reduce: ...` 😅 

I like your suggestion.

File: lib/elixir/lib/module/locals_tracker.ex [hunk 4]
```diff
@@ -196,6 +210,10 @@ defmodule Module.LocalsTracker do
   defp build_meta(nil), do: []
   defp build_meta(line), do: [line: line]
 
+  defp is_macro(:defmacro), do: true
+  defp is_macro(:defmacrop), do: true
```
Comment (josevalim) [inline lib/elixir/lib/module/locals_tracker.ex]: Maybe make it a `defguardp` as you have this logic here and also here `when kind in [:defmacro, :defmacrop]`? Or use a module attribute: `@macros [:defmacro, :defmacrop]` and do a `kind in @macros` in both.

I prefer the module attribute, but your calll.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
