### PR TITLE
Handle external files for xref callers and warnings

### LINKED ISSUE #6629: `mix xref callers` and Phoenix templates
Original bug report: https://github.com/phoenixframework/phoenix/issues/2543

### Environment

* Elixir & Erlang versions (elixir --version): 1.5.2/OTP 20
* Operating system: macOS Sierra

### Current behavior

Let's say I have following files:

```elixir
# post_view.ex
defmodule ExampleWeb.PostView do
  use ExampleWeb, :view
end
```

```eex
# lib/example_web/templates/post/index.html.eex
line 1
line 2
<%= String.upcase("foo") %>
```

```
$ mix xref callers String.upcase
lib/example_web/views/post_view.ex:3: String.upcase/1
```

Note xref correctly got the line number but used views' filename instead of template's.

### Expected behavior

```
$ mix xref callers String.upcase
lib/example_web/templates/post/index.html.eex:3: String.upcase/1
```

### PR DESCRIPTION
**Pull request by ggcampinho**
Use the file location available in the manifest to display external sources.

Closes #6629

### CODE REVIEW

**Comment by ggcampinho** [comment]
I focused the fix on what was asked on the issue, can I create another PR fixing the warnings for xref also?

File: lib/mix/lib/mix/tasks/xref.ex [hunk 1]
```diff
@@ -312,36 +318,41 @@ defmodule Mix.Tasks.Xref do
   ## Callers
 
   defp do_callers(filter) do
```
Comment (josevalim) [inline lib/mix/lib/mix/tasks/xref.ex]: Since we are changing around here, should we call this `print_callers` or `format_callers`? We are getting rid of the `do_` prefix.

File: lib/mix/lib/mix/tasks/xref.ex [hunk 2]
```diff
@@ -511,4 +520,11 @@ defmodule Mix.Tasks.Xref do
 
   defp line_location({_file, line}), do: line
   defp line_location(line), do: line
```
Comment (josevalim) [inline lib/mix/lib/mix/tasks/xref.ex]: Is there a reason why we still need this function?

File: lib/mix/lib/mix/tasks/xref.ex [hunk 3]
```diff
@@ -164,7 +166,11 @@ defmodule Mix.Tasks.Xref do
 
   defp unreachable(pair_fun) do
     excludes = excludes()
-    each_source_entries(&source_warnings(&1, excludes), pair_fun)
+
+    for source(source: file) = source <- sources(),
+        entries = source_warnings(source, excludes),
+        entries != [],
+        do: pair_fun.(file, entries)
```
Comment (josevalim) [inline lib/mix/lib/mix/tasks/xref.ex]: I think we will need to revisit this approach. If you look at `warnings/2`, you will see it has to return something like `{file, warnings}` but the warnings now can belong to many files. We will probably need to first get all warnings in a structure like `{file, line, {module, function, arity}}` and then let each part of `xref` group it as they find necessary. For example, callers may want to group by `{module, function, arity}`. The warnings will want to group by `file` and so on.

 I think by then we will no longer need `pair_fun` and instead we will end-up doing something like `unreachable() |> group_by_x |> print`.

Thoughts?

**Comment by josevalim** [comment]
@ggcampinho let's please go ahead and fix everything because I think fixing the warnings will require substantial changes to this file. :)

**Comment by ggcampinho** [comment]
@josevalim I had some code for the warnings on another branch, so I moved here. I think they address your previous concerns. I did a small refactor after to address the naming and to let the code on the functions similar. Please take a look 🙂 

Also, I would like to point that the graph also don't cover the external sources and if it makes sense I would like to tackle this, but I think it isolated enough to be done in another PR.

**Comment by josevalim** [comment]
This is beautiful! :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment]
@ggcampinho about `mix xref graph` I can see both arguments. For example, it would make the output of running the graph on Phoenix much more complex. What are your thoughts?

**Comment by ggcampinho** [comment]
@josevalim I agree for Phoenix will be complex, but also really helpful when you try to find who is using a shared partial, or things like that. I took a quick look on the render functions there, but I don't fully understand yet how the rendering works if this actually makes sense. I would guess that some option flag like `external=false` or something like that, would solve the problem, but I think I need more context to push this forward. Now, I'm leaning on leave as it is.
