### PR TITLE
fix(Kernel): check arguments on if and unless

### LINKED ISSUE #3614: Raise when invalid keyword arguments are passed to if.
Following on from a discussion on irc with @josevalim and @rvirding

Currently the following uses of the `if` macro are valid:

```elixir
if true, blarp: 7 # => nil
if true, doo: 7, else: 6 # => nil
if false, else: 1 # => 1
if true, [] # => nil
if true, do: 1, do: 2 # => 1
```

Ideally the `if` macro should ensure that `do` is required, `else` is optional, if not then an error should be raised. This will help users with typos such as the second example above.

It would be nice if it warned on duplicate keys too.

### PR DESCRIPTION
**Pull request by Gazler**
`Kernel.if` and `Kernel.unless` are now only valid if there is exactly
one `do` key and optionally an `else` key.

Any calls to the if macro that do not satisfy these conditions raise an
ArgumentError with a relevant error message.

This closes #3614 and is an alternative to #3615

### CODE REVIEW

File: lib/elixir/lib/kernel.ex [hunk 1]
```diff
@@ -2303,6 +2308,10 @@ defmodule Kernel do
     end)
   end
 
+  defp build_if(_condition, _keys) do
+    raise(ArgumentError, "invalid or duplicate keys for if")
```
Comment (ericmj) [inline lib/elixir/lib/kernel.ex]: Change keys to arguments or maybe blocks. Maybe we can also print the keys that are invalid.

Same for build_unless.

File: lib/elixir/lib/kernel.ex [hunk 2]
```diff
@@ -2303,6 +2308,11 @@ defmodule Kernel do
     end)
   end
 
+  defp build_if(_condition, _arguments) do
+    raise(ArgumentError, "invalid or duplicate keys for if, only `do` " <>
+    "and an optional `else` are permitted.")
```
Comment (josevalim) [inline lib/elixir/lib/kernel.ex]: No period at the end of error messages!

File: lib/elixir/lib/kernel.ex [hunk 3]
```diff
@@ -2328,14 +2338,26 @@ defmodule Kernel do
...
+  defp build_unless(condition, do: do_clause, else: else_clause) do
     quote do
-      if(unquote(clause), do: unquote(else_clause), else: unquote(do_clause))
+      if(unquote(condition), do: unquote(else_clause), else: unquote(do_clause))
     end
   end
 
+  defp build_unless(_condition, _arguments) do
+    raise(ArgumentError, "invalid or duplicate keys for unless, only `do` " <>
+      "and an optional `else` are permitted.")
```
Comment (josevalim) [inline lib/elixir/lib/kernel.ex]: No period!

File: lib/elixir/lib/kernel.ex [hunk 4]
```diff
@@ -2328,14 +2338,26 @@ defmodule Kernel do
...
+  end
+
+
```
Comment (josevalim) [inline lib/elixir/lib/kernel.ex]: :scissors:

**Comment by josevalim** [comment]
Let's just remove the period from error messages and we are good to go! :D

**Comment by Gazler** [comment]
@josevalim No more periods in the messages!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
