### PR TITLE
Enhance in/2 to support |/2

### LINKED ISSUE #4968: `x in [1 | rest]` raises `undefined function |/2`
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.1
```

* Operating system:

OS X El Capitan

### Current behavior

```
iex(1)> x = 5
5
iex(2)> nums = 2..5 |> Enum.to_list
[2, 3, 4, 5]
iex(3)> x in [1 | nums]
** (CompileError) iex:3: undefined function |/2
    (elixir) expanding macro: Kernel.in/2
             iex:3: (file)
```

### Expected behavior
 
I'd expect to be able to prepend to a list on the right side of an `in` expression.  I also tried using parens (`x in ([1 | nums])`) -- which seems like that should force the prepend to be evaluated first -- but that also fails.  It works if I do this, though:

```
iex(3)> list = [1 | nums]
[1, 2, 3, 4, 5]
iex(4)> x in list
true
```

### PR DESCRIPTION
**Pull request by antipax**
Closes #4968.

### CODE REVIEW

File: lib/elixir/lib/kernel.ex [hunk 1]
```diff
@@ -2872,6 +2872,8 @@ defmodule Kernel do
         :lists.foldr(fn x, acc ->
           quote do: :erlang.or(unquote(comp(left, x)), unquote(acc))
         end, comp(left, h), t)
+      {:++, _meta, [h, t]} ->
+        quote do: :erlang.or(unquote(left) in unquote(t), unquote(left) in unquote(h))
```
Comment (lexmag) [inline lib/elixir/lib/kernel.ex]: Why in that order? It's changes semantics.

File: lib/elixir/test/elixir/kernel_test.exs [hunk 2]
```diff
@@ -94,16 +94,28 @@ defmodule KernelTest do
...
 
   @at_list  [4, 5]
   @at_range 6..8
+  @at_list2 [13, 14]
+  @at_list3 [19, 20]
   @doc "fun_in/1"
   "fun_in/1" = @doc
   def fun_in(x) when x in [0],       do: :list
   def fun_in(x) when x in 1..3,      do: :range
   def fun_in(x) when x in @at_list,  do: :at_list
```
Comment (lexmag) [inline lib/elixir/test/elixir/kernel_test.exs]: Probably we should name it `@at_list1` then.

File: lib/elixir/lib/kernel.ex [hunk 3]
```diff
@@ -2924,6 +2926,10 @@ defmodule Kernel do
     end
   end
 
+  defp comp(left, {:|, _, [h, t]}) do
+    quote(do: :erlang.or(unquote(left) in unquote(t), :erlang."=:="(unquote(left), unquote(h))))
```
Comment (lexmag) [inline lib/elixir/lib/kernel.ex]: Different order?

File: lib/elixir/test/elixir/kernel_test.exs [hunk 4]
```diff
@@ -194,6 +230,30 @@ defmodule KernelTest do
     end
   end
 
+  test "in/2 with a non-compile-time list cons in guards" do
+    message = ~r/invalid args for operator "in", .* got: list()/
```
Comment (lexmag) [inline lib/elixir/test/elixir/kernel_test.exs]: We need to escape `()` in regex.

File: lib/elixir/lib/kernel.ex (hunk 1 above)
Comment (lexmag) [inline lib/elixir/lib/kernel.ex]: For example `1 in [1] ++ nil`.

File: lib/elixir/lib/kernel.ex (hunk 3 above)
Comment (antipax) [inline lib/elixir/lib/kernel.ex]: Yeah, I wasn't sure about this but I went with the same order that other optimized in/2 cases use, such as this example from the tests:

```elixir
assert expand_to_string(quote(do: foo in [1, 2])) ==
             ~S[:erlang.or(:erlang.=:=(foo, 2), :erlang.=:=(foo, 1))]
```

File: lib/elixir/lib/kernel.ex (hunk 1 above)
Comment (antipax) [inline lib/elixir/lib/kernel.ex]: Same reason for the order as below, but I'm not 100% sure I know what change in semantics you mean. Is it that `right` will be evaluated before `left` in this case?

File: lib/elixir/test/elixir/kernel_test.exs (hunk 4 above)
Comment (antipax) [inline lib/elixir/test/elixir/kernel_test.exs]: Good catch!

File: lib/elixir/lib/kernel.ex (hunk 1 above)
Comment (lexmag) [inline lib/elixir/lib/kernel.ex]: The difference will be in that currently `1 in [1] ++ nil` won't raise any error and with patch it will raise.
Anyway, I think we shouldn't rewrite `++` case as it is illegal expression in guards on it's own.
Also I believe this patch will make the error message for `123 ++ []` case worse as well.

File: lib/elixir/lib/kernel.ex (hunk 3 above)
Comment (lexmag) [inline lib/elixir/lib/kernel.ex]: For other cases order not that important but for this specific one I think we should put less costly check at first position.

File: lib/elixir/lib/kernel.ex (hunk 1 above)
Comment (antipax) [inline lib/elixir/lib/kernel.ex]: Cool, will just back out the `++` stuff then.

File: lib/elixir/lib/kernel.ex (hunk 3 above)
Comment (antipax) [inline lib/elixir/lib/kernel.ex]: Ok, cool. I wasn't sure if we wanted to preserve the exact semantics of the other cases or whether performance was more important. Will make the change.

File: lib/elixir/test/elixir/kernel_test.exs [hunk 5]
```diff
@@ -203,18 +263,24 @@ defmodule KernelTest do
...
+           ~S[:erlang.or(:erlang.=:=(foo, 2), :erlang.=:=(foo, 1))]
+
+    assert expand_to_string(quote(do: foo in [1] ++ [2])) ==
+           ~S[:erlang.or(:erlang.=:=(foo, 2), :erlang.=:=(foo, 1))]
   end
 
   defp expand_to_string(ast) do
     ast
-    |> Macro.expand(__ENV__)
+    |> Macro.prewalk(&Macro.expand(&1, __ENV__))
```
Comment (lexmag) [inline lib/elixir/test/elixir/kernel_test.exs]: 👍

**Comment by josevalim** [comment]
Looks good to me!  :heart: :green_heart: :blue_heart: :yellow_heart: 💜 

@lexmag, please merge when you are done!
