### PR TITLE
[ExUnit] fix output when absolute path is given

### LINKED ISSUE #12233: mix test with absolute path on umbrella project root doesn't work as expected
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:32:12] [ds:32:12:10] [async-threads:1] [jit:ns]

Elixir 1.14.1 (compiled with Erlang/OTP 25)

### Operating system

Arch

### Current behavior

With a new umbrella project like this
.
├── apps
│   ├── bar
│   └── foo
├── _build
│   └── test
└── config
`pwd`: /tmp/umbrella

Running `mix test /tmp/umbrella/apps/bar/test/bar_test.exs` gives the following output:
```
==> foo
..
Finished in 0.01 seconds (0.00s async, 0.01s sync)
1 doctest, 1 test, 0 failures

Randomized with seed 436342
==> bar

Finished in 0.00 seconds (0.00s async, 0.00s sync)
0 failures

Randomized with seed 436342
```

Running the `foo_test.exs` gives the exact same result.

It looks like the tests are run for the same app which is the first to be compiled in an umbrella project.

### Expected behavior

It should run the right test when using an absolute path

### PR DESCRIPTION
**Pull request by joaopsramos**
Closes #12233

### CODE REVIEW

File: lib/mix/lib/mix/tasks/test.ex [hunk 1]
```diff
@@ -434,7 +434,7 @@ defmodule Mix.Tasks.Test do
         files
         |> Enum.map(&Path.expand/1)
         |> Enum.map(&Path.relative_to_cwd/1)
-        |> Enum.split_with(&String.starts_with?(&1, "apps/"))
+        |> Enum.split_with(&String.contains?(&1, "apps/"))
```
Comment (josevalim) [inline lib/mix/lib/mix/tasks/test.ex:437]: Unfortunately this check can have also positives, for example, if you have a folder called "company-apps". We will need to take a look into other ways to address this.

File: lib/mix/lib/mix/tasks/test.ex [hunk 2]
```diff
@@ -430,11 +430,14 @@ defmodule Mix.Tasks.Test do
...
+      parent_umbrella = Path.dirname(Mix.Project.parent_umbrella_project_file())
+
       {files_in_apps_path, files_not_in_apps_path} =
         files
-        |> Enum.map(&Path.expand/1)
-        |> Enum.map(&Path.relative_to_cwd/1)
+        |> Enum.map(&Path.expand(&1, parent_umbrella))
+        |> Enum.map(&Path.relative_to(&1, parent_umbrella))
         |> Enum.split_with(&String.starts_with?(&1, "apps/"))
+        |> dbg()
```
Comment (josevalim) [inline lib/mix/lib/mix/tasks/test.ex:440]:
```suggestion
```

File: lib/mix/lib/mix/tasks/test.ex [hunk 3]
```diff
@@ -456,7 +458,7 @@ defmodule Mix.Tasks.Test do
 
   defp relative_app_file_exists?(file) do
     {file, _} = ExUnit.Filters.parse_path(file)
-    File.exists?(Path.join("../..", file))
+    File.exists?(Path.join("../..", file)) || File.exists?(file)
```
Comment (josevalim) [inline lib/mix/lib/mix/tasks/test.ex:461]:
```suggestion
    File.exists?(Path.join("../..", file))
```

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
