### PR TITLE
Fix divergedreq error when update changes requirement and version

### LINKED ISSUE #9806: Spurious error from `mix deps.update` on Elixir 1.10
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

```
$ elixir --version
Erlang/OTP 22 [erts-10.6] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.10.1 (compiled with Erlang/OTP 22)
```

* Operating system: 

MacOS 10.15.3

### Current behavior

`mix deps.update` on Elixir 1.10 is throwing a spurious "Dependencies have diverged" error when upgrading a package. Interestingly the update appears to succeed and everything works fine afterwards. I've created a minimal reproduction here: https://github.com/bismark/elixir-mix-bug

### Expected behavior

No error is thrown.

### PR DESCRIPTION
**Pull request by ericmj**
The fix is to mark the dependency for compilation in the Fetcher (by
touching .fetch) so that the Loader wont read the version from the .app
file.

Fixes #9806.

### CODE REVIEW

File: lib/mix/lib/mix/dep/fetcher.ex [hunk 1]
```diff
@@ -64,12 +64,9 @@ defmodule Mix.Dep.Fetcher do
             scm.checkout(opts)
           end
 
-        if new do
```
Comment (ericmj) [inline lib/mix/lib/mix/dep/fetcher.ex]: Removed this `if` since all SCMs should always return the lock.

File: lib/mix/lib/mix/dep/fetcher.ex [hunk 2]
```diff
@@ -92,22 +89,18 @@ defmodule Mix.Dep.Fetcher do
...
-    # If there is any other dependency that is not ok, we include
-    # it for compilation too, this is our best to try to solve the
-    # maximum we can at each deps.get and deps.update.
-    deps =
+    parent_deps =
       if Enum.all?(all_deps, &available?/1) do
         Enum.uniq_by(with_depending(deps, all_deps), & &1.app)
       else
-        deps
+        []
```
Comment (ericmj) [inline lib/mix/lib/mix/dep/fetcher.ex]: We don't have to mark these as fetched since they were marked immediately after fetching.

File: lib/mix/lib/mix/dep/fetcher.ex [hunk 3]
```diff
@@ -92,22 +89,18 @@ defmodule Mix.Dep.Fetcher do
     # dependency is missing, it could directly affect one of the
     # dependencies we are trying to compile, causing the whole thing
     # to fail.
-    #
-    # If there is any other dependency that is not ok, we include
-    # it for compilation too, this is our best to try to solve the
-    # maximum we can at each deps.get and deps.update.
```
Comment (ericmj) [inline lib/mix/lib/mix/dep/fetcher.ex]: Removed this comment since it doesn't seem to be true?

**Comment by ericmj** [comment]
Added test on hex ^.

File: lib/mix/lib/mix/dep/fetcher.ex (hunk 1 above)
Comment (josevalim) [reply lib/mix/lib/mix/dep/fetcher.ex]: Path SCMs do not return a lock if there was no lock before. So I would add it back.

**Comment by lukaszsamson** [comment]
@josevalim @ericmj Can this fix be backported to 1.10? I keep running into https://github.com/elixir-lang/elixir/issues/9806 every on every `mix deps.update`

**Comment by ericmj** [comment]
I have backported it but I don't know if there will be another 1.10 release.
