### PR TITLE
Make Exception.blame/3 extensible

### LINKED ISSUE #7074: Add blame/2 as a callback of the Exception behaviour
`Exception.blame/3` should normalize errors and delegate to the callback:

```elixir
  def blame(:error, error, stacktrace) do
    %module{} = struct = normalize(:error, error, stacktrace)
    module.blame(struct, stacktrace)
  end
```

The callback should return a tuple with the blamed exception and the stacktrace. A default callback will be generated by default by defexception.

/cc @michalmuskala @chrismccord

### PR DESCRIPTION
**Pull request by michalmuskala**
Provide an optional callback for exception: blame/2 that can be used to
augment the exceptions with some additional data that requires expensive
computation and shouldn't be done in every place, for example,
FunctionClauseError that will look up the clauses in the .beam file.

Closes #7074

### CODE REVIEW

File: lib/elixir/lib/exception.ex [hunk 1]
```diff
@@ -163,48 +172,29 @@ defmodule Exception do
...
   def blame(:error, error, stacktrace) do
-    case normalize(:error, error, stacktrace) do
-      %{__struct__: FunctionClauseError} = struct ->
-        blame_function_clause_error(struct, stacktrace)
+    %module{} = struct = normalize(:error, error, stacktrace)
 
-      _ ->
-        {error, stacktrace}
+    if Code.ensure_loaded?(module) and function_exported?(module, :blame, 2) do
+      module.blame(struct, stacktrace)
```
Comment (michalmuskala) [inline lib/elixir/lib/exception.ex]: Should we do some basic sanity check against the returned value to see, if it's valid?

Comment (josevalim) [reply lib/elixir/lib/exception.ex]: Let's go simple for now, I think we are fine.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
