### PR TITLE
Ensure unconstrained rebar deps generate valid mix specifications.

### LINKED ISSUE #11062: Parsing of rebar3 unconstrained hex deps causes mix to crash itself
* Elixir & Erlang/OTP versions (elixir --version): 

```
Erlang/OTP 24 [erts-12.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]
Elixir 1.12.1 (compiled with Erlang/OTP 24)
```

* Operating system: 

`Darwin [...] 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64`

### Current behavior

Fetching rebar3 dependencies with no version constraints in their transitive deps is parsed in a way where mix's own parsing causes it to fail.

I was trying with the following sample specification for dependencies:

```
  defp deps do
    [
      {:recon, ">= 0.0.0"},
      {:grpcbox, "~> 0.14.0", override: true},
      {:opentelemetry_api, git: "http://github.com/open-telemetry/opentelemetry-erlang", branch: "master", sparse: "apps/opentelemetry_api", override: true},
      {:opentelemetry, git: "http://github.com/open-telemetry/opentelemetry-erlang", branch: "master", sparse: "apps/opentelemetry", override: true},
      {:opentelemetry_exporter, git: "http://github.com/open-telemetry/opentelemetry-erlang", branch: "master", sparse: "apps/opentelemetry_exporter", override: true}
    ]
  end
```

This is interesting because I'm trying to get the `master` branch, which is defined in Erlang and has `:opentelemetry` as a subdirectory checkout: https://github.com/open-telemetry/opentelemetry-erlang/blob/master/apps/opentelemetry/rebar.config (the issue is gone on `main`, the new mainline branch, but still happens there with `grpcbox` as a dep), with no lockfile to further limit the dependency.

However, when this is parsed by mix, the content returns a `nil` version constraint:

https://github.com/elixir-lang/elixir/blob/ba78d902e3bd084edf02416f82316715eec0795b/lib/mix/lib/mix/rebar.ex#L107-L109

This is seen as invalid in the dep loader: https://github.com/elixir-lang/elixir/blob/ba78d902e3bd084edf02416f82316715eec0795b/lib/mix/lib/mix/dep/loader.ex#L162-L168

### Expected behavior

The actual proper semantics would likely be to return it as `{app, ">= 0.0.0", override: true}`, which would match the intent behind rebar3's format, and avoid parsing dependencies in a ways that crashes itself.

### PR DESCRIPTION
**Pull request by christhekeele**
Not super sure of this, but noticed #11062 and thought I'd take a stab at it.

Fixes #11062.

### CODE REVIEW

File: lib/mix/test/mix/rebar_test.exs [hunk 1]
```diff
@@ -111,6 +111,9 @@ defmodule Mix.RebarTest do
 
       assert parse_dep({:git_rebar, '', {:git, @git_rebar_charlist, {:ref, '64691eb'}}}) ==
                {:git_rebar, ~r"", override: true, git: @git_rebar_string, ref: "64691eb"}
+
+      assert parse_dep({:git_rebar, {:git, @git_rebar_charlist, {:ref, '64691eb'}}}) ==
+               {:git_rebar, override: true, git: @git_rebar_string, ref: "64691eb"}
```
Comment (josevalim) [inline lib/mix/test/mix/rebar_test.exs:116]: I think the test you want is this:

```suggestion
      assert parse_dep(:git_rebar) == {:git_rebar, override: true}
```

:)

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
