### PR TITLE
Fix nfd cluster columns

### LINKED ISSUE #11142: column metadata does not consider grapheme clusters
Take the following code:

    Code.string_to_quoted("'josé' = 1", columns: true)

where "josé" is written in nfd format. The column for the equal sign will be 9 but it should be 8.

This issue exists on master and doesn't depend on the OTP version.

### PR DESCRIPTION
**Pull request by WLSF**
- [x] Add tests for NFD vs NFC cases with columns
- [x] Add spaces between `Column + 2`
- [x] Add new validation to disregard `\r\n` tokens on cluster
- [x] Add `unicode_util:gc/1` to clusterize NFD symbols

Fix #11142

### CODE REVIEW

File: lib/elixir/src/elixir_interpolation.erl [hunk 1]
```diff
@@ -52,12 +52,21 @@ extract(Line, Column, Scope, true, [$#, ${ | Rest], Buffer, Output, Last) ->
...
-  extract(Line, Column+2, Scope, Interpol, Rest, [Char, $\\ | Buffer], Output, Last);
+  extract(Line, Column + 2, Scope, Interpol, Rest, [Char, $\\ | Buffer], Output, Last);
 
 %% Catch all clause
 
 extract(Line, Column, Scope, Interpol, [Char | Rest], Buffer, Output, Last) ->
-  extract(Line, Column + 1, Scope, Interpol, Rest, [Char | Buffer], Output, Last).
+  NewRest =
+    case Rest of
+      [$\r, $\n | _T] ->
```
Comment (WLSF) [inline lib/elixir/src/elixir_interpolation.erl:62]: I had to add this validation, because when `unicode_util:gc/1` finds these tokens together it clusterizes them, and it was breaking the heredocs validation in the extract functions above

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by jpbrab0** [comment]
AEEEEEEEEEEEE! Parabéns Will!
