### PR TITLE
Fix #3914: split IEx server/evaluator state to prevent unnecessary copying

### LINKED ISSUE #3914: assigning enormous data to a variable makes IEx slow and could result in crash
```
Erlang/OTP 18 [erts-7.1] [source-2882b0c] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.1.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> q = 1..1000 |> Enum.map fn _ -> Enum.to_list 1..30000  end ; :ok
:ok
iex(2)> 1
1
iex(3)> 1
1
iex(4)> 1

Crash dump is being written to: erl_crash.dump...done
eheap_alloc: Cannot allocate 790960704 bytes of memory (of type "heap").
Aborted (core dumped)
```
each ```1``` took about a second to evaluate

### PR DESCRIPTION
**Pull request by antipax**
* Splits `IEx.State` into `IEx.State` (which contains `cache`, `counter`, and `prefix`)  and `IEx.Evaluator.State` (which contains `binding`, `scope`, and `env`).
* `IEx.State` continues to be stored in the server and passed to the evaluator
* `IEx.Evaluator.State` is stored in the evaluator to enhance performance when large values are stored
* Peeking at the environment is retrieved via message-passing from the evaluator, rather than simply returned from the server.

In my testing I noticed that `IEx.Server.current_env/0` didn't work with the new code, but it also seemed not to work without this patch, as well. Not sure what the intended use of that function is. Other than that, everything seems to work as expected and all iex tests pass.

### CODE REVIEW

**Comment by antipax** [comment]
Oops, wrong version of the code ended up here... updating

**Comment by josevalim** [comment]
A couple things to check:

  1. current_env should not be called from IEx itself but from another process. One way to check it is working as expected is if you can autocomplete aliases:

        ```
        iex(1)> alias Kernel, as: K
        nil
        iex(2)> K.P<tab>
        ```

    If it autocompletes, you are ok.

  2. Check if `v(0)`, `v(-1)` and friends still work as expected

File: lib/iex/lib/iex/evaluator.ex [hunk 1]
```diff
@@ -1,3 +1,9 @@
+defmodule IEx.Evaluator.State do
```
Comment (josevalim) [inline lib/iex/lib/iex/evaluator.ex]: Given we don't match on this anywhere, we should just make it a map.

File: lib/iex/lib/iex/server.ex [hunk 2]
```diff
@@ -274,13 +279,18 @@ defmodule IEx.Server do
...
     binding = Keyword.get(opts, :binding, [])
+    evaluator_state  = %IEx.Evaluator.State{binding: binding, scope: scope, env: env}
+
+    evaluator_state =
+      case opts[:dot_iex_path] do
+        ""   -> evaluator_state
+        path -> IEx.Evaluator.load_dot_iex(evaluator_state, path)
+      end
+
     prefix  = Keyword.get(opts, :prefix, "iex")
```
Comment (josevalim) [inline lib/iex/lib/iex/server.ex]: You should either remove the whitespace after `prefix` or indent the line below accordingly. :)

File: lib/iex/lib/iex/server.ex [hunk 3]
```diff
@@ -186,7 +191,7 @@ defmodule IEx.Server do
       {:input, ^input, {:error, :terminated}} ->
         exit_loop(evaluator, evaluator_ref)
       {:peek_env, receiver} ->
-        send receiver, {:peek, state.env}
+        send evaluator, {:peek, receiver}
```
Comment (josevalim) [inline lib/iex/lib/iex/server.ex]: Let's call it `{:peek_env, _}` in the evaluator too. :)

**Comment by antipax** [comment]
Thanks, code has been updated to address all of your comments, and both of those tests work as expected:

```elixir
╰─$ bin/iex
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.2.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> alias Kernel, as: K
nil
iex(2)> K.P<tab>arallel
Kernel.Parallel
iex(3)> v
Kernel.Parallel
```

**Comment by antipax** [comment]
I'll also add that with this PR, the example in #3914 no longer exhibits the undesirable behavior when evaluating `1` after generating large data.

File: lib/iex/lib/iex/server.ex [hunk 4]
```diff
@@ -82,7 +82,8 @@ defmodule IEx.Server do
               {^ref, nil} ->
                 {:error, :refused}
               {^ref, leader} ->
-                IEx.Evaluator.start(server, leader)
+                {_, evaluator_state} = run_state(opts)
```
Comment (josevalim) [inline lib/iex/lib/iex/server.ex]: This is changing the semantics of the code because `run_state` will now run twice, once here and another one inside IEx.Server run. My recommendation would be to move the whole run_state function to the Evaluator because building the state of the server is now very straight-forward. Make the evaluator receive the `opts`, instead of the state, and build everything in there.

Comment (josevalim) [inline lib/iex/lib/iex/server.ex]: This will also bring some benefits like: IEx.Evaluator.load_dot_iex no longer needs to be public. :)

Comment (antipax) [inline lib/iex/lib/iex/server.ex]: That's true, I wasn't sure if this was OK but figured you'd mention if it wasn't. :)

**Comment by josevalim** [comment]
Because we are changing take_over, you should also try IEx.pry and see if it works as expected after your changes. :) Thank you!

**Comment by antipax** [comment]
Gotcha, will test that as well. No problem!

**Comment by antipax** [comment]
Ok, comments addressed and retested. Looks good to me:

```elixir
╰─$ bin/iex
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.2.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> alias Kernel, as: K
nil
iex(2)> K.Parallel
Kernel.Parallel
iex(3)> v
Kernel.Parallel
iex(4)> require IEx
nil
iex(5)> &IEx.pry/0
#Function<20.54118792/0 in :erl_eval.expr/5>
iex(6)> v.()
Request to pry #PID<0.57.0> at iex:5. Allow? [Yn] Y

Interactive Elixir (1.2.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
pry(1)> K.Parallel
Kernel.Parallel
```

File: lib/iex/lib/iex/evaluator.ex [hunk 5]
```diff
@@ -10,33 +10,51 @@ defmodule IEx.Evaluator do
...
     try do
-      loop(server, IEx.History.init)
+      loop(server, IEx.History.init, run_state(opts))
     after
       Process.group_leader(self, old_leader)
     end
   end
 
-  defp loop(server, history) do
+  defp loop(server, history, evaluator_state) do
```
Comment (lexmag) [inline lib/iex/lib/iex/evaluator.ex]: Since it is evaluator's state we could name it just `state` and use `iex_state` for server's state respectively.
I think it'll reduce visual noise and improve readability.

**Comment by lexmag** [comment]
I think it worth to ping @tonini, as Alchemist may depend on this part as I remember.

File: lib/iex/lib/iex/evaluator.ex (hunk 5 above)
Comment (antipax) [inline lib/iex/lib/iex/evaluator.ex]: Good call

File: lib/iex/lib/iex/evaluator.ex [hunk 6]
```diff
@@ -10,33 +10,51 @@ defmodule IEx.Evaluator do
...
         :ok
     end
   end
 
-  @doc """
-  Locates and loads an .iex.exs file from one of predefined locations.
-  Returns the new state.
-  """
-  def load_dot_iex(state, path \\ nil) do
+  defp run_state(opts) do
```
Comment (josevalim) [inline lib/iex/lib/iex/evaluator.ex]: Sorry, minor nitpick: we should call it `loop_state` now or `evaluator_state`. :) It was called `run_state` before because it was the state of the `run` function (confusing name, sorry).

**Comment by josevalim** [comment]
Beautiful, thank you! I have added just one super tiny comment and we are good to go! :D

**Comment by josevalim** [comment]
Thank you! I will rename the function locally because I decided to improve a couple other things on the file, unrelated to this PR. :)  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
