### PR TITLE
Fix bug in Macro.to_string. Fix #4065.

### LINKED ISSUE #4065: Losing brackets in Code.string_to_quoted
Hi! 

I'm losing brackets if I use Code.string_to_quoted in this case:

```elixir
$ iex
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.1.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> "(acc || [a: []])[:a]" |> Code.string_to_quoted |> elem(1) |> Macro.to_string
"acc || [a: []][:a]"
```

I think `(acc || [a: []])[:a]` is not the same `acc || [a: []][:a]`

### PR DESCRIPTION
**Pull request by tuvistavie**
This fixes the `Access.get` case in `Macro.to_string` to put parenthesis when the left hand side operand is an application.
This fixes #4065.
It does add unneeded parentheses for cases like

```elixir
Macro.to_string(quote do: Dict.put(%{}, "foo", "bar")["foo"])
```

If this is an issue, I can work on it.

### CODE REVIEW

**Comment by lexmag** [comment]
I think we should handle `Macro.to_string(quote do: Dict.put(%{}, "foo", "bar")["foo"])` with unneeded parentheses.

File: lib/elixir/lib/macro.ex [hunk 1]
```diff
@@ -585,6 +585,9 @@ defmodule Macro do
   end
 
   # Access
+  def to_string({{:., _, [Access, :get]}, _, [{_, _, [_|_]} = left, right]} = ast, fun) do
```
Comment (lexmag) [inline lib/elixir/lib/macro.ex]: I think you could limit this function "head" to only match on `@binary_ops` and this should help to keep `Macro.to_string(quote do: Dict.put(%{}, "foo", "bar")["foo"])` intact.

File: lib/elixir/lib/macro.ex [hunk 2]
```diff
@@ -585,6 +585,9 @@ defmodule Macro do
...
+    fun.(ast, "(" <> to_string(left, fun) <> ")" <> to_string([right], fun))
+  end
```
Comment (lexmag) [inline lib/elixir/lib/macro.ex]: The newline is needed to match the style with the rest of `to_string` definitions.

Comment (tuvistavie) [inline lib/elixir/lib/macro.ex]: Thanks for the feedback, I'm on it!

**Comment by tuvistavie** [comment]
@lexmag I just updated my commit. This should now only add parentheses for binary ops.

**Comment by josevalim** [comment]
Looks beautiful! Ship it @lexmag!

**Comment by lexmag** [comment]
@tuvistavie Thank you. :yellow_heart:
