### PR TITLE
StringIO read_line performance and binread bug fix

### LINKED ISSUE #6037: Performance problem reading from StringIO
### Environment

Mac OS 10.12.4 on an older Macbook Pro

```
> elixir --version
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.2
```

### Current behavior

Reading from a `StringIO` using `IO.read(pid, :line)` is extremely slow. In the benchmark below with 30,000 lines it takes 2,500 times longer to read from a `StringIO` than to read from a file.

### Expected behavior

I would expect reading from a `StringIO` to have similar performance to reading from a file. Furthermore, I would expect to read N lines in O(N) time.

### Benchmark

```elixir
defmodule Read do
  def with_timing(label, pid) do
    {micro_sec, :ok} = :timer.tc(fn -> until_eof(pid) end)
    IO.puts "#{label}: #{round(micro_sec / 1_000)}ms"
  end

  def until_eof(pid) do
    case IO.read(pid, :line) do
      :eof -> :ok
      line when is_binary(line) -> until_eof(pid)
    end
  end
end

num_lines = 30_000
IO.puts "Number of lines: #{num_lines}"

lots_of_lines =
  0..num_lines
  |> Enum.map(fn _ -> "abcdefghijklmnopqrstuvwxyz" end)
  |> Enum.join("\n")

{:ok, pid} = StringIO.open(lots_of_lines)

Read.with_timing("StringIO", pid)

# For comparison, read the same lines from file
path = "/tmp/lots_of_lines.txt"
File.write!(path, lots_of_lines, [:utf8])

file_pid = File.open!(path, [:read, :utf8])
Read.with_timing("File", file_pid)
```

### Results

```
➜ elixir perf.exs
Number of lines: 10000
StringIO: 56336ms
File: 94ms
➜ elixir perf.exs
Number of lines: 20000
StringIO: 291517ms
File: 172ms
➜ elixir perf.exs
Number of lines: 30000
StringIO: 616679ms
File: 247ms
```

### PR DESCRIPTION
**Pull request by balexand**
This pull request currently consists of 3 separate commits:

1. bf28be6243392a5c40367d329fa7ed233e257a2b Adds test coverage to the existing implementation.
2. 2a475a6a8d1e80b1c8790915b0d08a3eb4357429 Fixes #6037, the performance/scalability problem.
3. c7e821394841c3eda7743f37933a60d501675125 Fixes a bug. `IO.binread` should return raw bytes instead of decoding the input as if it were Latin1. See [this comment](https://github.com/elixir-lang/elixir/issues/6037#issuecomment-298233279).

I can split the last item into a separate pull-request if desired.

Using [this benchmark](https://gist.github.com/balexand/629e37f97865ce404f002199c3b406cd), each `IO.read(pid, :line)` call takes:

```
Before: 2557µs when N=5,000 O(N)
After: 14µs O(1)
```

`StringIO.get_until` suffers from the same performance problem but I've avoided touching it (and `collect_line`) because it has almost no test coverage. When I delete the entire function the only test that fails is:

```
1) test with get until (ExUnit.CaptureIOTest)
   test/ex_unit/capture_io_test.exs:196
   Assertion with == failed
   code:  capture_io(fn -> :io.scan_erl_form('>') end) == ">"
   left:  ""
   right: ">"
   stacktrace:
     test/ex_unit/capture_io_test.exs:197: (test)
```

I'd be happy to work on `get_until` in a separate pull-request. But first, does `StringIO` even need to support `get_until` or can we delete it? Also, is there any documentation about `get_until` other than http://erlang.org/doc/apps/stdlib/io_protocol.html?

### CODE REVIEW

**Comment by balexand** [comment]
The only supported encodings are UTF-8 and Latin1 (which is interpreted as "read raw bytes"). If any other encoding is passed then an error will be returned. See https://github.com/elixir-lang/elixir/issues/6037#issuecomment-298233279

**Comment by balexand** [comment]
I just noticed that section 2.2 of http://erlang.org/doc/apps/stdlib/io_protocol.html documents that `:unicode` and `:latin1` are the only allowed encodings.

**Comment by josevalim** [comment]
Notice there is a discussion here: http://erlang.org/pipermail/erlang-bugs/2014-July/004498.html

Notice I am proposing 3 for this particular case because StringIO is meant to only work with Unicode anyway (we don't allow the device to change).

File: lib/elixir/lib/string_io.ex [hunk 1]
```diff
@@ -263,37 +257,21 @@ defmodule StringIO do
...
-        s =
-          if capture_prompt do
-            %{s | output: <<output::binary, IO.chardata_to_string(prompt)::binary>>}
-          else
-            s
-          end
+      s = capture_prompt(s, prompt)
 
-        {result, %{s | input: input}}
+      {result, %{s | input: input}}
```
Comment (kelvinst) [inline lib/elixir/lib/string_io.ex]: As you're already refactoring it for performance purposes, why not sending `input` as a parameter for capture prompt and doing this mapset together with the `output` attribute in the [`capture_prompt\2`](https://github.com/elixir-lang/elixir/pull/6056/files#diff-b27997fe2e28aaac3723720c70523ea1R342) function?

This is also duplicated code with [`get_chars\4`](https://github.com/elixir-lang/elixir/pull/6056/files#diff-b27997fe2e28aaac3723720c70523ea1R226)

Comment (kelvinst) [inline lib/elixir/lib/string_io.ex]: PS.: if it's because of naming purposes, you can always rename the function right?

File: lib/elixir/lib/string_io.ex [hunk 2]
```diff
@@ -359,6 +337,25 @@ defmodule StringIO do
...
+
+  defp binary_collect(<<head::utf8, tail::binary>>, :unicode, acc) do
+    binary_collect(tail, :unicode, <<acc::binary, head::utf8 >>)
+  end
+
+  defp binary_collect(<<head, tail::binary>>, :latin1, acc) do
+    binary_collect(tail, :latin1, <<acc::binary, head >>)
+  end
+
+  defp binary_collect(<<_::binary>>, _, _), do: :error
```
Comment (michalmuskala) [inline lib/elixir/lib/string_io.ex]: I'm pretty sure it should be enough to just count the characters and do a `:erlang.split_binary` at the end. This way we can avoid copying.

Comment (balexand) [inline lib/elixir/lib/string_io.ex]: I've made this change in 20b1df39515a99bad31ab190ca6a3f2f7b90a176.

I guess I should have known to do that since you gave me the exact same advice in a [different PR](https://github.com/elixir-lang/elixir/pull/6044#issuecomment-298150724) a few days ago 😄 . This change definitely improves the performance, especially when reading large lines. When I run the benchmark with each line containing 5,000 characters then this change results in a 25% reduction in time.

In the `split_at_eol` function I'm dealing with lines ending in `"\r\n"`. It's a little ugly, but it seems fast. Please let me know if you have any suggestions about how to improve this.

File: lib/elixir/lib/string_io.ex (hunk 1 above)
Comment (balexand) [inline lib/elixir/lib/string_io.ex]: First, let me make sure I understand you correctly. Are you suggesting replacing `capture_prompt/2` with a function like:

```elixir
defp state_after_read(%{capture_prompt: false} = s, remainder, _prompt) do
  %{s | input: remainder}
end
defp state_after_read(%{capture_prompt: true, output: output} = s, remainder, prompt) do
  %{s | input: remainder, output: <<output::binary, IO.chardata_to_string(prompt)::binary>>}
end
```

so that 

```
s = capture_prompt(s, prompt)
{result, %{s | input: remainder}}
```

can be replaced by 

```elixir
{result, state_after_read(s, remainder, prompt)}
```

?

This works but has no measurable impact on performance (setting an item in a map is fast). It's a question of code style and I don't have a preference. Please let me know if you think.

Comment (kelvinst) [inline lib/elixir/lib/string_io.ex]: Yep, that's what I was thinking.

And, I guess you're right, the impact on performance is secondary. Even if it's clear that what I suggested is really faster, it's not that much (one less attribution and one less item set in the map for one case) and it falls into code preferences. 

I prefer my suggestion anyways. :)

Comment (balexand) [inline lib/elixir/lib/string_io.ex]: I've added this change in d28aa65448ce47211691e4c1ce9d0d0af8fd863c.

File: lib/elixir/lib/string_io.ex [hunk 3]
```diff
@@ -359,6 +344,28 @@ defmodule StringIO do
...
+  defp state_after_read(%{capture_prompt: false} = s, remainder, _prompt) do
+    %{s | input: remainder}
+  end
+
+  defp state_after_read(%{capture_prompt: true, output: output} = s, remainder, prompt) do
+    %{s | input: remainder, output: <<output::binary, IO.chardata_to_string(prompt)::binary>>}
+  end
+
+  defp bytes_until_eol("", _, count), do: {:ok, count}
+  defp bytes_until_eol(<<"\r\n"::binary, _::binary>>, _, count), do: {:ok, count + 2}
```
Comment (fishcakez) [inline lib/elixir/lib/string_io.ex]: We get the `\r` information here so could pass this information in the return tuple?

File: lib/elixir/lib/string_io.ex [hunk 4]
```diff
@@ -263,35 +255,28 @@ defmodule StringIO do
...
+    with {:ok, count} <- bytes_until_eol(input, encoding, 0) do
+      {result, remainder} = case count do
+        0 -> {:eof, ""}
+        count -> split_at_eol(input, count)
+      end
 
-        {result, %{s | input: input}}
+      {result, state_after_read(s, remainder, prompt)}
+    else
+      _ -> {{:error, :collect_line}, s}
```
Comment (fishcakez) [inline lib/elixir/lib/string_io.ex]: I think this should match on `:error` to be explicit since this should be the only possible else clause, and could hide a bug.

Comment (balexand) [inline lib/elixir/lib/string_io.ex]: Done in bec17fc5697421c4fcb1cd2c4bdfb339aa6f2286.

File: lib/elixir/lib/string_io.ex (hunk 3 above)
Comment (balexand) [inline lib/elixir/lib/string_io.ex]: Done in 8850fa51f1b83bf697104ff57d936aa2a3ab18ae. Cleaner code and a bit faster too. Thanks!

File: lib/elixir/lib/string_io.ex [hunk 5]
```diff
@@ -263,35 +255,24 @@ defmodule StringIO do
...
-            %{s | output: <<output::binary, IO.chardata_to_string(prompt)::binary>>}
-          else
-            s
-          end
-
-        {result, %{s | input: input}}
+  defp get_line(encoding, prompt, %{input: input} = s) do
+    case bytes_until_eol(input, encoding, 0) do
+      {:ok, count, replace_cr} ->
+        {result, remainder} = case count do
```
Comment (fishcakez) [inline lib/elixir/lib/string_io.ex]: We should try to avoid a nested case, especially when it is not required because it makes the code less clear. I think we could add `{:ok, 0, false}` pattern to top level case to handle this one. Note that we don't need to have a 3-tuple we could have `{:split, count} | {:replace_split, count} | :error`.

Comment (balexand) [inline lib/elixir/lib/string_io.ex]: Done in d960c58bf8fda3ef2fc7285e1be9d32ee3b7d647. I've played around with an alternative implementation ([see Gist](https://gist.github.com/balexand/eada286ce46019cfac333947ed877065)) that avoids some repetition but adds a nested case.
