### PR TITLE
Forbid using only the "else" clause in "try"

### LINKED ISSUE #8146: Should the compiler warn about an unmatched `else`?
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.7.1 (compiled with Erlang/OTP 21)
* Operating system: MacOS High Sierra (10.13.6)

## Problem

I was just in a debugging session with a colleague where the bug came down to an incorrectly-nested `else`. A minimal reproduction is:

```elixir
defmodule Else do
  def weirdness do
    with true <- true do
      IO.puts("yay")
    end
  else
    match -> IO.inspect(["wat", match])
  end
end

Else.weirdness() # => prints both `"yay"` and `["wat", :ok]`
```

We were very confused to have both the `do` clause of the `with` executed and also the `else`. Eventually we realized that the problem is that the `else` is not nested in the `with`. (Side note: the value of `_match` here is `:ok`, but I don't know why.)

Perhaps an even more minimal reproduction is:

```elixir
defmodule LonelyElse do
  def here do
  else
    match -> IO.inspect(["wat", match])
  end
end
LonelyElse.here() # => prints `["wat", nil]`
```

I don't think either of these `else` clauses makes sense. Could the compiler issue a warning in cases where an `else` does not have a matching `if` or `with` or `catch`?

### PR DESCRIPTION
**Pull request by whatyouhide**
Closes #8146.

Now using `else` without a `rescue`, `catch`, or `after` in `try` expressions is not allowed anymore.

I started with not allowing `else` by itself but I wonder if it would make sense to also disallow `else` if the only other clause is `after`. `else` is there to handle what happens if nothing is caught/rescued, so it might make sense to disallow `else`/`after` as well. Let me know your thoughts!

### CODE REVIEW

**Comment by fishcakez** [comment]
else/after has valid use case, e.g.
```elixir
file = File.open!("file")
try do
   handle_file(file)
else
  result ->
    handle_result(result)
after
  File.close!(file)
end
```

**Comment by whatyouhide** [comment]
@fishcakez isn't that the same as:

```elixir
file = File.open!("file")
try do
   result = handle_file(file)
    handle_result(result)
after
  File.close!(file)
end
```

?

File: lib/elixir/test/elixir/kernel/expansion_test.exs [hunk 1]
```diff
@@ -1653,6 +1657,21 @@ defmodule Kernel.ExpansionTest do
...
+            try do
+              :ok
+            else
+              other -> other
+            end
+          end
+
+        expand(code)
+      end
+    end
```
Comment (josevalim) [inline lib/elixir/test/elixir/kernel/expansion_test.exs]: We also need a test for this:

```elixir
def foo do
  :ok
else
  other -> other
end
```

and we need to make sure that we don't say "try" in the error message but rather definition or something similar. If you look at `elixir_def.erl`, you can see that we set the `{origin, _}` attribute in the `try` node, exactly so we know the origin of the try.

Comment (whatyouhide) [reply lib/elixir/test/elixir/kernel/expansion_test.exs]: I pushed an update, please have a look cause I'm not sure it's the best way of doing this. FWIW, there are other places where we say something bad happened in `try` but it really happened in `def`:

```
iex(2)> defmodule Foo do
...(2)> def foo() do
...(2)> :ok
...(2)> catch
...(2)> _ -> :catch
...(2)> rescue
...(2)> _ -> :rescue
...(2)> end
...(2)> end
warning: "catch" should always come after "rescue" in try
  iex:3
```

Should we fix them (separate PR)>

Comment (josevalim) [reply lib/elixir/test/elixir/kernel/expansion_test.exs]: > Should we fix them (separate PR)?

Up to you!

Comment (whatyouhide) [reply lib/elixir/test/elixir/kernel/expansion_test.exs]: Yep, separate PR! :)

File: lib/elixir/src/elixir_clauses.erl [hunk 2]
```diff
@@ -186,6 +186,13 @@ expand_with_else(Meta, Opts, E, HasMatch) ->
   form_error(Meta, ?key(E, file), elixir_expand, {missing_option, 'try', [do]});
 'try'(Meta, [{do, _}], E) ->
   form_error(Meta, ?key(E, file), elixir_expand, {missing_option, 'try', ['catch', 'rescue', 'after', 'else']});
+'try'(Meta, [{do, _}, {else, _}], E) ->
+  Kind =
+    case lists:keyfind(origin, 1, Meta) of
+      {origin, Origin} -> Origin;
+      false -> 'try'
+    end,
```
Comment (josevalim) [inline lib/elixir/src/elixir_clauses.erl]: I believe we already do this elsewhere in this file too, maybe we should put this behind a private function? Something like `origin(Meta, 'try')`?

Comment (whatyouhide) [reply lib/elixir/src/elixir_clauses.erl]: @josevalim I want to do this as the next PR, where I fix the other similar cases I mentioned. Would that work for you?
