### PR TITLE
Raise exception when passing negative delta to assert_in_delta/4

### LINKED ISSUE #6439: Third parameter of assert_in_delta...
If the third parameter of `assert_in_delta` is less than zero, the assertion never passes.

But a negative value makes no sense, so I believe that the code should take the absolute value of the delta before testing.

This issue arises if you want to test against a variable delta:

~~~ elixir
a = -1
b = -1.00001

# are A and B the same to 1%
assert_in_delta a, b, a/100
~~~

### PR DESCRIPTION
**Pull request by devonestes**
I agreed with @josevalim's idea of raising an exception here rather
than coercing the negative delta, so I implemented that. As a user, I
would find that coercion to be unexpected behavior, and I personally
felt the value of being explicit here outweighed the convenience of the
coercion. I did, however, put in the exception message a helpful hint
in the case that the user did want the absolute value of that negative
delta instead.

Fixes #6439

### CODE REVIEW

File: lib/ex_unit/lib/ex_unit/assertions.ex [hunk 1]
```diff
@@ -600,7 +600,9 @@ defmodule ExUnit.Assertions do
   end
 
   @doc """
-  Asserts that `value1` and `value2` differ by no more than `delta`.
+  Asserts that `value1` and `value2` differ by no more than `delta`. All `delta`s
```
Comment (josevalim) [inline lib/ex_unit/lib/ex_unit/assertions.ex]: The paragraph of documentation should always be a short summary. The summary is used by tools like ExDoc.

File: lib/ex_unit/lib/ex_unit/assertions.ex [hunk 2]
```diff
@@ -609,7 +611,11 @@ defmodule ExUnit.Assertions do
       assert_in_delta 10, 15, 4
 
   """
-  def assert_in_delta(value1, value2, delta, message \\ nil) do
+  def assert_in_delta(value1, value2, delta, message \\ nil)
+  def assert_in_delta(_, _, delta, _) when delta < 0 do
+    raise ArgumentError, "All deltas must be positive. Did you mean #{abs(delta)}?"
```
Comment (josevalim) [inline lib/ex_unit/lib/ex_unit/assertions.ex]: Error messages start in lowercase.

**Comment by josevalim** [comment]
Thanks for the PR! :heart: I have added some cosmetic comments!

**Comment by devonestes** [comment]
Cosmetic (💄 ) changes addressed!

File: lib/ex_unit/lib/ex_unit/assertions.ex [hunk 3]
```diff
@@ -609,7 +609,11 @@ defmodule ExUnit.Assertions do
       assert_in_delta 10, 15, 4
 
   """
-  def assert_in_delta(value1, value2, delta, message \\ nil) do
+  def assert_in_delta(value1, value2, delta, message \\ nil)
+  def assert_in_delta(_, _, delta, _) when delta < 0 do
+    raise ArgumentError, "all deltas must be positive. Did you mean #{abs(delta)}?"
```
Comment (lexmag) [inline lib/ex_unit/lib/ex_unit/assertions.ex]: We can use `-delta` here instead of `abs(delta)` since we already know that `delta` is negative.

Comment (devonestes) [inline lib/ex_unit/lib/ex_unit/assertions.ex]: Of course! I'll make that change now.

Comment (whatyouhide) [inline lib/ex_unit/lib/ex_unit/assertions.ex]: I don't think this is a good error message with the "did you mean" thing. I think we should have the user decide however they want to fix this error, for example they might want to use `abs/1` even if this is negative and we know it because they might want both positive and negative numbers to work. I believe the correct error message here is what we almost always say, which is something along the lines of

```
delta must always be a positive number, got: #{inspect(delta)}
```

Wdyt?

Comment (whatyouhide) [inline lib/ex_unit/lib/ex_unit/assertions.ex]: (btw I can push directly on the PR and fix the error message if you prefer :))

Comment (devonestes) [inline lib/ex_unit/lib/ex_unit/assertions.ex]: That make sense to me. I'm happy to stick with the convention!

**Comment by whatyouhide** [comment]
Thanks @devonestes! 💟
