### PR TITLE
Handle unused :uniq comprehensions

### LINKED ISSUE #12107: Confusing warning generated by misused for comprehension with uniq
### Elixir and Erlang/OTP versions

Erlang/OTP 24 [erts-12.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.0-rc.1 (b0153d5) (compiled with Erlang/OTP 24)

### Operating system

any

### Current behavior

When compiled, this code
```
defmodule Repro do
  def go(changes) do
    for change <- changes, uniq: true, do: (
      Some.fun(change)
    )
    :ok
  end
end
```
emits
```
warning: the result of calling element/2 is ignored (suppress the warning by assigning the expression to the _ variable)
```

### Expected behavior

This code is obviously wrong as the uniqueness is checked on the result of `Some.fun(change)` and not on `change` but the warning is confusing. There is no `element/2` call in the code.

### PR DESCRIPTION
**Pull request by sabiwara**
Close #12107

Hi, this is a suggestion how we could fix the issue:
- if `uniq` is true but `into` is false, it is basically the same as if uniq wasn't here, so we can ignore `uniq` (building a map with `nil` keys etc... don't make much sense)
- this is an incorrect use of `uniq`, so we should probably better add a warning that just ignore it silently

### CODE REVIEW

File: lib/elixir/src/elixir_erl_for.erl [hunk 1]
```diff
@@ -43,6 +43,18 @@ translate_into(Meta, Cases, Expr, Opts, Return, S) ->
     into -> build_into(Ann, TCases, TExpr, TInto, TUniq, SE)
   end.
 
+validate_uniq(Opts, TInto, _Meta) ->
+  case {lists:keyfind(uniq, 1, Opts), TInto} of
+    {{uniq, true}, false} ->
+      % TODO format this warning properly with Meta
+      io:format(standard_error, "warning: the option :uniq has no effect because the result is not used~n", []),
```
Comment (sabiwara) [inline lib/elixir/src/elixir_erl_for.erl:50]: I struggled a bit here and couldn't figure it the right way to warn, since `elixir_erl_for` doesn't raise any warning as of today.
I tried to do it based on some other example using `form_warn`, but `E` isn't accessible here.

Comment (josevalim) [reply lib/elixir/src/elixir_erl_for.erl:50]: We don't emit warnings from `elixir_erl_*` modules, because they don't have all relevant information. We would need to emit this from `elixir_expand` by porting `translate_block` from `elixir_erl_pass` to `elixir_expand`.

If we do so, we likely want to remove `translate_block` from `elixir_erl_pass`. To do so, we should probably normalize `into` in `elixir_expand` so a comprehension has `:into` set to `[]` if no `:reduce` and no `:into are given and the result is used. If we arrive in `elixir_erl_for` and the comprehension has no `:reduce` and no `:into`, then we assume the result is not used.

Does it make sense?

Comment (sabiwara) [reply lib/elixir/src/elixir_erl_for.erl]: OK, I think I got it working, sorry for the delay!
Is this what you had in mind @josevalim ?

**Comment by josevalim** [comment]
Absolutely beautiful :heart:

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
