### PR TITLE
Consider improper lists in ExUnit.Diff.format/3

### LINKED ISSUE #4548: ExUnit assertion differ crashes on improper lists
GenEvent crash:

```
2016-04-23 15:40:17.340 [error] GenEvent handler ExUnit.CLIFormatter installed in #PID<0.451.0> terminating
** (FunctionClauseError) no function clause matching in ExUnit.Diff.format_list/5
    (ex_unit) lib/ex_unit/diff.ex:74: ExUnit.Diff.format_list([" because"], "\e[4m", #Function<3.116801188/2 in ExUnit.CLIFormatter.handle_event/2>, false, ["[\e[31m[[[[[[[[[] | \"\\e[4m\"], \"Failed to use \\\"\"], \"foo\"], \"\\\"\"], \" (versions \"], \"0.0.1\"], \" to \"], \"0.2.0\"]\e[0m, \e[31m\")\"\e[0m]"])
    (ex_unit) lib/ex_unit/diff.ex:205: ExUnit.Diff.format_inner/3
    (ex_unit) lib/ex_unit/diff.ex:107: ExUnit.Diff.format_list/5
    (ex_unit) lib/ex_unit/diff.ex:205: ExUnit.Diff.format_inner/3
    (ex_unit) lib/ex_unit/diff.ex:107: ExUnit.Diff.format_list/5
    (ex_unit) lib/ex_unit/diff.ex:205: ExUnit.Diff.format_inner/3
    (ex_unit) lib/ex_unit/diff.ex:107: ExUnit.Diff.format_list/5
    (ex_unit) lib/ex_unit/formatter.ex:228: anonymous fn/3 in ExUnit.Formatter.format_diff/2
```

/cc @lexmag

### PR DESCRIPTION
**Pull request by lexmag**
Closes #4548.

screen shot 2016-04-24 at 15 19 38

\cc @ericmj

### CODE REVIEW

File: lib/ex_unit/test/ex_unit/diff_test.exs [hunk 1]
```diff
@@ -48,6 +48,13 @@ defmodule ExUnit.DiffTest do
     char_list2 = 'fox jumps over the lazy cat'
     expected = "'fox {ho}[jum]ps over {\\'}the {dog}[lazy cat]'"
     assert format(char_list1, char_list2, &formatter/2) == expected
+
+    # improper lists
+    assert format([1, 2], [1, 2 | 3], &formatter/2) == "[1, 2 | [3]]"
```
Comment (josevalim) [inline lib/ex_unit/test/ex_unit/diff_test.exs]: We also need a test where the improper tail is equal. :)

Comment (josevalim) [inline lib/ex_unit/test/ex_unit/diff_test.exs]: We can probably move these assertions to their own test. :)

**Comment by josevalim** [comment]
@lexmag I wonder if there is a better way to implement this. You are annotating the list as cooked but, at that point, there is nothing more to process because you certainly got to the end of the list. I am wondering if it would be better if `format_list([], [], ...)` and the improper ones called a "final" function instead of putting stuff in acc and then calling `format_list([], [])`.
