### PR TITLE
Fix: warnings-as-errors for compiling with all-warnings

### LINKED ISSUE #11628: `mix compile`'s `--warnings-as-errors` doesn't work for errors reported by `--all-warnings`
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.13.3 (compiled with Erlang/OTP 24)
```
* Operating system: 
macOS Monterney 12.2.1
or Ubuntu 20.04.3 LTS on Windows 10 x86_64 (WSL 2) / 4.19.128-microsoft-standard

### Current behavior

When running `mix compile`, it looks like warnings reported by `--all-warnings` aren't considered by `--warnings-as-errors`.
For example, create a new mix project and add an unused variable anywhere:

```
$ mix clean
$ mix compile --all-warnings --warnings-as-errors # note that `--all-warning` won't do anything, since we cleaned the project before
Compiling 1 file (.ex)
warning: variable "args" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/testmix.ex:15: Testmix.hello/1

Compilation failed due to warnings while using the --warnings-as-errors option
$ # failed as expected
$ mix compile
Compiling 1 file (.ex)
warning: variable "args" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/testmix.ex:15: Testmix.hello/1

Generated testmix app
$ mix compile --all-warnings --warnings-as-errors
warning: variable "args" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/testmix.ex:15
(compilation went fine)
```

### Expected behavior

Warning reported by the `--all-warnings` options should be treated the same as others by the `--warnings-as-errors` option, and therefore that the compilation crashed

### PR DESCRIPTION
**Pull request by MichalDolata**
Fixes #11628

### CODE REVIEW

File: lib/mix/test/mix/tasks/compile.elixir_test.exs [hunk 1]
```diff
@@ -1267,6 +1267,33 @@ defmodule Mix.Tasks.Compile.ElixirTest do
...
+
+      assert capture_io(:stderr, fn ->
+               assert catch_exit(
+                        Mix.Task.run("compile", [
+                          "--all-warnings",
+                          "--warnings-as-errors"
+                        ])
+                      )
+             end) =~ message
+    end)
```
Comment (josevalim) [inline lib/mix/test/mix/tasks/compile.elixir_test.exs:1294]:
```suggestion
      Mix.Task.clear()

      File.write!("lib/b.ex", """
      defmodule B do
      end
      """)

      # Recompiling a new file still fails due to warnings as errors
      assert capture_io(:stderr, fn ->
               catch_exit(Mix.Task.run("compile", ["--all-warnings", "--warnings-as-errors"]))
             end) =~ message
    end)
```

File: lib/mix/test/mix/tasks/compile.elixir_test.exs [hunk 2]
```diff
@@ -1267,6 +1267,33 @@ defmodule Mix.Tasks.Compile.ElixirTest do
...
+      end
+      """)
+
+      message = "variable \"unused\" is unused"
+
+      assert capture_io(:stderr, fn ->
+               Mix.Tasks.Compile.Elixir.run([]) == :ok
+             end) =~ message
+
+      assert capture_io(:stderr, fn ->
```
Comment (josevalim) [inline lib/mix/test/mix/tasks/compile.elixir_test.exs:1286]:
```suggestion
      # Stale compilation fails due to warnings as errors
      assert capture_io(:stderr, fn ->
```

File: lib/mix/test/mix/tasks/compile.elixir_test.exs [hunk 3]
```diff
@@ -1267,6 +1267,40 @@ defmodule Mix.Tasks.Compile.ElixirTest do
...
+      message = "variable \"unused\" is unused"
+
+      assert capture_io(:stderr, fn ->
+               Mix.Tasks.Compile.Elixir.run([]) == :ok
+             end) =~ message
+
+      # Stale compilation fails due to warnings as errors
+      assert capture_io(:stderr, fn ->
+               catch_exit(Mix.Task.run("compile", ["--all-warnings", "--warnings-as-errors"]))
+             end) =~ message
```
Comment (josevalim) [inline lib/mix/test/mix/tasks/compile.elixir_test.exs:1289]:
```suggestion
             end) =~ message

```

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
