### PR TITLE
Fix signature expansion when no docs

### LINKED ISSUE #10970: IEx crashing on tab completion
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 24 [RELEASE CANDIDATE 3] [erts-12.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.12.0-rc.1 (ce321f8) (compiled with Erlang/OTP 24)
```
* Operating system: Arch Linux (installed with asdf)

### Current behavior

Contents of `foo.ex`:
```ex
defmodule Foo do
  def foo(a), do: a
end
```

- Run `iex foo.ex`
- Type `Foo.foo(` and then press tab
- An error occurs:
```
iex(1)> Foo.foo(*** ERROR: Shell process terminated! (^G to start new job) ***

11:30:47.973 [error] Process #PID<0.66.0> raised an exception
** (FunctionClauseError) no function clause matching in IEx.Autocomplete.expand_signatures/2
    (iex 1.12.0-rc.1) lib/iex/autocomplete.ex:135: IEx.Autocomplete.expand_signatures(:error, #PID<0.78.0>)
    (kernel 8.0) group.erl:596: :group.get_line1/5
    (kernel 8.0) group.erl:471: :group.get_chars_loop/9
    (kernel 8.0) group.erl:181: :group.io_request/6
    (kernel 8.0) group.erl:117: :group.server_loop/3
```

This appears to happen for any user-defined functions or functions from external libraries (including ones written in Erlang), except for ones with arity 0.

### Expected behavior

IEx should not crash and a completion list should be shown.

### PR DESCRIPTION
**Pull request by v0idpwn**
Closes #10970

### CODE REVIEW

File: lib/iex/lib/iex/autocomplete.ex [hunk 1]
```diff
@@ -147,6 +147,8 @@ defmodule IEx.Autocomplete do
 
   defp expand_signatures([], shell), do: expand_local_or_var("", shell)
 
+  defp expand_signatures(_, _), do: no()
+
```
Comment (v0idpwn) [inline lib/iex/lib/iex/autocomplete.ex:151]:
```suggestion
  defp expand_signatures(_, shell), do: expand_local_or_var("", shell)
```

The other alternative: this would suggest all the alternatives from context

Comment (josevalim) [reply lib/iex/lib/iex/autocomplete.ex:151]: Yes, I would make it return an empty list instead. Can you please update the PR and add tests? Thanks.

**Comment by v0idpwn** [comment]
Hope its correct now :)

File: lib/iex/test/iex/autocomplete_test.exs [hunk 2]
```diff
@@ -398,6 +398,14 @@ defmodule IEx.AutocompleteTest do
 
     assert expand('take(') == {:yes, '', ['take(enumerable, amount)']}
     assert expand('derive(') == {:yes, '', ['derive(protocol, module, options \\\\ [])']}
+
+    eval("defmodule NoDocs do; def sample(a), do: a; end")
```
Comment (josevalim) [inline lib/iex/test/iex/autocomplete_test.exs:402]: I don't think it needs to be define in the shell. I think  you can define a function in `IEx.AutocompleteTest` itself and try to call it from the shell.

Comment (v0idpwn) [reply lib/iex/test/iex/autocomplete_test.exs]: Indeed. Changed another thing and it looks a lot better now.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
