### PR TITLE
Fix Regex.split/2 edge case with empty chunks

### LINKED ISSUE #14467: Regex.split with trailing \K works incorrectly
Elixir 1.18.3, Erlang/OTP 27.3.3
```elixir
IO.inspect Regex.split ~r/b\K/, "ababab"
IO.inspect :re.split "ababab", "b\\K"
```
returns
```
["ab", "ab", "", "ab", "", ""]
["ab", "ab", "ab", ""]
```
I think `Regex.split` should return the same result as `:re.split`. Non-trailing `\K`s and lookbehinds seem to work correctly, this is the only case.

### PR DESCRIPTION
**Pull request by sabiwara**
Closes #14467

### CODE REVIEW

File: lib/elixir/lib/regex.ex [hunk 1]
```diff
@@ -600,7 +600,7 @@ defmodule Regex do
       ["abc"]
 
       iex> Regex.split(~r//, "abc")
-      ["", "a", "b", "c", ""]
+      ["a", "b", "c", ""]
```
Comment (sabiwara) [inline lib/elixir/lib/regex.ex:603]: As mentioned [here](https://github.com/elixir-lang/elixir/issues/14467#issuecomment-2849071034), this might be a breaking change, but is consistent with `:re.split/2`

**Comment by josevalim** [comment]
Perhaps we can add a clause where we only check the length if offset != 0?

**Comment by sabiwara** [comment]
@josevalim do you mean [e212e3f](https://github.com/elixir-lang/elixir/pull/14468/commits/e212e3f4873c9fd4846fd7f509a4998adc4397da) ?

Also, I added a test for [c22e459](https://github.com/elixir-lang/elixir/pull/14468/commits/c22e45991a83b0efa809b80ca57dff7883cef451), but I'm not sure what's the correct expectation here? (with the fix, we remove one `""`)

**Review by josevalim — APPROVED** [review]

File: lib/elixir/test/elixir/regex_test.exs [hunk 2]
```diff
@@ -236,6 +238,8 @@ defmodule RegexTest do
 
     assert Regex.split(~r/[Ei]/, "Elixir", include_captures: true, parts: 3, trim: true) ==
              ["E", "l", "i", "xir"]
+
+    assert Regex.split(~r/b\K/, "abab", include_captures: true) == ["ab", "", "ab", "", "", ""]
```
Comment (josevalim) [inline lib/elixir/test/elixir/regex_test.exs:242]: Is this expected? There are no captures, is there?

Comment (josevalim) [reply lib/elixir/test/elixir/regex_test.exs:242]: Oh, nevermind, I got it.

**Review by josevalim — APPROVED** [review]

File: lib/elixir/test/elixir/regex_test.exs (hunk 2 above)
Comment (sabiwara) [reply lib/elixir/test/elixir/regex_test.exs:242]: I'm not sure TBH 😅
Do you have a good idea of a good test for this?

**Comment by sabiwara** [comment]
@josevalim OK to backport after merge?

**Comment by josevalim** [comment]
@sabiwara I would not backport it because it is not an urgent fix (it has been here for several years).

File: lib/elixir/test/elixir/regex_test.exs (hunk 2 above)
Comment (josevalim) [reply lib/elixir/test/elixir/regex_test.exs:242]: Yes, it is a good test, because it tests the very specific behaviour of \K which forgets the previous match as part of the capture. Another good test would be with `b\Kc` matching on "abcabc" that shows only c is included. Although, comparatively, it seems the test above is included one extra `""`:

```
iex(1)> Regex.split(~r/b\Kc/, "abcabc", include_captures: true)
["ab", "c", "ab", "c", ""]
```

So maybe there is more work to be done?

Comment (josevalim) [reply lib/elixir/test/elixir/regex_test.exs:242]: In other words, I would say:



Yes, it is a good test, because it tests the very specific behaviour of \K which forgets the previous match as part of the capture. Another good test would be with b\Kc matching on "abcabc" that shows only c is included. Although, comparatively, it seems the test above is included one extra "":

    Regex.split(~r/b\Kc/, "abcabc", include_captures: true)
    Regex.split(~r/b\K/, "abab", include_captures: true)

Should behave the same, except in one the capture is "" and the other it is "c".

File: lib/elixir/lib/regex.ex [hunk 3]
```diff
@@ -677,7 +677,7 @@ defmodule Regex do
     <<_::binary-size(^offset), part::binary-size(^keep), match::binary-size(^length), _::binary>> =
       string
 
-    if keep == 0 and trim do
+    if keep == 0 and (trim or (offset != 0 and length == 0)) do
```
Comment (josevalim) [inline lib/elixir/lib/regex.ex:680]: You may need this to be a cond:

```
    cond do
      keep == 0 and offset != 0 and length == 0 ->
        do_split([h | t], string, new_offset, counter - 1, trim, true)

      keep == 0 and trim ->
        [match | do_split([h | t], string, new_offset, counter - 1, trim, true)]

      true ->
        [part, match | do_split([h | t], string, new_offset, counter - 1, trim, true)]
    end
```

I haven't tested it but it may fix my additional reports below.

File: lib/elixir/test/elixir/regex_test.exs (hunk 2 above)
Comment (sabiwara) [reply lib/elixir/test/elixir/regex_test.exs:242]: Thanks for the detailed answer, this is really helpful 💜

File: lib/elixir/lib/regex.ex (hunk 3 above)
Comment (sabiwara) [reply lib/elixir/lib/regex.ex]: @josevalim [be37140](https://github.com/elixir-lang/elixir/pull/14468/commits/be3714038dfd6c2320cbd7a564e8943952e11a87)

**Review by josevalim — APPROVED** [review]
