### PR TITLE
Fix duplicate bindings causing weird behaviour

### LINKED ISSUE #11581: Elixir 1.13 breaking change on EEx
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

```
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.13.2 (compiled with Erlang/OTP 24)
```

* Operating system:  Linux amd64 (kernel 5.15)

### Current behavior

Elixir 1.13 introduced semantic recompilation and I think that brought a breaking change to how EEx compiles templates too.

Even with #11378 there are still edge cases... this breaks in 1.13.2 but not on any versions prior to 1.13

```elixir
EEx.eval_string("foo <%= bar %>", [bar: "baz", bar: 1, other: 1])
** (MatchError) no match of right hand side value: "1"
    (stdlib 3.17) erl_eval.erl:450: :erl_eval.expr/5
    (elixir 1.13.2) lib/code.ex:802: Code.eval_quoted/3 
    lib/eex.ex:286: EEx.do_eval/3
```

It is a duplicate binding with other tags after them... it does not break if the other tag is between the duplicates like:

```elixir
EEx.eval_string("foo <%= bar %>", [bar: "baz",  other: 1, bar: 1])
"foo 1"
```

That is the beauty of programming right?

### Expected behavior

It should work like 1.12 and prior :)

Thanks!

### PR DESCRIPTION
**Pull request by v0idpwn**
Before this fix, evaluating `b = a` with assignments of: `a: 1, a: 2, c:
3` would eval AST equivalent to `^c = a`. This happened due to binding
normalization generating version numbers larger than the total number of
bindings. Later in the pipeline, the number of bindings is used to
compute the next version number, which would then conflict with an
existing binding.

This commit fixes that by not increasing the version number when
a repeated binding is normalized.

Closes #11581

### CODE REVIEW

File: lib/elixir/src/elixir.erl [hunk 1]
```diff
@@ -286,12 +286,23 @@ eval_forms(Tree, RawBinding, OrigE) ->
...
+    {Pair, Value} = normalize_pair(El),
+    case maps:get(Pair, Map, nil) of
+      nil ->
+        {maps:put(Pair, Counter, Map), Counter + 1, [{Pair, Value} | Normalized]};
+      C ->
+        {maps:put(Pair, C, Map), Counter, [{Pair, Value} | Normalized]}
+    end
+  end,
+  {#{}, 0, []}, RawBindings),
+  {VarsMap, Pairs}.
```
Comment (v0idpwn) [inline lib/elixir/src/elixir.erl:305]: I can refactor this to be recursive with ease, I think it will probably look nicer :)

File: lib/elixir/src/elixir.erl [hunk 2]
```diff
@@ -286,12 +286,23 @@ eval_forms(Tree, RawBinding, OrigE) ->
...
+  {Pair, Value}.
+
+normalize_binding(RawBindings) ->
+  {VarsMap, _Counter, Pairs} = lists:foldl(fun(El, {Map, Counter, Normalized}) ->
+    {Pair, Value} = normalize_pair(El),
+    case maps:get(Pair, Map, nil) of
+      nil ->
+        {maps:put(Pair, Counter, Map), Counter + 1, [{Pair, Value} | Normalized]};
+      C ->
+        {maps:put(Pair, C, Map), Counter, [{Pair, Value} | Normalized]}
```
Comment (josevalim) [inline lib/elixir/src/elixir.erl:301]:
```suggestion
        {Map, Counter, [{Pair, Value} | Normalized]}
```

File: lib/elixir/src/elixir.erl (hunk 1 above)
Comment (josevalim) [reply lib/elixir/src/elixir.erl:305]: Yeah, let's keep the recursive format! And, instead of `maps:get+case`, please do:

```erlang
case Map of
  #{Pair := _} -> ...
  #{} -> ...
end
```

:)

File: lib/elixir/src/elixir.erl [hunk 3]
```diff
@@ -286,12 +286,20 @@ eval_forms(Tree, RawBinding, OrigE) ->
...
-  normalize_binding(Binding, [{Pair, I} | Vars], [{Pair, Value} | Acc], I + 1);
-normalize_binding([], Vars, Acc, _I) ->
-  {maps:from_list(Vars), Acc}.
+normalize_binding([Binding | NextBindings], VarsMap, Normalized, Counter) ->
+  {Pair, Value} = normalize_pair(Binding),
+  case VarsMap of
+    #{Pair := _} ->
+      normalize_binding(NextBindings, VarsMap, [{Pair, Value} | Normalized], Counter);
+    #{} ->
+      normalize_binding(NextBindings, maps:put(Pair, Counter, VarsMap), [{Pair, Value} | Normalized], Counter + 1)
```
Comment (v0idpwn) [inline lib/elixir/src/elixir.erl:295]:
```suggestion
      normalize_binding(NextBindings, VarsMap#{Pair => Counter}, [{Pair, Value} | Normalized], Counter + 1)
```

File: lib/elixir/test/elixir/code_test.exs [hunk 4]
```diff
@@ -50,8 +50,8 @@ defmodule CodeTest do
 
     test "does not raise on duplicate bindings" do
       # The order of which values win is not guaranteed, but it should evaluate successfully.
-      assert Code.eval_string("b = String.Chars.to_string(a)", a: 0, a: 1) ==
-               {"1", [{:b, "1"}, {:a, 1}]}
+      assert Code.eval_string("b = String.Chars.to_string(a)", a: 0, a: 1, c: 2) ==
```
Comment (josevalim) [inline lib/elixir/test/elixir/code_test.exs:53]:
```suggestion
      assert Code.eval_string("b = String.Chars.to_string(a)", a: 0, a: 1) ==
               {"1", [{:b, "1"}, {:a, 1}]}

      assert Code.eval_string("b = String.Chars.to_string(a)", a: 0, a: 1, c: 2) ==
```

File: lib/elixir/src/elixir.erl [hunk 5]
```diff
@@ -286,12 +286,20 @@ eval_forms(Tree, RawBinding, OrigE) ->
...
-  {maps:from_list(Vars), Acc}.
+normalize_binding([Binding | NextBindings], VarsMap, Normalized, Counter) ->
+  {Pair, Value} = normalize_pair(Binding),
+  case VarsMap of
+    #{Pair := _} ->
+      normalize_binding(NextBindings, VarsMap, [{Pair, Value} | Normalized], Counter);
+    #{} ->
+      normalize_binding(NextBindings, VarsMap#{Pair => Counter}, [{Pair, Value} | Normalized], Counter + 1)
+  end;
+
```
Comment (josevalim) [inline lib/elixir/src/elixir.erl:297]:
```suggestion
```

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
