### PR TITLE
Fix: dot path for umbrella test

### LINKED ISSUE #11689: Mix test does not accept a `./<x>` file path for a test in an umbrella app
### Precheck

* For proposing a new feature, please start a discussion on the Elixir Core mailing list: https://groups.google.com/group/elixir-lang-core
* For bugs, do a quick search and make sure the bug has not yet been reported
* Please disclose security vulnerabilities privately at elixir-security@googlegroups.com
* Do not use the issues tracker for guidance, questions or support (try Elixir Forum, Stack Overflow, Slack, etc. instead)
* Finally, be nice and have fun!

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.13.1 (compiled with Erlang/OTP 24)
```
* Operating system:  Mac 12.1, M1

### Current behavior

`mix test ./path` works inside an individual app

```
> mix test ./test/identifier_utils/identifier_grouper/hash_group_test.exs
.....

Finished in 0.1 seconds (0.1s async, 0.00s sync)
5 tests, 0 failures

Randomized with seed 601369
```

`mix test apps/app_name/path` works at the top level on an umbrella app

```
> mix test apps/profile_utils/test/identifier_utils/identifier_grouper/hash_group_test.exs
==> profile_utils
.....

Finished in 0.3 seconds (0.3s async, 0.00s sync)
5 tests, 0 failures
```

`mix test ./apps/app_name/path` does not work

```
> cd ../..
> mix test ./apps/profile_utils/test/identifier_utils/identifier_grouper/hash_group_test.exs
==> utils
Paths given to "mix test" did not match any directory/file: ./apps/profile_utils/test/identifier_utils/identifier_grouper/hash_group_test.exs
==> solve_constants
Paths given to "mix test" did not match any directory/file: ./apps/profile_utils/test/identifier_utils/identifier_grouper/hash_group_test.exs
==> schemas
Paths given to "mix test" did not match any directory/file: ./apps/profile_utils/test/identifier_utils/identifier_grouper/hash_group_test.exs
...
```

### Expected behavior

<title> should work in an umbrella app at the top level

### PR DESCRIPTION
**Pull request by MichalDolata**
Fixes #11689

### CODE REVIEW

File: lib/mix/lib/mix/tasks/test.ex [hunk 1]
```diff
@@ -425,7 +425,9 @@ defmodule Mix.Tasks.Test do
       do_run(opts, args, files)
     else
       {files_in_apps_path, files_not_in_apps_path} =
-        Enum.split_with(files, &String.starts_with?(&1, "apps/"))
+        files
+        |> Enum.map(&String.trim_leading(&1, "./"))
```
Comment (josevalim) [inline lib/mix/lib/mix/tasks/test.ex:429]: I would if instead we should do something like Path.expand and then Path.relative_to_cwd?

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
