### PR TITLE
Raise error on functions/guards without implementation

### LINKED ISSUE #9392: `defmodule X do def x do y() end; defp y() end` crashes erl compiler
### Environment

* OTP 22.1.2
* elixir f52f2c79527f5477a91876536e5f2debbdf0a51d
* Operating system: https://github.com/c0b/docker-elixir/blob/8c92148d07fc89a57706dcb22c926a96e73a4194/1.9/Dockerfile (adjusted to use today's master) on amd64 Debian testing

### Current behavior

```
iex(1)> defmodule X do def x do y() end; defp y() end
warning: implementation not provided for predefined defp y/0
  iex:1

Function: y/0
** (CompileError) iex: internal error in beam_ssa_opt;
crash reason: {case_clause,
 {'EXIT',
  {{badkey,{b_local,{b_literal,y},0}},
   [{erlang,map_get,
     [{b_local,{b_literal,y},0},
      #{{b_local,{b_literal,'__info__'},1} =>
         {st,
          [{0,
            {b_blk,#{},[],
             {b_switch,#{},
              {b_var,0},
              3,
              [{{b_literal,compile},12},
               {{b_literal,md5},12},
               {{b_literal,attributes},12},
               {{b_literal,functions},9},
               {{b_literal,macros},8},
               {{b_literal,deprecated},8},
               {{b_literal,module},7}]}}},
           {7,{b_blk,#{},[],{b_ret,#{},{b_literal,'Elixir.X'}}}},
           {8,{b_blk,#{},[],{b_ret,#{},{b_literal,[]}}}},
           {9,{b_blk,#{},[],{b_ret,#{},{b_literal,[{x,0}]}}}}, 
           {12,
            {b_blk,#{},
             [{b_set,#{},
               {b_var,{'@ssa_ret',6}},
               call,
               [{b_remote,{b_literal,erlang},{b_literal,get_module_info},2},
                {b_literal,'Elixir.X'},
                {b_var,0}]}],
             {b_ret,#{},{b_var,{'@ssa_ret',6}}}}},
           {3,
            {b_blk,#{},
             [{b_set,#{},{b_var,4},put_list,[{b_var,0},{b_literal,[]}]}],
             {b_br,#{},{b_literal,true},14,14}}},
           {14,
            {b_blk,#{},
             [{b_set,#{},
               {b_var,{'@ssa_ret',13}},
               call,
               [{b_remote,{b_literal,erlang},{b_literal,error},2},
                {b_literal,function_clause},
                {b_var,4}]}],
             {b_ret,#{},{b_var,{'@ssa_ret',13}}}}}],
          [{b_var,0}],
          15,
          #{func_info => {'Elixir.X','__info__',1},
            parameter_type_info => #{}}},
        {b_local,{b_literal,module_info},0} =>
         {st,
          [{0,
            {b_blk,#{},
             [{b_set,#{},
               {b_var,{'@ssa_ret',3}},
               call,
               [{b_remote,{b_literal,erlang},{b_literal,get_module_info},1},
                {b_literal,'Elixir.X'}]}],
             {b_ret,#{},{b_var,{'@ssa_ret',3}}}}}],
          [],4,
          #{func_info => {'Elixir.X',module_info,0},
            parameter_type_info => #{}}},
        {b_local,{b_literal,module_info},1} =>
         {st,
          [{0,
            {b_blk,#{},
             [{b_set,#{},
               {b_var,{'@ssa_ret',3}},
               call,
               [{b_remote,{b_literal,erlang},{b_literal,get_module_info},2},
                {b_literal,'Elixir.X'},
                {b_var,0}]}],
             {b_ret,#{},{b_var,{'@ssa_ret',3}}}}}],
          [{b_var,0}],
          4,
          #{func_info => {'Elixir.X',module_info,1},
            parameter_type_info => #{}}},
        {b_local,{b_literal,x},0} =>
         {st,
          #{0 =>
             {b_blk,#{},
              [{b_set,
                #{location => {"iex",1}},
                {b_var,{'@ssa_ret',3}},
                call,
                [{b_local,{b_literal,y},0}]}],
              {b_ret,#{},{b_var,{'@ssa_ret',3}}}}},
          [],4,
          #{func_info => {'Elixir.X',x,0},
            location => {"iex",1},
            parameter_type_info => #{}}}}],
     []},
    {beam_ssa_opt,phase,4,[{file,"beam_ssa_opt.erl"},{line,82}]},
    {lists,foldl,3,[{file,"lists.erl"},{line,1263}]},
    {beam_ssa_opt,module,2,[{file,"beam_ssa_opt.erl"},{line,75}]},
    {compile,'-select_passes/2-anonymous-2-',3,
     [{file,"compile.erl"},{line,675}]},
    {compile,'-internal_comp/5-anonymous-1-',3,
     [{file,"compile.erl"},{line,399}]},
    {compile,fold_comp,4,[{file,"compile.erl"},{line,426}]},
    {compile,internal_comp,5,[{file,"compile.erl"},{line,410}]}]}}}

  in function  compile:'-select_passes/2-anonymous-2-'/3 (compile.erl, line 675)
  in call from compile:'-internal_comp/5-anonymous-1-'/3 (compile.erl, line 399)
  in call from compile:fold_comp/4 (compile.erl, line 426)
  in call from compile:internal_comp/5 (compile.erl, line 410)
  in call from compile:'-do_compile/2-anonymous-0-'/2 (compile.erl, line 207)
  in call from elixir_erl_compiler:compile/3 (src/elixir_erl_compiler.erl, line 52)
  in call from elixir_erl:load_form/5 (src/elixir_erl.erl, line 442)
  in call from elixir_erl_compiler:'-spawn/2-fun-0-'/3 (src/elixir_erl_compiler.erl, line 12)
    (stdlib 3.10) lists.erl:1338: :lists.foreach/2
    (elixir 1.10.0-dev) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
```

I don't think I can reproduce this using just Erlang as it won't let me declare a function without defining it, therefore I'm filing an issue here as opposed to the Erlang issue tracker. The closest I can get to an Erlang reproducer is to dump the Core Erlang that Elixir passes to `compile:noenv_forms`:

```
module 'Elixir.X' ['__info__'/1,
                   'module_info'/0,
                   'module_info'/1,
                   'x'/0]
    attributes [%% Line 4
                'file' =
                    %% Line 4
                    [{[105|[101|[120]]],4}],
                %% Line 4
                'compile' =
                    %% Line 4
                    ['no_auto_import'],
                %% Line 4
                'spec' =
                    %% Line 4
                    [{{'__info__',1},[{'type',4,'fun',[{'type',4,'product',[{'type',4,'union',[{'atom',4,'attributes'}|[{'atom',4,'compile'}|[{'atom',4,'functions'}|[{'atom',4,'macros'}|[{'atom',4,'md5'}|[{'atom',4,'module'}|[{'atom',4,'deprecated'}]]]]]]]}]}|[{'type',4,'any',[]}]]}]}]]
'__info__'/1 =
    fun (_0) ->
        case _0 of
          <'module'> when 'true' ->
              'Elixir.X'
          <'functions'> when 'true' ->
              [{'x',0}]
          <'macros'> when 'true' ->
              []
          <Key = 'attributes'> when 'true' ->
              call 'erlang':'get_module_info'
                  ('Elixir.X', Key)
          <Key = 'compile'> when 'true' ->
              call 'erlang':'get_module_info'
                  ('Elixir.X', Key)
          <Key = 'md5'> when 'true' ->
              call 'erlang':'get_module_info'
                  ('Elixir.X', Key)
          <'deprecated'> when 'true' ->
              []
          ( <_1> when 'true' ->
                ( primop 'match_fail'
                      ({'function_clause',_1})
                  -| [{'function_name',{'__info__',1}}] )
            -| ['compiler_generated'] )
        end
'x'/0 =
    %% Line 4
    fun () ->
        case <> of
          <> when 'true' ->
              apply 'y'/0
                  ()
          ( <> when 'true' ->
                ( primop 'match_fail'
                      ({'function_clause'})
                  -| [{'function_name',{'x',0}}] )
            -| ['compiler_generated'] )
        end
'module_info'/0 =
    fun () ->
        case <> of
          <> when 'true' ->
              call 'erlang':'get_module_info'
                  ('Elixir.X')
          ( <> when 'true' ->
                ( primop 'match_fail'
                      ({'function_clause'}) 
                  -| [{'function_name',{'module_info',0}}] )
            -| ['compiler_generated'] )
        end
'module_info'/1 =
    fun (_0) ->
        case _0 of
          <X> when 'true' ->
              call 'erlang':'get_module_info'
                  ('Elixir.X', X)
          ( <_1> when 'true' ->
                ( primop 'match_fail'
                      ({'function_clause',_1})
                  -| [{'function_name',{'module_info',1}}] )
            -| ['compiler_generated'] )
        end
end
```

### Expected behavior

Just the warning/error, not a crash in the compiler.

### PR DESCRIPTION
**Pull request by ggcampinho**
When a local bodiless function is called the generated Erlang code is invalid, this commit changes the current warning to error to avoid this invalid code.

Fixes #9392

### CODE REVIEW

File: lib/elixir/lib/module/locals_tracker.ex [hunk 1]
```diff
@@ -105,28 +105,31 @@ defmodule Module.LocalsTracker do
...
-      else
-        false
-      end
-    catch
-      _, _ -> :undefined_function
+  defp undefined_local_error({set, bag}, local, false) do
+    case :ets.lookup(set, {:def, local}) do
+      [] -> :undefined_function
+      [{_, kind, _, _, _, _}] when kind in @defmacros -> :incorrect_dispatch
+      _other -> bodiless_local_error(bag, local)
```
Comment (ggcampinho) [inline lib/elixir/lib/module/locals_tracker.ex]: I added the check here to be cheaper, but I don't know if it makes sense to put all together and still keep the same name for `undefined_local_error`

File: lib/elixir/test/elixir/kernel/errors_test.exs [hunk 2]
```diff
@@ -433,6 +433,18 @@ defmodule Kernel.ErrorsTest do
     assert_eval_raise CompileError, "nofile:1: undefined function call/2", 'call foo, do: :foo'
   end
 
+  test "bodiless local function" do
+    ExUnit.CaptureIO.capture_io(:stderr, fn ->
```
Comment (ggcampinho) [inline lib/elixir/test/elixir/kernel/errors_test.exs]: I know that there is an on going discussion on #9455, but I couldn't find another way to remove the warnings, maybe I should remove the `async: true`?

File: lib/elixir/lib/module/locals_tracker.ex (hunk 1 above)
Comment (josevalim) [reply lib/elixir/lib/module/locals_tracker.ex]: Let's rollback to `ets:lookup_element` because it loads less data from the table, even if the code is ultimately uglier.

File: lib/elixir/lib/module/locals_tracker.ex [hunk 3]
```diff
@@ -105,28 +105,31 @@ defmodule Module.LocalsTracker do
...
+    end
+  end
+
+  defp bodiless_local_error(bag, local) do
+    case :ets.lookup(bag, {:clauses, local}) do
```
Comment (josevalim) [inline lib/elixir/lib/module/locals_tracker.ex]: A `ets:member` check is enough.

**Comment by josevalim** [comment]
Thanks @ggcampinho. Now that I think about it... it may be easier to simply make the existing bodiless function definition an error instead of a warning? Can you also please try such approach so we can compare them? Thank you!

**Comment by ggcampinho** [comment]
Added two commits to compare the approaches, I find the error more consistent

**Comment by whatyouhide** [comment]
I love this change :) Thanks @ggcampinho! 💟
