### PR TITLE
Revert mix do to enforce space after comma

### LINKED ISSUE #4861: mix do fails when one of the tasks has a comma in it
Debian 9 Linux
Elixir 1.3.0

As of Elixir v1.3 `mix do` incorrectly parses arguments when a task contains a comma.

Example:

```
mix do run -e "[1, 2]"
```

Before this was interpreted as one task (`run -e "[1, 2]"`), but now it is incorrectly interpreted as 2 (`run -e "[1` and `2]`), which is a syntax error.

```console
louis ~/tmp/foo $ mix do run -e "[1, 2]"
Compiling 1 file (.ex)
Generated foo app
** (TokenMissingError) nofile:1: missing terminator: ] (for "[" starting at line 1)
    (elixir) lib/code.ex:168: Code.eval_string/3
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    (mix) lib/mix/tasks/run.ex:67: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
```

I've been unable to find ways to escape the comma in the code literal here.

Thanks,
Louis

### PR DESCRIPTION
**Pull request by tuvistavie**
I reverted the `mix do` behavior, this should fix #4861.
Sorry for messing up! :sweat:

### CODE REVIEW

File: lib/mix/lib/mix/tasks/do.ex [hunk 1]
```diff
@@ -22,29 +24,21 @@ defmodule Mix.Tasks.Do do
...
-  defp gather_commands([arg | rest], current, commands) do
-    case String.split(arg, ",", parts: 2) do
-      [arg] ->
-        gather_commands(rest, [arg | current], commands)
-      [left, right] ->
-        rest    = append_unless_empty(right, rest)
-        current = append_unless_empty(left, current)
-        gather_commands(rest, [], [current | commands])
-    end
+  defp gather_commands([h | t], current, acc) do
```
Comment (lexmag) [inline lib/mix/lib/mix/tasks/do.ex]: Since we're changing this, I think better to replace one-letter variable with name from previous implementation.

Comment (tuvistavie) [inline lib/mix/lib/mix/tasks/do.ex]: Thanks for the feedback, I just updated the PR.

File: lib/mix/test/mix/tasks/do_test.exs [hunk 2]
```diff
@@ -10,16 +10,4 @@ defmodule Mix.Tasks.DoTest do
       assert_received {:mix_shell, :info, ["mix compile.app" <> _]}
     end
   end
-
-  test "gather_command ignore spaces and trailing commas" do
-    import Mix.Tasks.Do, only: [gather_commands: 1]
-    assert gather_commands(["compile", "--list,", "help"]) == [["compile", "--list"], ["help"]]
-    assert gather_commands(["compile", "--list,help"]) == [["compile", "--list"], ["help"]]
-    assert gather_commands(["help", ",compile", "--list"]) == [["help"], ["compile", "--list"]]
-    assert gather_commands(["compile", "--list", ",", "help"]) == [["compile", "--list"], ["help"]]
```
Comment (josevalim) [inline lib/mix/test/mix/tasks/do_test.exs]: I think we should keep the tests but adjust them accordingly. I think it may reveal cases we can handle, like this one.

Comment (tuvistavie) [inline lib/mix/test/mix/tasks/do_test.exs]: I just restored the tests and added one for the regression that was reported.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
