### PR TITLE
Fix bug in Enum.slice with step>1

### LINKED ISSUE #12041: Inconsistent behavior when slicing
### Elixir and Erlang/OTP versions

(Latest `main` or `1.14.0-rc.0`)

```
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.15.0-dev (9ac5acf) (compiled with Erlang/OTP 25)
```

### Operating system

macOS 12.4

### Current behavior

Slicing on a stream with a step > 1 and a start != 0 leads in an inconsistent result:

```elixir
iex(1)> 1..100 |> Stream.take(10) |> Enum.slice(-9..-1//3)
[4, 7, 10]
iex(2)>  1..100 |> Enum.take(10) |> Enum.slice(-9..-1//3)
[2, 5, 8]
```

In some cases, it could crash:
```elixir
iex(4)> 1..100 |> Stream.take(10) |> Enum.slice(-9..-1//2)
** (FunctionClauseError) no function clause matching in Enum.take_exact/2
```

Will send a PR.

### Expected behavior

```elixir
iex(1)> 1..100 |> Stream.take(10) |> Enum.slice(-9..-1//3)
[2, 5, 8]
```

### PR DESCRIPTION
**Pull request by sabiwara**
Closes #12041

### CODE REVIEW

File: lib/elixir/lib/enum.ex [hunk 1]
```diff
@@ -4469,29 +4469,15 @@ defmodule Enum do
...
         {list, count} =
-          if step == 1 do
-            enumerable
-            |> module.reduce({:cont, {[], 0}}, fn elem, {acc, count} ->
-              {:cont, {[elem | acc], count + 1}}
-            end)
-            |> elem(1)
-          else
-            # We want to count all elements but we only keep the ones we need
-            {_, {list, _, count}} =
```
Comment (sabiwara) [inline lib/elixir/lib/enum.ex:4480]: I wonder if we can keep this optimization in some cases, for instance if we know the `start` to be positive (but currently we are not passing `start` at this stage).
