### PR TITLE
mix test --listen-on-stdin will no longer exit on failure

### LINKED ISSUE #4929: --listen-on-stdin is ignored if tests fail to compile
/cc @antipax

### PR DESCRIPTION
**Pull request by antipax**
Closes #4929.

/cc @josevalim

### CODE REVIEW

File: lib/mix/lib/mix/tasks/test.ex [hunk 1]
```diff
@@ -175,6 +175,24 @@ defmodule Mix.Tasks.Test do
   def run(args) do
     {opts, files} = OptionParser.parse!(args, strict: @switches)
 
+    if opts[:listen_on_stdin] do
+      try do
+        Process.flag(:trap_exit, true)
```
Comment (josevalim) [inline lib/mix/lib/mix/tasks/test.ex]: Is trap_exit required? I am afraid it will hide actual exceptions. If we need to do like this, it would maybe be preferable to do it all on another process that always exits and use monitor to see the actual error.

Comment (antipax) [inline lib/mix/lib/mix/tasks/test.ex]: Maybe I'm missing something, but wouldn't all exceptions be logged by the code below?

Comment (josevalim) [inline lib/mix/lib/mix/tasks/test.ex]: Here is the code we have on the CLI but I am hoping it won't have to be this complex: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel/cli.ex#L70

Comment (josevalim) [inline lib/mix/lib/mix/tasks/test.ex]: Maybe you can use `System.at_exit fn _ -> ... end` to hook into CLI and wait in there (instead of exiting).

Comment (antipax) [inline lib/mix/lib/mix/tasks/test.ex]: Turns out trap_exit wasn't required, I took it out and all the tests are passing.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
