### PR TITLE
Delete counter for vars in nested quotes

### LINKED ISSUE #7709: Nested quote with bind_quoted does not work as expected
### Environment

```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]
Interactive Elixir (1.7.0-dev) - press Ctrl+C to exit (type h() ENTER for help)* 
```

Operating system: Linux/Ubuntu18

### Current behavior

Nested `quote(bind_quoted: ..., do: ...)` does not bind the quoted arguments.

```elixir
defmodule Foo do
  # works as expected
  defmacrop macro0(arg) do
    quote bind_quoted: [arg: arg] do
      {{:., [], [{:__aliases__, [alias: false], [:IO]}, :puts]}, [], [arg]}
    end 
  end
  # works as expected
  defmacrop macro1(arg) do
    quote bind_quoted: [arg: arg] do
      quote do: IO.puts(unquote arg)
    end
  end
  # raises ** (CompileError) foo.ex:37: undefined function arg/0
  defmacrop macro2(arg) do
    quote bind_quoted: [arg: arg] do
      # quote bind_quoted: [arg: arg], do: IO.puts(arg)
    end
  end
  
  defmacro __using__(_) do
    quote do
      def test0 do
        str = "world 0"
        unquote(macro0(quote do: str))
      end
      def test1 do
        str = "world 1"
        unquote(macro1(quote do: str))
      end
      def test2 do
        str = "world 2"
        unquote(macro2(quote do: str))
      end
    end
  end
end

defmodule Bar do
  use Foo 
end

Bar.test0()
Bar.test1()
Bar.test2()
```

### Expected behavior

The latter macro `macro2` should behave the same way as `macro1` since unless it’s nested, they behave the same way.

### PR DESCRIPTION
**Pull request by josevalim**
Consider the following example:

    defmodule NestedQuote do
      defmacrop macro(arg) do
        quote bind_quoted: [arg: arg] do
          quote bind_quoted: [arg: arg], do: String.duplicate(arg, 2)
        end
      end

      defmacro __using__(_) do
        quote do
          def test do
            unquote(macro("foo"))
          end
        end
      end
    end

    defmodule UseNestedQuote do
      use NestedQuote
    end

It has two macro expansions, one inside __using__/1 when it invokes
macro/1, and another when used. The issue, however, is that the
`arg` of `String.duplicate(arg, 2)` gets tagged with the context
of `macro/1` but it should be tagged with the context of `__using__`
since it is a quote inside a quote. This patch addresses this.

Closes #7709

### CODE REVIEW

File: lib/elixir/src/elixir_rewrite.erl [hunk 1]
```diff
@@ -207,6 +207,10 @@ rewrite(?map, fetch, [Map, Key]) ->
   {maps, find, [Key, Map]};
 rewrite(?map, 'fetch!', [Map, Key]) ->
   {maps, get, [Key, Map]};
+rewrite(?map, 'get', [Map, Key]) ->
```
Comment (fertapric) [inline lib/elixir/src/elixir_rewrite.erl]: Should the implementation of `Maps.get/3` use `:maps.get(key, map, default)` then? 

I was looking at past PRs, and [this was not inlined](https://github.com/elixir-lang/elixir/pull/6205#discussion_r120950701) in the past because `get/3` was not a BIF. I checked Erlang's source code, and it seems [it is not included in the `%% BIFs` section](https://github.com/erlang/otp/blob/master/lib/stdlib/src/maps.erl#L23).

I've also made some benchmarks, and apparently Elixir's implementation is faster than Erlang's.

Comment (josevalim) [reply lib/elixir/src/elixir_rewrite.erl]: Good catch. I will revert this. The only reason I added it here is because of bootstrap issues but performance should be the main criteria.

**Comment by OvermindDL1** [comment]
Ah, this explains some oddities I've seen when I work with macro's!

Looking forward to the release then!
