### PR TITLE
Raise on recursive macros

### LINKED ISSUE #9101: Compiler crash on recursive macro guards
# Versions

```
➜  ~ elixir -v
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.8.2 (compiled with Erlang/OTP 21)

# OS: 64bit Mac OS X 10.14.4 18E226
# Kernel: x86_64 Darwin 18.5.0
```
# Minimal failing example
```ex
defmodule CrashBeam do
  defmacro foo(a) when is_atom(a) do
    foo([a])
  end
end
```

# Example usage

```ex
defmodule CrashBeam do
  defmacro foo(a) when is_atom(a) do
    foo([a])
  end

  defmacro foo(a) when is_list(a) do
    quote do
      unquote(a)
    end
  end
end
```

### Current behavior

```
Compiling 1 file (.ex)
Function: foo/1

== Compilation error in file lib/crash_beam.ex ==
** (CompileError) lib/crash_beam.ex: internal error in beam_ssa_opt;
crash reason: {case_clause,
 {'EXIT',
  {{badkey,{b_local,{b_literal,foo},1}},
   [{erlang,map_get,
     [{b_local,{b_literal,foo},1},
      #{{b_local,{b_literal,'MACRO-foo'},2} =>
         {st,
          #{0 =>
             {b_blk,#{},
              [{b_set,#{},{b_var,'@ssa_bool'},{bif,is_atom},[{b_var,1}]}],
              {b_br,#{},{b_var,'@ssa_bool'},5,4}},
            3 =>
             {b_blk,#{},
              [{b_set,#{},{b_var,9},put_list,[{b_var,1},{b_literal,[]}]},
               {b_set,#{},{b_var,10},put_list,[{b_var,0},{b_var,9}]},
               {b_set,
                #{location => {"lib/crash_beam.ex",2}},
                {b_var,{'@ssa_ret',9}},
                call,
                [{b_remote,{b_literal,erlang},{b_literal,error},2},
                 {b_literal,function_clause},
                 {b_var,10}]}],
              {b_ret,#{},{b_var,{'@ssa_ret',9}}}},
            4 =>
             {b_blk,#{},
              [{b_set,#{},{b_var,{'@ssa_bool',7}},{bif,is_list},[{b_var,1}]}],
              {b_br,#{},{b_var,{'@ssa_bool',7}},8,3}},
            5 =>
             {b_blk,#{},
              [{b_set,#{},{b_var,7},put_list,[{b_var,1},{b_literal,[]}]},
               {b_set,
                #{location => {"lib/crash_beam.ex",3}},
                {b_var,{'@ssa_ret',6}},
                call,
                [{b_local,{b_literal,foo},1},{b_var,7}]}],
              {b_ret,#{},{b_var,{'@ssa_ret',6}}}},
            8 => {b_blk,#{},[],{b_ret,#{},{b_var,1}}}},
          [{b_var,0},{b_var,1}],
          10,
          #{func_info => {'Elixir.CrashBeam','MACRO-foo',2},
            location => {"lib/crash_beam.ex",2},
            parameter_type_info => #{}}},
        {b_local,{b_literal,'__info__'},1} =>
         {st,
          #{0 =>
             {b_blk,#{},[],
              {b_switch,#{},
               {b_var,0},
               3,
               [{{b_literal,compile},12},
                {{b_literal,md5},12},
                {{b_literal,attributes},12},
                {{b_literal,macros},9},
                {{b_literal,deprecated},8},
                {{b_literal,functions},8},
                {{b_literal,module},7}]}},
            3 =>
             {b_blk,#{},
              [{b_set,#{},{b_var,4},put_list,[{b_var,0},{b_literal,[]}]},
               {b_set,#{},
                {b_var,{'@ssa_ret',13}},
                call,
                [{b_remote,{b_literal,erlang},{b_literal,error},2},
                 {b_literal,function_clause},
                 {b_var,4}]}],
              {b_ret,#{},{b_var,{'@ssa_ret',13}}}},
            7 => {b_blk,#{},[],{b_ret,#{},{b_literal,'Elixir.CrashBeam'}}},
            8 => {b_blk,#{},[],{b_ret,#{},{b_literal,[]}}},
            9 => {b_blk,#{},[],{b_ret,#{},{b_literal,[{foo,1}]}}},
            12 =>
             {b_blk,#{},
              [{b_set,#{},
                {b_var,{'@ssa_ret',6}},
                call,
                [{b_remote,{b_literal,erlang},{b_literal,get_module_info},2},
                 {b_literal,'Elixir.CrashBeam'},
                 {b_var,0}]}],
              {b_ret,#{},{b_var,{'@ssa_ret',6}}}}},
          [{b_var,0}],
          14,
          #{func_info => {'Elixir.CrashBeam','__info__',1},
            parameter_type_info => #{}}},
        {b_local,{b_literal,module_info},0} =>
         {st,
          #{0 =>
             {b_blk,#{},
              [{b_set,#{},
                {b_var,{'@ssa_ret',3}},
                call,
                [{b_remote,{b_literal,erlang},{b_literal,get_module_info},1},
                 {b_literal,'Elixir.CrashBeam'}]}],
              {b_ret,#{},{b_var,{'@ssa_ret',3}}}}},
          [],4,
          #{func_info => {'Elixir.CrashBeam',module_info,0},
            parameter_type_info => #{}}},
        {b_local,{b_literal,module_info},1} =>
         {st,
          #{0 =>
             {b_blk,#{},
              [{b_set,#{},
                {b_var,{'@ssa_ret',3}},
                call,
                [{b_remote,{b_literal,erlang},{b_literal,get_module_info},2},
                 {b_literal,'Elixir.CrashBeam'},
                 {b_var,0}]}],
              {b_ret,#{},{b_var,{'@ssa_ret',3}}}}},
          [{b_var,0}],
          4,
          #{func_info => {'Elixir.CrashBeam',module_info,1},
            parameter_type_info => #{}}}}],
     []},
    {beam_ssa_opt,phase,4,[{file,"beam_ssa_opt.erl"},{line,82}]},
    {lists,foldl,3,[{file,"lists.erl"},{line,1263}]},
    {beam_ssa_opt,module,2,[{file,"beam_ssa_opt.erl"},{line,75}]},
    {compile,'-select_passes/2-anonymous-2-',3,
     [{file,"compile.erl"},{line,672}]},
    {compile,'-internal_comp/5-anonymous-1-',3,
     [{file,"compile.erl"},{line,396}]},
    {compile,fold_comp,4,[{file,"compile.erl"},{line,423}]},
    {compile,internal_comp,5,[{file,"compile.erl"},{line,407}]}]}}}

  in function  compile:'-select_passes/2-anonymous-2-'/3 (compile.erl, line 672)
  in call from compile:'-internal_comp/5-anonymous-1-'/3 (compile.erl, line 396)
  in call from compile:fold_comp/4 (compile.erl, line 423)
  in call from compile:internal_comp/5 (compile.erl, line 407)
  in call from compile:'-do_compile/2-anonymous-0-'/2 (compile.erl, line 207)
  in call from elixir_erl_compiler:compile/4 (src/elixir_erl_compiler.erl, line 52)
  in call from elixir_erl:load_form/5 (src/elixir_erl.erl, line 439)
  in call from elixir_erl_compiler:'-spawn/2-fun-0-'/3 (src/elixir_erl_compiler.erl, line 12)
    (stdlib) lists.erl:1338: :lists.foreach/2
    (elixir) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

### Expected behavior

Should return something like that: `[a]`

### PR DESCRIPTION
**Pull request by josevalim**
Closes #9101.

### CODE REVIEW

File: lib/elixir/lib/module/locals_tracker.ex [hunk 1]
```diff
@@ -114,16 +111,22 @@ defmodule Module.LocalsTracker do
...
+    case :ets.member(set, {:def, local}) do
+      true -> false
+      false -> :undefined_function
+    end
+  end
 
-      [{_, kind, _, _, _, _}] when kind in @defmacros and not macro_dispatch? ->
+  defp undefined_local_error(set, local, false) do
+    try do
+      if :ets.lookup_element(set, {:def, local}, 2) in @defmacros do
```
Comment (josevalim) [inline lib/elixir/lib/module/locals_tracker.ex]: Change those to element lookups to avoid loading a lot of data from the table.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
