### PR TITLE
Fix reentrancy of Code.eval_*

### LINKED ISSUE #15303: `Code.eval_*` functions are not reentrant
### Elixir and Erlang/OTP versions

Erlang/OTP 28 [erts-16.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.20.0-rc.4 (808075d) (compiled with Erlang/OTP 28)

### Operating system

any

### Current behavior

Repro in iex:
Nested eval:
```
Code.eval_string("""
          Code.eval_string("1 + 1")
          IO.inspect(:erlang.get({:elixir, :eval_env}), label: :inside_after_inner)
          raise "boom"
        """, [], %{Code.env_for_eval([]) | file: "foo"})
inside_after_inner: :undefined
** (RuntimeError) boom
    (elixir 1.20.0-rc.4) src/elixir.erl:369: :elixir.eval_external_handler/3
    (stdlib 7.2) erl_eval.erl:924: :erl_eval.do_apply/7
    (elixir 1.20.0-rc.4) src/elixir.erl:355: :elixir.erl_eval/3
    (elixir 1.20.0-rc.4) src/elixir.erl:326: :elixir.eval_forms/4
    (elixir 1.20.0-rc.4) lib/module/parallel_checker.ex:156: Module.ParallelChecker.verify/1
    (elixir 1.20.0-rc.4) lib/code.ex:649: Code.validated_eval_string/4
```

No nested eval - works as expected
```
Code.eval_string("""
          IO.inspect(:erlang.get({:elixir, :eval_env}), label: :inside)
          raise "boom"
        """, [], %{Code.env_for_eval([]) | file: "foo"})
inside: #Macro.Env<...
** (RuntimeError) boom
    foo:3: (file)
```

Notice after nested eval `eval_env` gets cleaned up and stacktrace on error is wrong.

Reason: unconditional process dict erase in https://github.com/elixir-lang/elixir/blob/2d6e61c4f5335f2b1eeadeab6a1be84092bd5324/lib/elixir/src/elixir.erl#L357

The same behavior affects `dbg_callback` https://github.com/elixir-lang/elixir/blob/2d6e61c4f5335f2b1eeadeab6a1be84092bd5324/lib/elixir/src/elixir.erl#L335

### Expected behavior

Three alternatives:
1. The code fixed to store nested evals on stack
2. `Code.eval_*` documented that reentrancy is not supported and leads to broken behavior
3. Hard error/warning on nested eval in runtime

### PR DESCRIPTION
**Pull request by lukaszsamson**
Keep env and dbg callbacks on stacks in process dict

Fixes #15303

### CODE REVIEW

File: lib/elixir/test/elixir/code_test.exs [hunk 1]
```diff
@@ -288,6 +288,42 @@ defmodule CodeTest do
...
     end
+
+    test "nested eval preserves outer :dbg_callback" do
+      opts = [dbg_callback: {__MODULE__, :dbg_callback_add_one, []}]
+
+      assert {2, _binding} =
+               Code.eval_string(
+                 """
+                 Code.eval_string("1 + 1")
+                 dbg(1)
```
Comment (jonatanklosko) [inline lib/elixir/test/elixir/code_test.exs]: This already works, because the `dbg` is expanded using the `dbg_callback` before `Code.eval_string` runs. So to actually test it we need this:

```suggestion
                 Code.eval_string("dbg(1)")
```

File: lib/elixir/src/elixir.erl [hunk 2]
```diff
@@ -341,20 +350,43 @@ erl_eval(Expr, Binding, Env) ->
...
+  %% is because we want to avoid passing closures to erl_eval, as that
+  %% would effectively tie the eval code to the Elixir version and it is
+  %% best if it depends solely on Erlang/OTP.
+  %%
+  %% The downside is that functions that escape the eval context will no
+  %% longer have the original environment they came from.
+  %%
+  %% We keep a stack of envs in the process dictionary so nested eval calls
+  %% in the same process do not clobber the outer env.
+  push_pdict(?elixir_eval_env, Env),
```
Comment (josevalim) [inline lib/elixir/src/elixir.erl]: I am not sure if we need the push and pop into the direct, because the try-block already captures the state. I'd do this:

```
PreviousEvalEnv = erlang:get(?elixir_eval_env),
try

after
  case PreviousEvalEnv of
    undefined -> erlang:delete(?elixir_eval_env);
    _ -> erlang:put(?elixir_eval_env, PreviousEvalEnv)
  end
end
```

The same for dbg_callback. WDYT?

File: lib/elixir/test/elixir/code_test.exs (hunk 1 above)
Comment (lukaszsamson) [reply lib/elixir/test/elixir/code_test.exs]: Nice catch, fixed

File: lib/elixir/src/elixir.erl (hunk 2 above)
Comment (lukaszsamson) [reply lib/elixir/src/elixir.erl]: Agreed, I was too fixated on stack model

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
