### PR TITLE
Fix --warnings-as-errors not catching misnamed test file warnings

### LINKED ISSUE #15105: Misnamed test files are not counted as errors
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.2.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.19.4 (compiled with Erlang/OTP 27)

### Operating system

N/A

### Current behavior

When a test file is not loaded nor ignored by `:test_load_filters` and `:test_ignore_filters`, the following warning is displayed:
```
warning: the following files do not match any of the configured `:test_load_filters` / `:test_ignore_filters`"
```

However, this "warning"-prefixed line does not seem to make `mix test ` return a non-zero exit code, even with `mix test --warnings-as-errors`.

### Expected behavior

I think it would be handy if this warning could be considered a warning, like warnings from test files.

Note that I'm open to submitting a PR if this "proposal" is accepted.

### PR DESCRIPTION
**Pull request by jdanielnd**
Fixes two cases where misnamed test file warnings were not properly handled by `--warnings-as-errors`:

- When tests fail, the exit status was not bumped by 1 for misnamed file warnings (`warn_files` was missing from the condition on the `failures > 0` branch)
- When no tests match the load filters (noop path), the `--warnings-as-errors` check was skipped entirely

Closes #15105

### CODE REVIEW

**Comment by josevalim** [comment]
I believe the idea is that, if tests fail, that status code will have higher priority.

**Comment by jdanielnd** [comment]
Makes sense, updated. Test failure exit status now takes priority. The fix only covers the noop path (when no test files match the load filters).

File: lib/mix/lib/mix/tasks/test.ex [hunk 1]
```diff
@@ -746,6 +746,16 @@ defmodule Mix.Tasks.Test do
...
         cond do
+          warnings_as_errors? and warn_files != [] ->
+            message =
+              "\nERROR! Test suite aborted after successful execution due to warnings while using the --warnings-as-errors option"
+
+            IO.puts(:stderr, IO.ANSI.format([:red, message]))
+
+            System.at_exit(fn _ ->
+              exit({:shutdown, 1})
+            end)
```
Comment (josevalim) [inline lib/mix/lib/mix/tasks/test.ex]: This is a bit duplicated now, can we please extract it into a helper?

File: lib/mix/test/mix/tasks/test_test.exs [hunk 2]
```diff
@@ -594,6 +594,39 @@ defmodule Mix.Tasks.TestTest do
       end)
     end
 
+    test "fail with exit status 1 if only misnamed test files with --warnings-as-errors (no tests to run)" do
```
Comment (josevalim) [inline lib/mix/test/mix/tasks/test_test.exs]:
```suggestion
    test "fail with exit status 1 if misnamed test files with --warnings-as-errors (no tests to run)" do
```

File: lib/mix/lib/mix/tasks/test.ex (hunk 1 above)
Comment (jdanielnd) [reply lib/mix/lib/mix/tasks/test.ex]: Done. I considered reusing `raise_or_error_at_exit` but it handles `:raise` and `recursing?` cases that do not apply here, so I went with a dedicated helper to avoid changing existing semantics.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
