### PR TITLE
Fix old initialisation for match_vars

### LINKED ISSUE #6450: Compiler fails to report line of error in source file
### Environment

* Elixir & Erlang versions (elixir --version): 
Erlang/OTP 20 [erts-9.0] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10]

Elixir 1.5.1
* Operating system: Windows 10

### Current behavior

Compiler fails to report `line of error` in source code.

This happens if you in-correctly setup a binary/bit-string function like bellow:

```
iex(14)> defmodule Test do
...(14)>   def match(<<_::size(pos)-bytes, code::8, _::bytes>>, pos) do
...(14)>     code
...(14)>   end
...(14)> end
** (CaseClauseError) no case clause matching: []
    (elixir) src/elixir_bitstring.erl:113: :elixir_bitstring.expand_each_spec/4
    (elixir) src/elixir_bitstring.erl:86: :elixir_bitstring.expand_specs/5
    (elixir) src/elixir_bitstring.erl:29: :elixir_bitstring.expand/6
    (elixir) src/elixir_bitstring.erl:9: :elixir_bitstring.expand/4
    
```
[gist] (https://gist.github.com/CharlesOkwuagwu/de07f9d3d7dbaad4da198b52d792ea48)

### Expected behavior

Compiler should indicate the line of in-correct code

### PR DESCRIPTION
**Pull request by ggcampinho**
The error was introduced with the changes on 35fae4790440cab90b85a99c04fad8de6b0f1d1a

Resolves #6450

### CODE REVIEW

**Comment by ggcampinho** [comment]
Now the tests contain a warning that I don't know how to remove
```
warning: variable "bar" does not exist and is being expanded to "bar()", please use parentheses to remove the ambiguity or change the variable name
  nofile:2
```

File: lib/elixir/test/elixir/kernel/errors_test.exs [hunk 1]
```diff
@@ -648,6 +648,14 @@ defmodule Kernel.ErrorsTest do
     assert_compile_fail CompileError,
       "nofile:1: cannot use ^x outside of match clauses",
       'x = 8; <<a, b::size(^x)>> = <<?a, ?b>>'
+
+    assert_compile_fail CompileError,
+      "nofile:2: size in bitstring expects an integer or a variable as argument, got: bar()",
+      '''
+      defmodule Kernel.ErrorsTest.InvalidSizeInBitStrings do
+        def foo(<<_::size(bar)>>), do: :ok
```
Comment (ivanovaleksey) [inline lib/elixir/test/elixir/kernel/errors_test.exs]: using `bar()` doesn't suppress the warning?

Comment (ggcampinho) [inline lib/elixir/test/elixir/kernel/errors_test.exs]: You're right, I was following the exact error described in the issue, but it doesn't matter here. Fixed on dc0e2df.

File: lib/elixir/src/elixir_clauses.erl [hunk 2]
```diff
@@ -14,7 +14,7 @@ match(Fun, Expr, #{context := Context, match_vars := Match, prematch_vars := nil
   {EExpr, EE#{context := Context, match_vars := Match, prematch_vars := nil}}.
 
 def({Meta, Args, Guards, Body}, #{match_vars := Match} = E) ->
-  {EArgs, EA}   = elixir_expand:expand(Args, E#{context := match, match_vars := []}),
+  {EArgs, EA}   = elixir_expand:expand(Args, E#{context := match, match_vars := warn}),
```
Comment (josevalim) [inline lib/elixir/src/elixir_clauses.erl]: My intuition says that match_vars should be `[]`, because they are always an empty list inside of a match. Maybe we need another solution for the problem?

**Comment by josevalim** [comment]
@ggcampinho here is a diff with the correct fix:

```diff
diff --git a/lib/elixir/src/elixir_bitstring.erl b/lib/elixir/src/elixir_bitstring.erl
index 8daa0acc4..9c77e7bb6 100644
--- a/lib/elixir/src/elixir_bitstring.erl
+++ b/lib/elixir/src/elixir_bitstring.erl
@@ -22,8 +22,8 @@ expand(BitstrMeta, Fun, [{'::', Meta, [Left, Right]} | T], Acc, E, RequireSize)
   %% on subparts, however we can't assign new variables.
   {ER, MatchSize} =
     case E of
-      {EExtracted, _} -> {EExtracted, false};          %% expand_arg,  no assigns
-      _               -> {E#{context := nil}, T /= []} %% expand, revert assigns
+      {EExtracted, _} -> {EExtracted, false}; %% expand_arg,  no assigns
+      _               -> {E#{context := nil, match_vars := warn}, T /= []} %% expand, revert assigns
     end,
```

can you please incorporate it to your branch with the relevant tests? Thank you!

**Comment by ggcampinho** [comment]
@josevalim I incorporated your diff added a comment to the test because of the warning. I re-checked and without the expansion, it causes a false-positive. Is there a better way to do that?

File: lib/elixir/test/elixir/kernel/errors_test.exs (hunk 1 above)
Comment (ggcampinho) [inline lib/elixir/test/elixir/kernel/errors_test.exs]: Re-tested this and I need the warning to have a breaking test, the ambiguous variable expansion to function is necessary to cause the error

**Comment by josevalim** [comment]
Yes, you are going to have a warning. See a way to capture warnings. See
ExUnit.CaptureIO. Maybe we already do so on this file.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

File: lib/elixir/test/elixir/kernel/errors_test.exs [hunk 3]
```diff
@@ -648,6 +650,17 @@ defmodule Kernel.ErrorsTest do
     assert_compile_fail CompileError,
       "nofile:1: cannot use ^x outside of match clauses",
       'x = 8; <<a, b::size(^x)>> = <<?a, ?b>>'
+
+    warning = capture_io(:stderr, fn ->
```
Comment (lexmag) [inline lib/elixir/test/elixir/kernel/errors_test.exs]: Looks like this test belongs to `Kernel.WarningTest`, otherwise we lose `async: true` property.

Comment (josevalim) [inline lib/elixir/test/elixir/kernel/errors_test.exs]: No, it is fine to leave it here, we shouldn't just not assert anything on the warning. @ggcampinho can you please make sure you don't assert a warning is shown? it is not the purpose of this test after all. :)

Comment (ggcampinho) [inline lib/elixir/test/elixir/kernel/errors_test.exs]: I added the test on the warning because it's necessary to happen otherwise we will get green when the test is supposed to be red, but I can take it out since it's not the purpose of the test

Comment (lexmag) [inline lib/elixir/test/elixir/kernel/errors_test.exs]: Yeah, fits better here, but then we should switch to `async: false`.

File: lib/elixir/src/elixir_bitstring.erl [hunk 4]
```diff
@@ -22,8 +22,8 @@ expand(BitstrMeta, Fun, [{'::', Meta, [Left, Right]} | T], Acc, E, RequireSize)
   %% on subparts, however we can't assign new variables.
   {ER, MatchSize} =
     case E of
-      {EExtracted, _} -> {EExtracted, false};          %% expand_arg,  no assigns
-      _               -> {E#{context := nil}, T /= []} %% expand, revert assigns
+      {EExtracted, _} -> {EExtracted, false}; %% expand_arg,  no assigns
+      _               -> {E#{context := nil, match_vars := warn}, T /= []} %% expand, revert assigns
```
Comment (lexmag) [inline lib/elixir/src/elixir_bitstring.erl]: I suppose, since we're touching this line, we can drop `->` aligning?

Comment (josevalim) [inline lib/elixir/src/elixir_bitstring.erl]: Yeah, :+1:.

File: lib/elixir/test/elixir/kernel/errors_test.exs (hunk 3 above)
Comment (josevalim) [inline lib/elixir/test/elixir/kernel/errors_test.exs]: Let's move the test to the kernel/expansion_test. It is already async: false and arguably a better place for this test since it does happen during expansion.

**Comment by ggcampinho** [comment]
@lexmag @josevalim I tried to follow the style of the expasion_text.exs, and the `def` is not allowed inside of the macro. So, I changed to an anonymous function that causes the same error and the warning disappears because of that. Please, let me know what do you think.

File: lib/elixir/test/elixir/kernel/expansion_test.exs [hunk 5]
```diff
@@ -1180,6 +1180,16 @@ defmodule Kernel.ExpansionTest do
     assert_raise CompileError, ~r"unhandled operator ->", fn ->
       expand(quote do: (foo -> bar))
     end
+
+    assert_raise CompileError,
```
Comment (josevalim) [inline lib/elixir/test/elixir/kernel/expansion_test.exs]: Shouldn't you also use capture_io to avoid the warning? Or we don't get a warning here?

Comment (ggcampinho) [inline lib/elixir/test/elixir/kernel/expansion_test.exs]: I was trying to use the `expand` method, but it was swallowing the warning. I couldn't find a nice way to reuse the functions, so I just added a direct call now on d39bd12

Comment (lexmag) [inline lib/elixir/test/elixir/kernel/expansion_test.exs]: We don't need to test warning message, it is not the purpose of this test, hence the `expand/1` usage is fine. 👍

File: lib/elixir/test/elixir/kernel/expansion_test.exs [hunk 6]
```diff
@@ -1198,7 +1210,7 @@ defmodule Kernel.ExpansionTest do
   end
 
   defp expand_env(expr, env) do
-    ExUnit.CaptureIO.capture_io(:stderr, fn ->
+    capture_io(:stderr, fn ->
```
Comment (lexmag) [inline lib/elixir/test/elixir/kernel/expansion_test.exs]: Please keep the old way of calling `capture_io/2`.

File: lib/elixir/test/elixir/kernel/expansion_test.exs (hunk 5 above)
Comment (ggcampinho) [inline lib/elixir/test/elixir/kernel/expansion_test.exs]: So, if I understood correctly, it's better to revert the last commit. It's done :)

The warning will be suppressed by the `expand/1`, but we don't check it, only that the `CompilationError` happens (before the code it would cause a `CaseClauseError`).

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
