### PR TITLE
Mix: fix import_config with non-matching wildcard

### LINKED ISSUE #3120: "mix" (especially "mix help") fails in the "umbrella" directory when no project was added in the apps directory
When I tried to run ```mix help``` in the top level directory of an "umbrella" project before I added a project in the ```apps``` directory it fails with the following message:
```bash
$ mix new --umbrella example
$ cd example/
$ mix help
** (Mix.Config.LoadError) could not load config apps/*/config/config.exs
    ** (Code.LoadError) could not load /home/family/bsmr/source/elixir/problems/example/apps/*/config/config.exs
    (mix) lib/mix/config.ex:141: Mix.Config.read!/1
    (mix) lib/mix/config.ex:153: anonymous fn/2 in Mix.Config.read_wildcard!/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:441: :erl_eval.expr/5
    (elixir) lib/code.ex:140: Code.eval_string/3
```
Within the ```apps``` directory ```mix help``` doesn't fail.

After a new project is added (within the ```apps``` directory) ```mix help``` doesn't fail in the top-level "umbrella directory".

**Note:** This bug showed up when I issued ```mix help```, but even without any arguments to ```mix``` it fails.

IMHO this is somewhat irritating, especially for newbies (like me) to Elixir.

### PR DESCRIPTION
**Pull request by oneeman**
Closes #3120

I'm not entirely sure about this.  It does fix the problem, while keeping the behavior of raising an error if a non-glob name of a non-existent file is received (as tested in `"import_config/1 with bad path"`).  But it seems less than ideal that a function called `read_wildcard!` handles the degenerate case of a concrete filename with no wildcards as a special case.  It would make more sense for it to treat it as a non-matching glob too (just using `Path.wildcard(path)` regardless of whether or not there are any results), but that would break the functionality of raising an error if called with a non-glob filename for a file that doesn't exist.  

There are other ways one could go (e.g. to modify `import_config` so it call either `read!` or `read_wildcard!` depending on whether or not it's a glob), but since these are public functions I figured it's best to start with the smallest change and get some feedback.

### CODE REVIEW

**Comment by ericmj** [comment]
Wouldn't it be possible to just call `Path.wildcard/1` with no case or regex? That should give us get correct behaviour.

```iex
iex(1)> File.ls!
["config.exs", "dev.exs", "prod.exs", "test.exs"]
iex(2)> Path.wildcard("*")
["config.exs", "dev.exs", "prod.exs", "test.exs"]
iex(3)> Path.wildcard("config.exs")
["config.exs"]

**Comment by oneeman** [comment]
@ericmj That was what I tried at first, but it breaks the test at https://github.com/oneeman/elixir/blob/mix-config-bugfix/lib/mix/test/mix/config_test.exs#L70-L76.  It is an option to consider, though.

File: lib/mix/lib/mix/config.ex [hunk 1]
```diff
@@ -146,9 +146,10 @@ defmodule Mix.Config do
   Reads many configuration files given by wildcard into a single config.
   """
   def read_wildcard!(config, path) do
-    paths = case Path.wildcard(path) do
-      [] -> [path]
-      o  -> o
+    paths = if path =~ ~r/[*?[{]/ do
```
Comment (josevalim) [inline lib/mix/lib/mix/config.ex]: Maybe `String.contains?(path, ~w(* ? {))`?

Comment (josevalim) [inline lib/mix/lib/mix/config.ex]: Also, should we add some code comments here explaining that we are checking for the path because we would like to raise for missing files?

**Comment by josevalim** [comment]
I ahve dropped some comments too! Thanks for tackling this!

**Comment by oneeman** [comment]
Thank you, that's perfect, I hadn't realized that `String.contains?` also accepts a list.  I added a commit with it.  For the comment, I added the note to the documentation, to make that case clear both to users looking at the API and anyone looking at the source code.  If this is all ok let me know and I'll squash the commits.

**Comment by josevalim** [comment]
Perfect, let's squash and merge!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by oneeman** [comment]
Ready to go :-)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
